<!DOCTYPE html>
<html lang="fr" xml:lang="fr">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6.1 Modèles économétriques spatiaux | Notes de cours GMQ405 : Modélisation et analyse spatiale</title>
  <meta name="description" content="Mettre le description du cours." />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="6.1 Modèles économétriques spatiaux | Notes de cours GMQ405 : Modélisation et analyse spatiale" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/introduction/ImageCouverture.png" />
  <meta property="og:description" content="Mettre le description du cours." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6.1 Modèles économétriques spatiaux | Notes de cours GMQ405 : Modélisation et analyse spatiale" />
  
  <meta name="twitter:description" content="Mettre le description du cours." />
  <meta name="twitter:image" content="/images/introduction/ImageCouverture.png" />

<meta name="author" content="Philippe Apparicio, département de géomatique appliquée, Université de Sherbrooke" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap06.html"/>
<link rel="next" href="sect062.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.1.2/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.1.2/leaflet-providers-plugin.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/quizlib.min.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">GMQ405 : modélisation et analyse spatiale</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenue</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html"><i class="fa fa-check"></i>Préface</a>
<ul>
<li class="chapter" data-level="" data-path="sect001.html"><a href="sect001.html"><i class="fa fa-check"></i>Un manuel sous la forme d’une ressource éducative libre</a></li>
<li class="chapter" data-level="" data-path="sect002.html"><a href="sect002.html"><i class="fa fa-check"></i>Comment lire ce manuel?</a></li>
<li class="chapter" data-level="" data-path="sect003.html"><a href="sect003.html"><i class="fa fa-check"></i>Comment utiliser les données du livre pour reproduire les exemples?</a></li>
<li class="chapter" data-level="" data-path="sect004.html"><a href="sect004.html"><i class="fa fa-check"></i>Structure du livre</a></li>
<li class="chapter" data-level="" data-path="sect005.html"><a href="sect005.html"><i class="fa fa-check"></i>Pourquoi faut-il programmer en géomatique appliquée et utiliser R?</a></li>
<li class="chapter" data-level="" data-path="sect006.html"><a href="sect006.html"><i class="fa fa-check"></i>Remerciements</a></li>
</ul></li>
<li class="part"><span><b>I Découverte de R</b></span></li>
<li class="chapter" data-level="1" data-path="chap01.html"><a href="chap01.html"><i class="fa fa-check"></i><b>1</b> Manipulation des données spatiales dans R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="sect011.html"><a href="sect011.html"><i class="fa fa-check"></i><b>1.1</b> Importation de données géographiques</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="sect011.html"><a href="sect011.html#sect0111"><i class="fa fa-check"></i><b>1.1.1</b> Importation de données vectorielles</a></li>
<li class="chapter" data-level="1.1.2" data-path="sect011.html"><a href="sect011.html#sect0112"><i class="fa fa-check"></i><b>1.1.2</b> Importation de données <em>raster</em></a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="sect012.html"><a href="sect012.html"><i class="fa fa-check"></i><b>1.2</b> Manipulation de données vectorielles</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="sect012.html"><a href="sect012.html#sect0121"><i class="fa fa-check"></i><b>1.2.1</b> Fonctions relatives à la projection cartographique</a></li>
<li class="chapter" data-level="1.2.2" data-path="sect012.html"><a href="sect012.html#sect0122"><i class="fa fa-check"></i><b>1.2.2</b> Fonctions d’opérations géométriques sur une couche</a></li>
<li class="chapter" data-level="1.2.3" data-path="sect012.html"><a href="sect012.html#sect01213"><i class="fa fa-check"></i><b>1.2.3</b> Fonctions d’opérations géométriques entre deux couches</a></li>
<li class="chapter" data-level="1.2.4" data-path="sect012.html"><a href="sect012.html#sect0124"><i class="fa fa-check"></i><b>1.2.4</b> Fonctions de mesures géométriques et de récupération des coordonnées géographiques</a></li>
<li class="chapter" data-level="1.2.5" data-path="sect012.html"><a href="sect012.html#sect0125"><i class="fa fa-check"></i><b>1.2.5</b> Jointures spatiales</a></li>
<li class="chapter" data-level="1.2.6" data-path="sect012.html"><a href="sect012.html#sect0126"><i class="fa fa-check"></i><b>1.2.6</b> Requêtes spatiales</a></li>
<li class="chapter" data-level="1.2.7" data-path="sect012.html"><a href="sect012.html#sect0127"><i class="fa fa-check"></i><b>1.2.7</b> Manipulation des données attributaires</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="sect013.html"><a href="sect013.html"><i class="fa fa-check"></i><b>1.3</b> Manipulation de données <em>raster</em></a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="sect013.html"><a href="sect013.html#sect0131"><i class="fa fa-check"></i><b>1.3.1</b> Mosaïquage et découpage d’images</a></li>
<li class="chapter" data-level="1.3.2" data-path="sect013.html"><a href="sect013.html#sect0132"><i class="fa fa-check"></i><b>1.3.2</b> Requêtes attributaires sur des images</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="sect014.html"><a href="sect014.html"><i class="fa fa-check"></i><b>1.4</b> Exportation de données spatiales de R vers des formats géographiques</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="sect014.html"><a href="sect014.html#sect0141"><i class="fa fa-check"></i><b>1.4.1</b> Exportation de données vectorielles <code>sf</code></a></li>
<li class="chapter" data-level="1.4.2" data-path="sect014.html"><a href="sect014.html#sect0142"><i class="fa fa-check"></i><b>1.4.2</b> Exportation de données <em>raster</em></a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="sect015.html"><a href="sect015.html"><i class="fa fa-check"></i><b>1.5</b> Cartographie avec R</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="sect015.html"><a href="sect015.html#sect0151"><i class="fa fa-check"></i><b>1.5.1</b> Manipulation des couches géométriques</a></li>
<li class="chapter" data-level="1.5.2" data-path="sect015.html"><a href="sect015.html#sect0152"><i class="fa fa-check"></i><b>1.5.2</b> Cartes interactives</a></li>
<li class="chapter" data-level="1.5.3" data-path="sect015.html"><a href="sect015.html#sect0153"><i class="fa fa-check"></i><b>1.5.3</b> Mise en page d’une carte</a></li>
<li class="chapter" data-level="1.5.4" data-path="sect015.html"><a href="sect015.html#sect0154"><i class="fa fa-check"></i><b>1.5.4</b> Exportation d’une carte</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="sect016.html"><a href="sect016.html"><i class="fa fa-check"></i><b>1.6</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="1.7" data-path="sect017.html"><a href="sect017.html"><i class="fa fa-check"></i><b>1.7</b> Exercices de révision</a></li>
</ul></li>
<li class="part"><span><b>II Autocorrélation spatiale</b></span></li>
<li class="chapter" data-level="2" data-path="chap02.html"><a href="chap02.html"><i class="fa fa-check"></i><b>2</b> Autocorrélation spatiale</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sect021.html"><a href="sect021.html"><i class="fa fa-check"></i><b>2.1</b> Notion d’autocorrélation spatiale</a></li>
<li class="chapter" data-level="2.2" data-path="sect022.html"><a href="sect022.html"><i class="fa fa-check"></i><b>2.2</b> Matrices de pondération spatiale</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="sect022.html"><a href="sect022.html#sect0221"><i class="fa fa-check"></i><b>2.2.1</b> Matrices de contiguïté</a></li>
<li class="chapter" data-level="2.2.2" data-path="sect022.html"><a href="sect022.html#sect0222"><i class="fa fa-check"></i><b>2.2.2</b> Matrices de proximité spatiale</a></li>
<li class="chapter" data-level="2.2.3" data-path="sect022.html"><a href="sect022.html#sect0223"><i class="fa fa-check"></i><b>2.2.3</b> Standardisation des matrices de pondération spatiale en ligne</a></li>
<li class="chapter" data-level="2.2.4" data-path="sect022.html"><a href="sect022.html#sect0224"><i class="fa fa-check"></i><b>2.2.4</b> Construction de matrices de pondération spatiale dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="sect023.html"><a href="sect023.html"><i class="fa fa-check"></i><b>2.3</b> Autocorrélation spatiale globale</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="sect023.html"><a href="sect023.html#sect0231"><i class="fa fa-check"></i><b>2.3.1</b> Statistique du <em>I</em> de Moran</a></li>
<li class="chapter" data-level="2.3.2" data-path="sect023.html"><a href="sect023.html#sect0232"><i class="fa fa-check"></i><b>2.3.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="sect024.html"><a href="sect024.html"><i class="fa fa-check"></i><b>2.4</b> Autocorrélation spatiale locale</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="sect024.html"><a href="sect024.html#sect0241"><i class="fa fa-check"></i><b>2.4.1</b> Statistiques locales de Getis et Ord : repérer les points chauds et froids</a></li>
<li class="chapter" data-level="2.4.2" data-path="sect024.html"><a href="sect024.html#sect0242"><i class="fa fa-check"></i><b>2.4.2</b> Version locale du <em>I</em> de Moran</a></li>
<li class="chapter" data-level="2.4.3" data-path="sect024.html"><a href="sect024.html#sect0243"><i class="fa fa-check"></i><b>2.4.3</b> Nuage de points du <em>I</em> de Moran d’Anselin</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="sect025.html"><a href="sect025.html"><i class="fa fa-check"></i><b>2.5</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="2.6" data-path="sect026.html"><a href="sect026.html"><i class="fa fa-check"></i><b>2.6</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap03.html"><a href="chap03.html"><i class="fa fa-check"></i><b>3</b> Méthodes de répartition ponctuelle</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sect031.html"><a href="sect031.html"><i class="fa fa-check"></i><b>3.1</b> Fréquence et densité des points dans l’espace d’étude</a></li>
<li class="chapter" data-level="3.2" data-path="sect032.html"><a href="sect032.html"><i class="fa fa-check"></i><b>3.2</b> Analyse centrographique</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sect032.html"><a href="sect032.html#sect0311"><i class="fa fa-check"></i><b>3.2.1</b> Paramètres de tendance centrale d’un semis de points</a></li>
<li class="chapter" data-level="3.2.2" data-path="sect032.html"><a href="sect032.html#sect0312"><i class="fa fa-check"></i><b>3.2.2</b> Paramètres de dispersion d’un semis de points</a></li>
<li class="chapter" data-level="3.2.3" data-path="sect032.html"><a href="sect032.html#sect0313"><i class="fa fa-check"></i><b>3.2.3</b> Mise en œuvre de l’analyse centrographique dans R</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sect033.html"><a href="sect033.html"><i class="fa fa-check"></i><b>3.3</b> Forme d’un semis de points</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="sect033.html"><a href="sect033.html#sect0331"><i class="fa fa-check"></i><b>3.3.1</b> Méthode du plus proche voisin</a></li>
<li class="chapter" data-level="3.3.2" data-path="sect033.html"><a href="sect033.html#sect0332"><i class="fa fa-check"></i><b>3.3.2</b> Méthode des quadrats</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="sect034.html"><a href="sect034.html"><i class="fa fa-check"></i><b>3.4</b> Identification des agrégats spatiaux</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="sect034.html"><a href="sect034.html#sect0341"><i class="fa fa-check"></i><b>3.4.1</b> Cartographie de la densité dans une maille irrégulière</a></li>
<li class="chapter" data-level="3.4.2" data-path="sect034.html"><a href="sect034.html#sect0342"><i class="fa fa-check"></i><b>3.4.2</b> Cartographie de la densité dans une maille régulière</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="sect035.html"><a href="sect035.html"><i class="fa fa-check"></i><b>3.5</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="3.6" data-path="sect036.html"><a href="sect036.html"><i class="fa fa-check"></i><b>3.6</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap04.html"><a href="chap04.html"><i class="fa fa-check"></i><b>4</b> Méthodes de détection d’agrégats spatiaux et spatio-temporels</a>
<ul>
<li class="chapter" data-level="4.1" data-path="sect041.html"><a href="sect041.html"><i class="fa fa-check"></i><b>4.1</b> Agrégats d’entités spatiales ponctuelles</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="sect041.html"><a href="sect041.html#sect0411"><i class="fa fa-check"></i><b>4.1.1</b> DBSCAN : agrégats spatiaux</a></li>
<li class="chapter" data-level="4.1.2" data-path="sect041.html"><a href="sect041.html#sect0412"><i class="fa fa-check"></i><b>4.1.2</b> ST-DBSCAN : agrégats spatio-temporels</a></li>
<li class="chapter" data-level="4.1.3" data-path="sect041.html"><a href="sect041.html#sect0414"><i class="fa fa-check"></i><b>4.1.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="sect042.html"><a href="sect042.html"><i class="fa fa-check"></i><b>4.2</b> Méthodes de balayage de Kulldorff</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="sect042.html"><a href="sect042.html#sect0421"><i class="fa fa-check"></i><b>4.2.1</b> Objectifs de la méthode, types d’analyses, de modèles et d’agrégats</a></li>
<li class="chapter" data-level="4.2.2" data-path="sect042.html"><a href="sect042.html#sect0422"><i class="fa fa-check"></i><b>4.2.2</b> Principes de base de la méthode</a></li>
<li class="chapter" data-level="4.2.3" data-path="sect042.html"><a href="sect042.html#sect043"><i class="fa fa-check"></i><b>4.2.3</b> Mise en oeuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="sect044.html"><a href="sect044.html"><i class="fa fa-check"></i><b>4.3</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="4.4" data-path="sect045.html"><a href="sect045.html"><i class="fa fa-check"></i><b>4.4</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap05.html"><a href="chap05.html"><i class="fa fa-check"></i><b>5</b> Mesures d’accessibilité spatiale selon les différents de modes de transport</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sect051.html"><a href="sect051.html"><i class="fa fa-check"></i><b>5.1</b> Notions relatives à l’analyse de réseau</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="sect051.html"><a href="sect051.html#sect0511"><i class="fa fa-check"></i><b>5.1.1</b> Définition d’un réseau</a></li>
<li class="chapter" data-level="5.1.2" data-path="sect051.html"><a href="sect051.html#sect0512"><i class="fa fa-check"></i><b>5.1.2</b> Principaux problèmes résolus en analyse de réseau</a></li>
<li class="chapter" data-level="5.1.3" data-path="sect051.html"><a href="sect051.html#sect0513"><i class="fa fa-check"></i><b>5.1.3</b> Analyse de réseau et entités polygonales</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="sect052.html"><a href="sect052.html"><i class="fa fa-check"></i><b>5.2</b> Construction d’un réseau avec R5R</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="sect052.html"><a href="sect052.html#sect0521"><i class="fa fa-check"></i><b>5.2.1</b> Extraction des données spatiales pour R5R</a></li>
<li class="chapter" data-level="5.2.2" data-path="sect052.html"><a href="sect052.html#sect0522"><i class="fa fa-check"></i><b>5.2.2</b> Construction du réseau avec R5R</a></li>
<li class="chapter" data-level="5.2.3" data-path="sect052.html"><a href="sect052.html#sect0523"><i class="fa fa-check"></i><b>5.2.3</b> Calcul d’itinéraires avec R5R selon le mode de transport</a></li>
<li class="chapter" data-level="5.2.4" data-path="sect052.html"><a href="sect052.html#sect0524"><i class="fa fa-check"></i><b>5.2.4</b> Calcul de matrices OD selon différents modes de transport</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="sect053.html"><a href="sect053.html"><i class="fa fa-check"></i><b>5.3</b> Mesures d’accessibilité</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="sect053.html"><a href="sect053.html#sect0531"><i class="fa fa-check"></i><b>5.3.1</b> Notion d’accessibilité</a></li>
<li class="chapter" data-level="5.3.2" data-path="sect053.html"><a href="sect053.html#sect0532"><i class="fa fa-check"></i><b>5.3.2</b> Accessibilité spatiale potentielle</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="sect054.html"><a href="sect054.html"><i class="fa fa-check"></i><b>5.4</b> Mesures d’accessibilité spatiale potentielle dans R</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="sect054.html"><a href="sect054.html#sect0541"><i class="fa fa-check"></i><b>5.4.1</b> Accessibilité spatiale potentielle aux supermarchés</a></li>
<li class="chapter" data-level="5.4.2" data-path="sect054.html"><a href="sect054.html#sect0542"><i class="fa fa-check"></i><b>5.4.2</b> Accessibilité spatiale potentielle aux patinoires extérieures</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="sect055.html"><a href="sect055.html"><i class="fa fa-check"></i><b>5.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap06.html"><a href="chap06.html"><i class="fa fa-check"></i><b>6</b> Introduction aux modèles de régression spatiale</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sect061.html"><a href="sect061.html"><i class="fa fa-check"></i><b>6.1</b> Modèles économétriques spatiaux</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="sect061.html"><a href="sect061.html#sect0611"><i class="fa fa-check"></i><b>6.1.1</b> Bref retour sur la régression linéaire multiple</a></li>
<li class="chapter" data-level="6.1.2" data-path="sect061.html"><a href="sect061.html#sect0612"><i class="fa fa-check"></i><b>6.1.2</b> Les différents modèles spatiaux autorégressifs</a></li>
<li class="chapter" data-level="6.1.3" data-path="sect061.html"><a href="sect061.html#sect0613"><i class="fa fa-check"></i><b>6.1.3</b> Quel modèle choisir?</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sect062.html"><a href="sect062.html"><i class="fa fa-check"></i><b>6.2</b> Modèles généralisés additifs (GAM) avec une <em>spline</em> bivariée sur les coordonnées géographiques</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="sect062.html"><a href="sect062.html#sect0621"><i class="fa fa-check"></i><b>6.2.1</b> Principe de base d’un GAM intégrant l’espace</a></li>
<li class="chapter" data-level="6.2.2" data-path="sect062.html"><a href="sect062.html#sect0622"><i class="fa fa-check"></i><b>6.2.2</b> Construction d’un modèle GAM dans R</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sect063.html"><a href="sect063.html"><i class="fa fa-check"></i><b>6.3</b> Régression géographiquement pondérée</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="sect063.html"><a href="sect063.html#sect0631"><i class="fa fa-check"></i><b>6.3.1</b> Principe de base</a></li>
<li class="chapter" data-level="6.3.2" data-path="sect063.html"><a href="sect063.html#sect0632"><i class="fa fa-check"></i><b>6.3.2</b> Construction et analyse du modèle GWR dans R</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="sect064.html"><a href="sect064.html"><i class="fa fa-check"></i><b>6.4</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="6.5" data-path="sect065.html"><a href="sect065.html"><i class="fa fa-check"></i><b>6.5</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap07.html"><a href="chap07.html"><i class="fa fa-check"></i><b>7</b> Introduction aux méthodes de classification spatiale</a>
<ul>
<li class="chapter" data-level="7.1" data-path="sect071.html"><a href="sect071.html"><i class="fa fa-check"></i><b>7.1</b> Bref retour sur les méthodes de classification non-supervisées</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="sect071.html"><a href="sect071.html#sect0711"><i class="fa fa-check"></i><b>7.1.1</b> Classification ascendante hiérarchique</a></li>
<li class="chapter" data-level="7.1.2" data-path="sect071.html"><a href="sect071.html#sect0712"><i class="fa fa-check"></i><b>7.1.2</b> <em>K-means</em></a></li>
<li class="chapter" data-level="7.1.3" data-path="sect071.html"><a href="sect071.html#sect0713"><i class="fa fa-check"></i><b>7.1.3</b> <em>Fuzzy c-means</em></a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="sect072.html"><a href="sect072.html"><i class="fa fa-check"></i><b>7.2</b> Méthodes de classification par agrégation intégrant une constrainte spatiale</a></li>
<li class="chapter" data-level="7.3" data-path="sect073.html"><a href="sect073.html"><i class="fa fa-check"></i><b>7.3</b> Classifications spatiales</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="sect073.html"><a href="sect073.html#sect0731"><i class="fa fa-check"></i><b>7.3.1</b> Classification ascendante hiérarchique spatiale (<em>ClustGeo</em>)</a></li>
<li class="chapter" data-level="7.3.2" data-path="sect073.html"><a href="sect073.html#sect0732"><i class="fa fa-check"></i><b>7.3.2</b> <em>Spatial fuzzy c-means</em> (SFCM)</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="sect074.html"><a href="sect074.html"><i class="fa fa-check"></i><b>7.4</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="7.5" data-path="sect075.html"><a href="sect075.html"><i class="fa fa-check"></i><b>7.5</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap08.html"><a href="chap08.html"><i class="fa fa-check"></i><b>8</b> Méthodes d’interpolation spatiale</a>
<ul>
<li class="chapter" data-level="8.1" data-path="sect081.html"><a href="sect081.html"><i class="fa fa-check"></i><b>8.1</b> Méthodes déterministes</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="sect081.html"><a href="sect081.html#sect0811"><i class="fa fa-check"></i><b>8.1.1</b> Interpolation polynomiale locale</a></li>
<li class="chapter" data-level="8.1.2" data-path="sect081.html"><a href="sect081.html#sect0812"><i class="fa fa-check"></i><b>8.1.2</b> Interpolation de l’inverse à la distance - <em>IDW</em></a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="sect082.html"><a href="sect082.html"><i class="fa fa-check"></i><b>8.2</b> Méthodes géostatistiques</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="sect082.html"><a href="sect082.html#sect0821"><i class="fa fa-check"></i><b>8.2.1</b> Krigeage simple</a></li>
<li class="chapter" data-level="8.2.2" data-path="sect082.html"><a href="sect082.html#sect0822"><i class="fa fa-check"></i><b>8.2.2</b> Krigeage universel</a></li>
<li class="chapter" data-level="8.2.3" data-path="sect082.html"><a href="sect082.html#sect0823"><i class="fa fa-check"></i><b>8.2.3</b> Co-krigeage</a></li>
<li class="chapter" data-level="8.2.4" data-path="sect082.html"><a href="sect082.html#sect0824"><i class="fa fa-check"></i><b>8.2.4</b> Krigeage résiduel</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="sect083.html"><a href="sect083.html"><i class="fa fa-check"></i><b>8.3</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="8.4" data-path="sect084.html"><a href="sect084.html"><i class="fa fa-check"></i><b>8.4</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap09.html"><a href="chap09.html"><i class="fa fa-check"></i><b>9</b> Analyse spatiale par l’analyse d’images</a>
<ul>
<li class="chapter" data-level="9.1" data-path="sect091.html"><a href="sect091.html"><i class="fa fa-check"></i><b>9.1</b> Fonctions mathématiques, booléennes, relationnelles et conditionnelles sur les images</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="sect091.html"><a href="sect091.html#sect0911"><i class="fa fa-check"></i><b>9.1.1</b> Fonctions mathématiques</a></li>
<li class="chapter" data-level="9.1.2" data-path="sect091.html"><a href="sect091.html#sect0912"><i class="fa fa-check"></i><b>9.1.2</b> Fonctions booléennes</a></li>
<li class="chapter" data-level="9.1.3" data-path="sect091.html"><a href="sect091.html#sect0913"><i class="fa fa-check"></i><b>9.1.3</b> Fonctions relationnelles</a></li>
<li class="chapter" data-level="9.1.4" data-path="sect091.html"><a href="sect091.html#sect0914"><i class="fa fa-check"></i><b>9.1.4</b> Fonctions conditionnelles</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="sect092.html"><a href="sect092.html"><i class="fa fa-check"></i><b>9.2</b> Fonctions locales, focales, zonales et globales sur les images</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="sect092.html"><a href="sect092.html#sect0921"><i class="fa fa-check"></i><b>9.2.1</b> Fonctions locales</a></li>
<li class="chapter" data-level="9.2.2" data-path="sect092.html"><a href="sect092.html#sect0922"><i class="fa fa-check"></i><b>9.2.2</b> Fonctions focales</a></li>
<li class="chapter" data-level="9.2.3" data-path="sect092.html"><a href="sect092.html#sect0923"><i class="fa fa-check"></i><b>9.2.3</b> Fonctions zonales</a></li>
<li class="chapter" data-level="9.2.4" data-path="sect092.html"><a href="sect092.html#sect0924"><i class="fa fa-check"></i><b>9.2.4</b> Fonctions globales</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="sect093.html"><a href="sect093.html"><i class="fa fa-check"></i><b>9.3</b> Fonctions de surface</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="sect093.html"><a href="sect093.html#sect0931"><i class="fa fa-check"></i><b>9.3.1</b> Élevation</a></li>
<li class="chapter" data-level="9.3.2" data-path="sect093.html"><a href="sect093.html#sect0932"><i class="fa fa-check"></i><b>9.3.2</b> Pente</a></li>
<li class="chapter" data-level="9.3.3" data-path="sect093.html"><a href="sect093.html#sect0933"><i class="fa fa-check"></i><b>9.3.3</b> Ombrage</a></li>
<li class="chapter" data-level="9.3.4" data-path="sect093.html"><a href="sect093.html#sect0934"><i class="fa fa-check"></i><b>9.3.4</b> Visibilité</a></li>
<li class="chapter" data-level="9.3.5" data-path="sect093.html"><a href="sect093.html#sect0935"><i class="fa fa-check"></i><b>9.3.5</b> Sky-view factor Index</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="sect094.html"><a href="sect094.html"><i class="fa fa-check"></i><b>9.4</b> Données spatiotemporelles en mode image</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="sect094.html"><a href="sect094.html#fichier-netcdf"><i class="fa fa-check"></i><b>9.4.1</b> Fichier <em>netCDF</em></a></li>
<li class="chapter" data-level="9.4.2" data-path="sect094.html"><a href="sect094.html#exemples-applicatifs"><i class="fa fa-check"></i><b>9.4.2</b> Exemples applicatifs</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="sect095.html"><a href="sect095.html"><i class="fa fa-check"></i><b>9.5</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="9.6" data-path="sect096.html"><a href="sect096.html"><i class="fa fa-check"></i><b>9.6</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap10.html"><a href="chap10.html"><i class="fa fa-check"></i><b>10</b> Correction des exercices</a>
<ul>
<li class="chapter" data-level="10.1" data-path="sect1001.html"><a href="sect1001.html"><i class="fa fa-check"></i><b>10.1</b> Exercices du chapitre 1</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="sect1001.html"><a href="sect1001.html#sect10011"><i class="fa fa-check"></i><b>10.1.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.1.2" data-path="sect1001.html"><a href="sect1001.html#sect10012"><i class="fa fa-check"></i><b>10.1.2</b> Exercice 2</a></li>
<li class="chapter" data-level="10.1.3" data-path="sect1001.html"><a href="sect1001.html#sect10013"><i class="fa fa-check"></i><b>10.1.3</b> Exercice 3</a></li>
<li class="chapter" data-level="10.1.4" data-path="sect1001.html"><a href="sect1001.html#sect10014"><i class="fa fa-check"></i><b>10.1.4</b> Exercice 4</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="sect1002.html"><a href="sect1002.html"><i class="fa fa-check"></i><b>10.2</b> Exercices du chapitre 2</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="sect1002.html"><a href="sect1002.html#sect10021"><i class="fa fa-check"></i><b>10.2.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.2.2" data-path="sect1002.html"><a href="sect1002.html#sect10022"><i class="fa fa-check"></i><b>10.2.2</b> Exercice 2</a></li>
<li class="chapter" data-level="10.2.3" data-path="sect1002.html"><a href="sect1002.html#sect10023"><i class="fa fa-check"></i><b>10.2.3</b> Exercice 3</a></li>
<li class="chapter" data-level="10.2.4" data-path="sect1002.html"><a href="sect1002.html#sect10024"><i class="fa fa-check"></i><b>10.2.4</b> Exercice 4</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="sect1003.html"><a href="sect1003.html"><i class="fa fa-check"></i><b>10.3</b> Exercices du chapitre 3</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="sect1003.html"><a href="sect1003.html#sect10031"><i class="fa fa-check"></i><b>10.3.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.3.2" data-path="sect1003.html"><a href="sect1003.html#sect10032"><i class="fa fa-check"></i><b>10.3.2</b> Exercice 2</a></li>
<li class="chapter" data-level="10.3.3" data-path="sect1003.html"><a href="sect1003.html#sect10033"><i class="fa fa-check"></i><b>10.3.3</b> Exercice 3</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="sect1004.html"><a href="sect1004.html"><i class="fa fa-check"></i><b>10.4</b> Exercices du chapitre 4</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="sect1004.html"><a href="sect1004.html#sect10041"><i class="fa fa-check"></i><b>10.4.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.4.2" data-path="sect1004.html"><a href="sect1004.html#sect10042"><i class="fa fa-check"></i><b>10.4.2</b> Exercice 2</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="sect1005.html"><a href="sect1005.html"><i class="fa fa-check"></i><b>10.5</b> Exercices du chapitre 5</a></li>
<li class="chapter" data-level="10.6" data-path="sect1006.html"><a href="sect1006.html"><i class="fa fa-check"></i><b>10.6</b> Exercices du chapitre 6</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="sect1006.html"><a href="sect1006.html#sect10061"><i class="fa fa-check"></i><b>10.6.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.6.2" data-path="sect1006.html"><a href="sect1006.html#sect10062"><i class="fa fa-check"></i><b>10.6.2</b> Exercice 2</a></li>
<li class="chapter" data-level="10.6.3" data-path="sect1006.html"><a href="sect1006.html#sect10063"><i class="fa fa-check"></i><b>10.6.3</b> Exercice 3</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="sect1007.html"><a href="sect1007.html"><i class="fa fa-check"></i><b>10.7</b> Exercices du chapitre 7</a></li>
<li class="chapter" data-level="10.8" data-path="sect1008.html"><a href="sect1008.html"><i class="fa fa-check"></i><b>10.8</b> Exercices du chapitre 8</a></li>
<li class="chapter" data-level="10.9" data-path="sect1009.html"><a href="sect1009.html"><i class="fa fa-check"></i><b>10.9</b> Exercices du chapitre 9</a></li>
<li class="chapter" data-level="10.10" data-path="sect1011.html"><a href="sect1011.html"><i class="fa fa-check"></i><b>10.10</b> Exercices du chapitre 11</a></li>
<li class="chapter" data-level="10.11" data-path="sect1012.html"><a href="sect1012.html"><i class="fa fa-check"></i><b>10.11</b> Excercice du chapitre 12</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notes de cours GMQ405 :
Modélisation et analyse spatiale</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sect061" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Modèles économétriques spatiaux<a href="sect061.html#sect061" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="bloc_attention">
<p><strong>Régression linéaire multiple et modèles économétriques spatiaux</strong></p>
<p>Dans cette section, nous décrivons uniquement les modèles économétriques spatiaux dont la variable dépendante est continue. Sommairement, ces modèles sont des extensions de la régression linéaire multiple dans laquelle est intégrée l’autocorrélation spatiale. Avant de lire cette section, il faut donc bien maîtriser la régression linéaire multiple. Si ce n’est pas le cas, nous vous invitons vivement à lire le <a href="https://laeq.github.io/LivreMethoQuantBolR/chap07.html">chapitre suivant</a> <span class="citation">(<a href="#ref-RBoldAir" role="doc-biblioref">Apparicio et Gelb 2022</a>)</span>.</p>
<p>Ces deux dernières décennies, plusieurs ouvrages traitant des modèles économétriques spatiaux ont été publiés, surtout en anglais <span class="citation">(<a href="#ref-lesage2008introduction" role="doc-biblioref">LeSage et Pace 2008</a>; <a href="#ref-anselin2014modern" role="doc-biblioref">Anselin et Rey 2014</a>; <a href="#ref-bivand2008applied" role="doc-biblioref">Bivand et al. 2008</a>)</span>. Ils méritent grandement d’être consultés, tout comme l’excellent livre en français de Jean Dubé et Diègo Legros <span class="citation">(<a href="#ref-dube2014econometrie" role="doc-biblioref">2014</a>)</span>.</p>
</div>
<p><strong>Pourquoi recourir à des modèles économétriques spatiaux?</strong></p>
<p>Dans un modèle, les résidus (<span class="math inline">\(\epsilon\)</span>) sont la différence entre les valeurs observées (<span class="math inline">\(y_i\)</span>) et les valeurs prédites par le modèle (<span class="math inline">\(\widehat{y_i}\)</span>). Une des hypothèses de la régression linéaire multiple est que les observations doivent être indépendantes les unes des autres (<em>indépendance du terme d’erreur</em>). Le non-respect de cette hypothèse produit des résultats biaisés, notamment pour les coefficients de régression.</p>
<p>Lorsque les observations sont des entités spatiales (polygones, points par exemple), si les résidus du modèle sont autocorrélées spatialement, il y a un problème de dépendance spatiale du modèle. Autrement dit, les observations ne sont pas spatialement indépendantes les unes des autres. Pour vérifier la dépendance spatiale d’un modèle, il suffit de calculer le <em>I</em> de Moran sur les résidus du modèle, comme décrit au chapitre 2 (section <a href="sect023.html#sect023">2.3</a>).</p>
<p>Autrement dit, un modèle régression construit à des données spatiales ne devrait pas avoir des résidus spatialement autocorrélés. Or, les modèles économétriques spatiaux permettent justement d’intégrer l’autocorrélation spatiale de différentes manières afin de s’assurer que l’hypothèse de l’indépendance du terme d’erreur soit respectée.</p>
<div id="sect0611" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Bref retour sur la régression linéaire multiple<a href="sect061.html#sect0611" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>À titre de rappel, la régression linéaire multiple permet de prédire et d’expliquer une variable dépendante (<span class="math inline">\(Y\)</span>) en fonction de plusieurs variables indépendantes (<span class="math inline">\(X\)</span>). L’équation de régression s’écrit alors :</p>
<p><span class="math display" id="eq:regmultiple1">\[\begin{equation}
y_i = \beta_{0} + \beta_{1}x_{1i} + \beta_{2}x_{2i} +\ldots+ \beta_{k}x_{ki} + \epsilon_{i}
\tag{6.1}
\end{equation}\]</span>
</p>
<p>avec :</p>
<ul>
<li><span class="math inline">\(y_i\)</span>, la valeur de la variable dépendante <em>Y</em> pour l’observation <em>i</em></li>
<li><span class="math inline">\(\beta_{0}\)</span>, la constante, soit la valeur prédite pour <em>Y</em> quand toutes les variables indépendantes sont égales à 0</li>
<li><span class="math inline">\(k\)</span> le nombre de variables indépendantes</li>
<li><span class="math inline">\(\beta_{1}\)</span> à <span class="math inline">\(\beta_{k}\)</span>, les coefficients de régression pour les variables indépendantes de 1 à <em>k</em> (<span class="math inline">\(X_{1}\)</span> à <span class="math inline">\(X_{k}\)</span>)</li>
<li><span class="math inline">\(\epsilon_{i}\)</span>, le résidu pour l’observation de <em>i</em>, soit la partie de la valeur de <span class="math inline">\(y_i\)</span> qui n’est pas expliquée par le modèle de régression.</li>
</ul>
<p>il existe plusieurs écritures simplifiées de cette équation. Dans le cadre de ce chapitre, nous utilisons la forme matricielle suivante :</p>
<p><span class="math display" id="eq:MCO">\[\begin{equation}
y = X\beta + \epsilon
\tag{6.2}
\end{equation}\]</span>
</p>
<p>avec :</p>
<ul>
<li><span class="math inline">\(y\)</span>, un vecteur de dimension <span class="math inline">\(n \times 1\)</span> pour la variable dépendante, soit une colonne avec <em>n</em> observations</li>
<li><span class="math inline">\(X\)</span>, une matrice de dimension <span class="math inline">\(n \times (k + 1)\)</span> pour les <em>k</em> variables indépendantes, incluant une autre colonne (avec la valeur de 1 pour les <em>n</em> observations) pour la constante d’où <span class="math inline">\(k + 1\)</span></li>
<li><span class="math inline">\(\beta\)</span>, un vecteur de dimension <span class="math inline">\(k + 1\)</span>, soit les coefficients de régression pour les <em>k</em> variables et la constante</li>
<li><span class="math inline">\(\epsilon\)</span>, un vecteur de dimension <span class="math inline">\(n \times 1\)</span> pour les résidus.</li>
</ul>
<p><strong>Construction du modèle MCO dans R</strong></p>
<p>Avec la fonction <code>lm()</code>, il est facile de construire un modèle de régression linéaire multiple, basé sur la méthodes des moindres carrés ordinaires (MCO).
Dans le code ci-dessous, la formule de l’équation du modèle est donc <code>NO2 ~ Pct0_14+Pct_65+Pct_Img+Pct_brevet+NivVieMed</code>. Notez que la variable dépendante et les variables indépendantes sont séparées avec un tilde (<code>~</code>). Quant à la fonction <code>summary(NomDuModèle)</code>, elle affiche les résultats du modèle.</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="sect061.html#cb431-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Appel des différents packages utilisés dans le chapitre</span></span>
<span id="cb431-2"><a href="sect061.html#cb431-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spdep)</span>
<span id="cb431-3"><a href="sect061.html#cb431-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Construction du modèle</span></span>
<span id="cb431-4"><a href="sect061.html#cb431-4" aria-hidden="true" tabindex="-1"></a>Modele.MCO <span class="ot">&lt;-</span> <span class="fu">lm</span>(NO2 <span class="sc">~</span> Pct0_14<span class="sc">+</span>Pct_65<span class="sc">+</span>Pct_Img<span class="sc">+</span>Pct_brevet<span class="sc">+</span>NivVieMed,</span>
<span id="cb431-5"><a href="sect061.html#cb431-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> LyonIris)</span>
<span id="cb431-6"><a href="sect061.html#cb431-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Résultats du modèle</span></span>
<span id="cb431-7"><a href="sect061.html#cb431-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Modele.MCO)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = NO2 ~ Pct0_14 + Pct_65 + Pct_Img + Pct_brevet + 
##     NivVieMed, data = LyonIris)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -27.733  -4.457  -0.499   3.507  29.160 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 49.43296    2.99550  16.502  &lt; 2e-16 ***
## Pct0_14     -0.53352    0.06305  -8.461 2.94e-16 ***
## Pct_65      -0.15047    0.05627  -2.674  0.00774 ** 
## Pct_Img      0.28287    0.05113   5.532 5.12e-08 ***
## Pct_brevet  -0.24004    0.03721  -6.451 2.63e-10 ***
## NivVieMed   -0.31625    0.10180  -3.107  0.00200 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.685 on 500 degrees of freedom
## Multiple R-squared:  0.2832, Adjusted R-squared:  0.276 
## F-statistic:  39.5 on 5 and 500 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Dépendance spatiale du modèle MCO?</strong></p>
<p>Pour vérifier si ce modèle linéaire multiple a un problème de dépendance spatiale, nous calculons le <em>I</em> de Moran sur ses résidus avec la fonction <code>lm.morantest</code>, puis nous les cartographions.</p>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="sect061.html#cb433-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Matrice de contiguïté selon le partage d&#39;un segment (Rook)</span></span>
<span id="cb433-2"><a href="sect061.html#cb433-2" aria-hidden="true" tabindex="-1"></a>Rook <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(LyonIris, <span class="at">queen=</span><span class="cn">FALSE</span>)</span>
<span id="cb433-3"><a href="sect061.html#cb433-3" aria-hidden="true" tabindex="-1"></a>W.Rook <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(Rook, <span class="at">zero.policy=</span><span class="cn">TRUE</span>, <span class="at">style =</span> <span class="st">&quot;W&quot;</span>)</span>
<span id="cb433-4"><a href="sect061.html#cb433-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Autocorrélation spatiale globale des résidus</span></span>
<span id="cb433-5"><a href="sect061.html#cb433-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.morantest</span>(Modele.MCO, W.Rook, <span class="at">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Global Moran I for regression residuals
## 
## data:  
## model: lm(formula = NO2 ~ Pct0_14 + Pct_65 + Pct_Img + Pct_brevet +
## NivVieMed, data = LyonIris)
## weights: W.Rook
## 
## Moran I statistic standard deviate = 21.266, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided
## sample estimates:
## Observed Moran I      Expectation         Variance 
##      0.587312061     -0.005375800      0.000776745</code></pre>
<p>Avec une valeur du <em>I</em> de Moran de 0,587 (<em>p</em> &lt; 0,001), les résidus sont fortement autocorrélés spatialement, traduisant ainsi un problème de dépendance spatiale du modèle MCO et la nécessité de recourir à des modèles économétriques spatiaux. La cartographie des résidus à la figure <a href="sect061.html#fig:figCartoRes">6.2</a> corrobore ce résultat.</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="sect061.html#cb435-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb435-2"><a href="sect061.html#cb435-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Ajout du colonne dans LyonIris avec les valeurs des résidus</span></span>
<span id="cb435-3"><a href="sect061.html#cb435-3" aria-hidden="true" tabindex="-1"></a>LyonIris<span class="sc">$</span>ModeleMCO.Residus <span class="ot">&lt;-</span> <span class="fu">residuals</span>(Modele.MCO)</span>
<span id="cb435-4"><a href="sect061.html#cb435-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Cartographie</span></span>
<span id="cb435-5"><a href="sect061.html#cb435-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">&quot;plot&quot;</span>)</span>
<span id="cb435-6"><a href="sect061.html#cb435-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span></span>
<span id="cb435-7"><a href="sect061.html#cb435-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;ModeleMCO.Residus&quot;</span>, <span class="at">n =</span> <span class="dv">5</span>, <span class="at">style =</span> <span class="st">&quot;quantile&quot;</span>, </span>
<span id="cb435-8"><a href="sect061.html#cb435-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">&quot;-RdBu&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Résidus&quot;</span>) <span class="sc">+</span></span>
<span id="cb435-9"><a href="sect061.html#cb435-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb435-10"><a href="sect061.html#cb435-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figCartoRes"></span>
<img src="GMQ405_files/figure-html/figCartoRes-1.png" alt="Cartographie des résidus du modèle de régression multiple" width="672" />
<p class="caption">
Figure 6.2: Cartographie des résidus du modèle de régression multiple
</p>
</div>
</div>
<div id="sect0612" class="section level3 hasAnchor" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> Les différents modèles spatiaux autorégressifs<a href="sect061.html#sect0612" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Selon Jean Dubé et Diègo Legros, « cinq raisons peuvent motiver le choix d’un modèle autorégressif : la présence d’externalités, les effets d’entraînement, l’omission de variables importantes, la présence d’hétérogénéité spatiale des comportements, les effets mixtes » <span class="citation">(<a href="#ref-dube2014econometrie" role="doc-biblioref">2014, 120</a>)</span>. Les effets mixtes peuvent être la combinaison d’externalités avec des effets d’entraînement ou encore d’externalités avec l’omission d’une ou plusieurs variables importantes spatialement structurées.</p>
<div id="sect06121" class="section level4 hasAnchor" number="6.1.2.1">
<h4><span class="header-section-number">6.1.2.1</span> Modèle SLX : autocorrélation spatiale sur les variables indépendantes<a href="sect061.html#sect06121" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Dans un modèle SLX, l’autocorrélation spatiale est intégrée au niveau des variables indépendantes. Autrement dit, les variables indépendantes spatialement décalées (<span class="math inline">\(WX\)</span>) sont introduites aussi dans le modèle. Par conséquent, la valeur de chaque unité spatiale du modèle est ainsi expliquée à la fois par ses propres caractéristiques et celles dans le voisinage ou à proximité en fonction de la matrice de pondération spatiale (<span class="math inline">\(W\)</span>).</p>
<div class="bloc_aller_loin">
<p><strong>Rappel sur les variables spatialement décalées</strong></p>
<p>Dans chapitre 2 sur l’autocorrélation spatiale, nous avons vu comment calculer une variable spatialement décalée avec un matrice de pondération spatiale (figure <a href="sect024.html#fig:Chap02FigureVariableSpatialementDecalee">2.20</a>). À titre de rappel, lorsque cette dernière est standardisée en ligne, elle correspond à la valeur moyenne dans le voisinage.</p>
</div>
<p>L’idée est alors d’introduire des <strong>externalités</strong> puisque les caractéristiques des entités spatiales proches ou voisines peuvent avoir un effet sur la variable dépendante <span class="citation">(<a href="#ref-dube2014econometrie" role="doc-biblioref">Dubé et Legros 2014</a>)</span>. L’équation du modèle SLX, qui est estimée selon la méthode des moindres carrés ordinaires (comme la régression linéaire multiple), s’écrit alors :</p>
<p><span class="math display" id="eq:SLX">\[\begin{equation}
y = X\beta + WX\theta + \epsilon
\tag{6.3}
\end{equation}\]</span>
</p>
<p>avec :</p>
<ul>
<li><span class="math inline">\(y\)</span>, la variable dépendante</li>
<li><span class="math inline">\(X\)</span>, les variables indépendantes</li>
<li><span class="math inline">\(\beta\)</span>, les coefficients des variables dépendantes</li>
<li><span class="math inline">\(W\)</span>, la matrice de pondération spatiale</li>
<li><span class="math inline">\(WX\)</span>, les variables dépendantes spatiales décalés</li>
<li><span class="math inline">\(\theta\)</span>, les coefficients des variables dépendantes spatiales décalées</li>
<li><span class="math inline">\(\epsilon\)</span>, les résidus.</li>
</ul>
<p><strong>Construction du modèle SLX dans R</strong></p>
<p>Le modèle SLX est construit avec la fonction <code>lmSLX</code> du <em>package</em> <code>spatialreg</code> <span class="citation">(<a href="#ref-bivand2021review" role="doc-biblioref">Bivand, Millo et Piras 2021</a>)</span>. Remarquez dans le code ci-dessous le paramètre <code>listw=W.Rook</code> qui est utilisé pour spécifier la matrice de pondération spatiale.</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="sect061.html#cb436-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatialreg)</span>
<span id="cb436-2"><a href="sect061.html#cb436-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Construction du modèle</span></span>
<span id="cb436-3"><a href="sect061.html#cb436-3" aria-hidden="true" tabindex="-1"></a>Modele.SLX <span class="ot">&lt;-</span> <span class="fu">lmSLX</span>(NO2 <span class="sc">~</span> Pct0_14<span class="sc">+</span>Pct_65<span class="sc">+</span>Pct_Img<span class="sc">+</span>Pct_brevet<span class="sc">+</span>NivVieMed,</span>
<span id="cb436-4"><a href="sect061.html#cb436-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">listw=</span>W.Rook,     <span class="co"># matrice de pondération spatiale</span></span>
<span id="cb436-5"><a href="sect061.html#cb436-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> LyonIris)  <span class="co"># dataframe</span></span>
<span id="cb436-6"><a href="sect061.html#cb436-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Résultats du modèle</span></span>
<span id="cb436-7"><a href="sect061.html#cb436-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Résultats du modèles</span></span>
<span id="cb436-8"><a href="sect061.html#cb436-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Modele.SLX)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = formula(paste(&quot;y ~ &quot;, paste(colnames(x)[-1], collapse = &quot;+&quot;))), 
##     data = as.data.frame(x), weights = weights)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -18.6087  -3.5084  -0.7178   2.9128  26.8724 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    50.67786    4.18791  12.101  &lt; 2e-16 ***
## Pct0_14        -0.20404    0.06268  -3.255  0.00121 ** 
## Pct_65         -0.03771    0.05361  -0.703  0.48217    
## Pct_Img         0.10406    0.04849   2.146  0.03235 *  
## Pct_brevet     -0.07363    0.03550  -2.074  0.03857 *  
## NivVieMed      -0.18441    0.11063  -1.667  0.09617 .  
## lag.Pct0_14    -0.77591    0.10295  -7.537 2.32e-13 ***
## lag.Pct_65     -0.06454    0.09115  -0.708  0.47924    
## lag.Pct_Img     0.64654    0.08593   7.524 2.53e-13 ***
## lag.Pct_brevet -0.30128    0.06157  -4.893 1.34e-06 ***
## lag.NivVieMed  -0.01805    0.17499  -0.103  0.91790    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.77 on 495 degrees of freedom
## Multiple R-squared:  0.4713, Adjusted R-squared:  0.4606 
## F-statistic: 44.13 on 10 and 495 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Effets directs, indirects et totaux</strong></p>
<p>Les effets des variables indépendantes sont donc décomposés en trois composantes :</p>
<ul>
<li>les <strong>effets directs</strong>, soit ceux des caractéristiques des entités spatiales. Ils correspondent aux coefficients <span class="math inline">\(\beta\)</span> des variables dépendantes (<span class="math inline">\(X\)</span>)</li>
<li>les <strong>effets indirects</strong>, soit ceux des caractéristiques des entités spatiales voisines ou proches définies selon la matrice de pondération spatiale. Ils correspondent aussi aux coefficients <span class="math inline">\(\theta\)</span> des variables dépendantes spatialement décalées (<span class="math inline">\(WX\)</span>)</li>
<li>les <strong>effets totaux</strong> soit la somme deux précédents.</li>
</ul>
<p>Le code suivant permet de les obtenir.</p>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb438-1"><a href="sect061.html#cb438-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Effets directs, indirects et totaux (uniquement les coefficients)</span></span>
<span id="cb438-2"><a href="sect061.html#cb438-2" aria-hidden="true" tabindex="-1"></a><span class="fu">impacts</span>(Modele.SLX)</span></code></pre></div>
<pre><code>## Impact measures (SlX, glht):
##                 Direct    Indirect      Total
## Pct0_14    -0.20403803 -0.77590830 -0.9799463
## Pct_65     -0.03770918 -0.06453809 -0.1022473
## Pct_Img     0.10406359  0.64653923  0.7506028
## Pct_brevet -0.07363272 -0.30128171 -0.3749144
## NivVieMed  -0.18440960 -0.01804718 -0.2024568</code></pre>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="sect061.html#cb440-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Effets directs, indirects et totaux (coefficients, valeurs de z et de p)</span></span>
<span id="cb440-2"><a href="sect061.html#cb440-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">impacts</span>(Modele.SLX))</span></code></pre></div>
<pre><code>## Impact measures (SlX, glht, n-k):
##                 Direct    Indirect      Total
## Pct0_14    -0.20403803 -0.77590830 -0.9799463
## Pct_65     -0.03770918 -0.06453809 -0.1022473
## Pct_Img     0.10406359  0.64653923  0.7506028
## Pct_brevet -0.07363272 -0.30128171 -0.3749144
## NivVieMed  -0.18440960 -0.01804718 -0.2024568
## ========================================================
## Standard errors:
##                Direct   Indirect      Total
## Pct0_14    0.06268202 0.10295210 0.10045332
## Pct_65     0.05361420 0.09114695 0.08556272
## Pct_Img    0.04849085 0.08593145 0.08060028
## Pct_brevet 0.03549819 0.06157121 0.05975821
## NivVieMed  0.11063207 0.17499339 0.14911021
## ========================================================
## Z-values:
##                Direct   Indirect     Total
## Pct0_14    -3.2551283 -7.5365951 -9.755241
## Pct_65     -0.7033432 -0.7080664 -1.194998
## Pct_Img     2.1460460  7.5238953  9.312658
## Pct_brevet -2.0742665 -4.8932234 -6.273857
## NivVieMed  -1.6668729 -0.1031306 -1.357766
## 
## p-values:
##            Direct    Indirect   Total     
## Pct0_14    0.0011334 4.8184e-14 &lt; 2.22e-16
## Pct_65     0.4818419 0.47890    0.23209   
## Pct_Img    0.0318693 5.3069e-14 &lt; 2.22e-16
## Pct_brevet 0.0380546 9.9198e-07 3.5221e-10
## NivVieMed  0.0955397 0.91786    0.17454</code></pre>
<p><strong>Dépendance du modèle spatiale SLX?</strong></p>
<p>Ce modèle a-t-il corrigé le problème de dépendance spatiale du modèle de régression linéaire classique? Avec une valeur du <em>I</em> de Moran de 0,605 (<em>p</em> &lt; 0,001), les résidus sont toujours fortement autocorrélés spatialement.</p>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb442-1"><a href="sect061.html#cb442-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.morantest</span>(Modele.SLX, W.Rook, <span class="at">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Global Moran I for regression residuals
## 
## data:  
## model: lm(formula = formula(paste(&quot;y ~ &quot;, paste(colnames(x)[-1],
## collapse = &quot;+&quot;))), data = as.data.frame(x), weights = weights)
## weights: W.Rook
## 
## Moran I statistic standard deviate = 21.951, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided
## sample estimates:
## Observed Moran I      Expectation         Variance 
##     0.6046602748    -0.0072844321     0.0007771643</code></pre>
</div>
<div id="sect06122" class="section level4 hasAnchor" number="6.1.2.2">
<h4><span class="header-section-number">6.1.2.2</span> Modèle SAR : autocorrélation spatiale sur la variable dépendante<a href="sect061.html#sect06122" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Dans le modèle SAR, l’autocorrélation spatiale est intégrée au niveau de variable indépendante (<span class="math inline">\(Wy\)</span>), qui est ainsi spatialement décalée. L’idée générale est que la valeur de la variable dépendante pour une observation (<span class="math inline">\(y_i\)</span>) peut être influencée par les valeurs de <span class="math inline">\(y\)</span> des observations voisines et proches. L’exemple le plus classique est le prix de vente des maisons : il est influencé à la fois par les caractéristiques intrinsèques de la maison (<span class="math inline">\(X\)</span>, par exemple, la superficie habitable, le nombre de chambres à coucher, de salles de bains, etc.) et par le prix de vente des maison voisines (<span class="math inline">\(Wy\)</span>). Dubé et Legros <span class="citation">(<a href="#ref-dube2014econometrie" role="doc-biblioref">2014</a>)</span> qualifie ce phénomène « <strong>d’effets d’entraînement ou d’effets de débordement</strong> (<em>spillover effects</em>) » <span class="citation">(<a href="#ref-dube2014econometrie" role="doc-biblioref">2014, 123</a>)</span>. L’équation du modèle SAR s’écrit alors :</p>
<p><span class="math display" id="eq:SLM">\[\begin{equation}
y = Wy\rho + X\beta + \epsilon
\tag{6.4}
\end{equation}\]</span>
</p>
<p>avec :</p>
<ul>
<li><span class="math inline">\(y\)</span>, la variable dépendante</li>
<li><span class="math inline">\(W\)</span>, la matrice de pondération spatiale</li>
<li><span class="math inline">\(Wy\)</span>, la variable indépendante spatialement décalée</li>
<li><span class="math inline">\(\rho\)</span> (prononcez <em>rho</em>), le coefficient de la variable indépendante spatialement décalée. Il varie de -1 à 1.</li>
<li><span class="math inline">\(X\)</span>, les variables indépendantes</li>
<li><span class="math inline">\(\beta\)</span>, les coefficients des variables dépendantes</li>
<li><span class="math inline">\(\epsilon\)</span>, les résidus.</li>
</ul>
<p><strong>Construction du modèle SAR dans R</strong></p>
<p>Le modèle SAR est construit avec la fonction <code>lagsarlm</code> du <em>package</em> <code>spatialreg</code>.</p>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="sect061.html#cb444-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Construction du modèle</span></span>
<span id="cb444-2"><a href="sect061.html#cb444-2" aria-hidden="true" tabindex="-1"></a>Modele.SAR <span class="ot">&lt;-</span> <span class="fu">lagsarlm</span>(NO2 <span class="sc">~</span> Pct0_14<span class="sc">+</span>Pct_65<span class="sc">+</span>Pct_Img<span class="sc">+</span>Pct_brevet<span class="sc">+</span>NivVieMed,</span>
<span id="cb444-3"><a href="sect061.html#cb444-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">listw=</span>W.Rook,    <span class="co"># matrice de pondération spatiale</span></span>
<span id="cb444-4"><a href="sect061.html#cb444-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">data =</span> LyonIris, <span class="co"># dataframe</span></span>
<span id="cb444-5"><a href="sect061.html#cb444-5" aria-hidden="true" tabindex="-1"></a>                              <span class="at">type =</span> <span class="st">&#39;lag&#39;</span>)    <span class="co"># Modèle lag par défaut</span></span>
<span id="cb444-6"><a href="sect061.html#cb444-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Résultats du modèle</span></span>
<span id="cb444-7"><a href="sect061.html#cb444-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Modele.SAR, <span class="at">Nagelkerke=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Call:lagsarlm(formula = NO2 ~ Pct0_14 + Pct_65 + Pct_Img + Pct_brevet + 
##     NivVieMed, data = LyonIris, listw = W.Rook, type = &quot;lag&quot;)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -12.86859  -1.88111  -0.49760   0.94464  18.21351 
## 
## Type: lag 
## Coefficients: (asymptotic standard errors) 
##              Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept)  7.838906   1.646232  4.7617 1.919e-06
## Pct0_14     -0.098708   0.030554 -3.2306  0.001235
## Pct_65      -0.034543   0.026957 -1.2814  0.200044
## Pct_Img      0.030241   0.024491  1.2348  0.216917
## Pct_brevet  -0.019234   0.017855 -1.0772  0.281384
## NivVieMed   -0.098413   0.048985 -2.0090  0.044534
## 
## Rho: 0.87939, LR test value: 620.31, p-value: &lt; 2.22e-16
## Asymptotic standard error: 0.01942
##     z-value: 45.283, p-value: &lt; 2.22e-16
## Wald statistic: 2050.5, p-value: &lt; 2.22e-16
## 
## Log likelihood: -1366.157 for lag model
## ML residual variance (sigma squared): 10.181, (sigma: 3.1908)
## Nagelkerke pseudo-R-squared: 0.78962 
## Number of observations: 506 
## Number of parameters estimated: 8 
## AIC: 2748.3, (AIC for lm: 3366.6)
## LM test for residual autocorrelation
## test value: 0.6198, p-value: 0.43112</code></pre>
<p>Dans les résultats ci-dessous, la valeur de <em>rho</em> est de 0,88 (LR = 620, <em>p</em> &lt; 0,001), traduisant une très fort effet d’entraînement. Autrement dit, lorsqu’en moyenne la concentration de dioxyde d’azote augmente dans les IRIS voisines (<span class="math inline">\(Wy\)</span>), elle augmente aussi fortement chaque IRIS (<span class="math inline">\(y\)</span>).</p>
<p><strong>Effets directs, indirects et totaux</strong></p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="sect061.html#cb446-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Effets directs, indirects et totaux (uniquement les coefficients)</span></span>
<span id="cb446-2"><a href="sect061.html#cb446-2" aria-hidden="true" tabindex="-1"></a><span class="fu">impacts</span>(Modele.SAR, <span class="at">listw =</span> W.Rook, <span class="at">R =</span> <span class="dv">999</span>)</span></code></pre></div>
<pre><code>## Impact measures (lag, exact):
##                 Direct   Indirect      Total
## Pct0_14    -0.13878038 -0.6796248 -0.8184052
## Pct_65     -0.04856624 -0.2378349 -0.2864012
## Pct_Img     0.04251743  0.2082131  0.2507306
## Pct_brevet -0.02704205 -0.1324283 -0.1594703
## NivVieMed  -0.13836534 -0.6775923 -0.8159576</code></pre>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="sect061.html#cb448-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Effets directs, indirects et totaux (coefficients, valeurs de z et de p)</span></span>
<span id="cb448-2"><a href="sect061.html#cb448-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">impacts</span>(Modele.SAR, <span class="at">listw =</span> W.Rook, <span class="at">R =</span> <span class="dv">999</span>), <span class="at">zstats =</span> <span class="cn">TRUE</span>, <span class="at">short =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Impact measures (lag, exact):
##                 Direct   Indirect      Total
## Pct0_14    -0.13878038 -0.6796248 -0.8184052
## Pct_65     -0.04856624 -0.2378349 -0.2864012
## Pct_Img     0.04251743  0.2082131  0.2507306
## Pct_brevet -0.02704205 -0.1324283 -0.1594703
## NivVieMed  -0.13836534 -0.6775923 -0.8159576
## ========================================================
## Simulation results ( variance matrix):
## ========================================================
## Simulated standard errors
##                Direct  Indirect     Total
## Pct0_14    0.04106249 0.2369711 0.2734005
## Pct_65     0.03690214 0.1888120 0.2246685
## Pct_Img    0.03399363 0.1775616 0.2105140
## Pct_brevet 0.02448167 0.1268029 0.1506836
## NivVieMed  0.06940295 0.3573234 0.4234237
## 
## Simulated z-values:
##               Direct  Indirect     Total
## Pct0_14    -3.369976 -2.899864 -3.019612
## Pct_65     -1.298650 -1.251854 -1.265367
## Pct_Img     1.237738  1.184090  1.198609
## Pct_brevet -1.132257 -1.084836 -1.096867
## NivVieMed  -1.988261 -1.906942 -1.935145
## 
## Simulated p-values:
##            Direct     Indirect  Total   
## Pct0_14    0.00075175 0.0037332 0.002531
## Pct_65     0.19406409 0.2106230 0.205740
## Pct_Img    0.21581308 0.2363775 0.230680
## Pct_brevet 0.25752652 0.2779945 0.272700
## NivVieMed  0.04678287 0.0565281 0.052973</code></pre>
<p><strong>Dépendance du modèle spatiale SAR?</strong></p>
<p>Ce modèle a-t-il corrigé le problème de dépendance spatiale du modèle de régression linéaire classique? Avec une valeur du <em>I</em> de Moran de -0,014 (<em>p</em> = 0,654), les résidus ne sont plus spatialement autocorrélés.</p>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb450-1"><a href="sect061.html#cb450-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Autocorrélation spatiale des résidus</span></span>
<span id="cb450-2"><a href="sect061.html#cb450-2" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.mc</span>(<span class="fu">resid</span>(Modele.SAR), W.Rook, <span class="at">nsim=</span><span class="dv">999</span>)</span></code></pre></div>
<pre><code>## 
##  Monte-Carlo simulation of Moran I
## 
## data:  resid(Modele.SAR) 
## weights: W.Rook  
## number of simulations + 1: 1000 
## 
## statistic = -0.014281, observed rank = 355, p-value = 0.645
## alternative hypothesis: greater</code></pre>
</div>
<div id="sect06123" class="section level4 hasAnchor" number="6.1.2.3">
<h4><span class="header-section-number">6.1.2.3</span> Modèle SEM : autocorrélation spatiale sur le terme d’erreur<a href="sect061.html#sect06123" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Dans le modèle SEM (<em>spatial erreur model</em>), l’intégration de l’autocorrélation spatiale est réalisée sur le terme d’erreur, ce qui pourrait se justifier par l’omission d’une variable dépendante spatialement structurée <span class="citation">(<a href="#ref-dube2014econometrie" role="doc-biblioref">Dubé et Legros 2014, 126</a>)</span>. L’équation du modèle SEM s’écrit :</p>
<p><span class="math display" id="eq:SEM">\[\begin{equation}
y = X\beta + u \textrm{, } u = \lambda Wu + \epsilon
\tag{6.5}
\end{equation}\]</span>
</p>
<p>avec :</p>
<ul>
<li><span class="math inline">\(y\)</span>, la variable dépendante</li>
<li><span class="math inline">\(W\)</span>, la matrice de pondération spatiale</li>
<li><span class="math inline">\(\lambda\)</span> (prononcez <em>lambda</em>), le coefficient sur le terme d’erreur spatialement décalée. Il varie de -1 à 1.</li>
<li><span class="math inline">\(X\)</span>, les variables indépendantes</li>
<li><span class="math inline">\(\beta\)</span>, les coefficients des variables dépendantes</li>
<li><span class="math inline">\(\epsilon\)</span>, les résidus.</li>
</ul>
<p><strong>Construction du modèle SAR dans R</strong></p>
<p>Le modèle SEM est construit avec la fonction <code>lmSLX</code> du <em>package</em> <code>spatialreg</code>.</p>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb452-1"><a href="sect061.html#cb452-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Construction du modèle</span></span>
<span id="cb452-2"><a href="sect061.html#cb452-2" aria-hidden="true" tabindex="-1"></a>Modele.SEM <span class="ot">&lt;-</span> <span class="fu">errorsarlm</span>(NO2 <span class="sc">~</span> Pct0_14<span class="sc">+</span>Pct_65<span class="sc">+</span>Pct_Img<span class="sc">+</span>Pct_brevet<span class="sc">+</span>NivVieMed,</span>
<span id="cb452-3"><a href="sect061.html#cb452-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">listw=</span>W.Rook,    <span class="co"># matrice de pondération spatiale</span></span>
<span id="cb452-4"><a href="sect061.html#cb452-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> LyonIris) <span class="co"># dataframe</span></span>
<span id="cb452-5"><a href="sect061.html#cb452-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Résultats du modèle</span></span>
<span id="cb452-6"><a href="sect061.html#cb452-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Modele.SEM, <span class="at">Nagelkerke=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Call:errorsarlm(formula = NO2 ~ Pct0_14 + Pct_65 + Pct_Img + Pct_brevet + 
##     NivVieMed, data = LyonIris, listw = W.Rook)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -12.86150  -1.83161  -0.44106   0.91029  17.94924 
## 
## Type: error 
## Coefficients: (asymptotic standard errors) 
##              Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 30.544576   2.358173 12.9526  &lt; 2e-16
## Pct0_14     -0.035019   0.033393 -1.0487  0.29431
## Pct_65      -0.026039   0.028970 -0.8988  0.36874
## Pct_Img     -0.016770   0.026176 -0.6407  0.52175
## Pct_brevet   0.023708   0.019074  1.2430  0.21388
## NivVieMed   -0.146309   0.060273 -2.4274  0.01521
## 
## Lambda: 0.91138, LR test value: 613.15, p-value: &lt; 2.22e-16
## Asymptotic standard error: 0.01651
##     z-value: 55.201, p-value: &lt; 2.22e-16
## Wald statistic: 3047.2, p-value: &lt; 2.22e-16
## 
## Log likelihood: -1369.737 for error model
## ML residual variance (sigma squared): 9.9971, (sigma: 3.1618)
## Nagelkerke pseudo-R-squared: 0.78662 
## Number of observations: 506 
## Number of parameters estimated: 8 
## AIC: NA (not available for weighted model), (AIC for lm: 3366.6)</code></pre>
<p>Dans les résultats ci-dessous, la valeur de <em>lambda</em> est de 0,91 (LR = 613, <em>p</em> &lt; 0,001), traduisant une très forte autocorrélation spatiale sur le terme d’erreur.</p>
<p><strong>Dépendance du modèle spatiale SEM?</strong></p>
<p>Ce modèle a-t-il corrigé le problème de dépendance spatiale du modèle de régression linéaire classique? Avec une valeur du <em>I</em> de Moran de -0,013 (<em>p</em> = 0,614), les résidus ne sont plus spatialement autocorrélés.</p>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="sect061.html#cb454-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Autocorrélation spatiale des résidus</span></span>
<span id="cb454-2"><a href="sect061.html#cb454-2" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.mc</span>(<span class="fu">resid</span>(Modele.SEM), W.Rook, <span class="at">nsim=</span><span class="dv">999</span>)</span></code></pre></div>
<pre><code>## 
##  Monte-Carlo simulation of Moran I
## 
## data:  resid(Modele.SEM) 
## weights: W.Rook  
## number of simulations + 1: 1000 
## 
## statistic = -0.011827, observed rank = 386, p-value = 0.614
## alternative hypothesis: greater</code></pre>
</div>
<div id="sect06124" class="section level4 hasAnchor" number="6.1.2.4">
<h4><span class="header-section-number">6.1.2.4</span> Modèle SDM : autocorrélation spatiale sur la variable dépendante et les variables indépendantes<a href="sect061.html#sect06124" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Le modèle SDM (<em>Spatial Durbin Model</em> en anglais) est un modèle mixte qui intègre à la fois l’autocorrélation spatiale sur la variable dépendante (<span class="math inline">\(Wy\)</span>, <strong>effets d’entraînement ou de débordement</strong>) et sur les variables indépendantes (<span class="math inline">\(WX\)</span>, <strong>externalités</strong>). Il s’écrit alors :</p>
<p><span class="math display" id="eq:SDM">\[\begin{equation}
y = Wy\rho + X\beta + WX\theta + \epsilon
\tag{6.6}
\end{equation}\]</span>
</p>
<p>avec :</p>
<ul>
<li><span class="math inline">\(y\)</span>, la variable dépendante</li>
<li><span class="math inline">\(W\)</span>, la matrice de pondération spatiale</li>
<li><span class="math inline">\(Wy\)</span>, la variable indépendante spatialement décalée</li>
<li><span class="math inline">\(\rho\)</span>, le coefficient de la variable indépendante spatialement décalée</li>
<li><span class="math inline">\(X\)</span>, les variables indépendantes</li>
<li><span class="math inline">\(\beta\)</span>, les coefficients des variables dépendantes</li>
<li><span class="math inline">\(WX\)</span>, les variables dépendantes spatiales décalés</li>
<li><span class="math inline">\(\theta\)</span>, les coefficients des variables dépendantes spatiales décalées</li>
<li><span class="math inline">\(\epsilon\)</span>, les résidus.</li>
</ul>
<p><strong>Construction du modèle SDM dans R</strong></p>
<p>Le modèle SDM est construit avec la fonction <code>lagsarlm</code> du <em>package</em> <code>spatialreg</code>. Notez que le paramètre <code>type = "mixed"</code> qui spécifie l’utilisation d’un modèle mixte.</p>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="sect061.html#cb456-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Construction du modèle</span></span>
<span id="cb456-2"><a href="sect061.html#cb456-2" aria-hidden="true" tabindex="-1"></a>Modele.DurbinSpatial <span class="ot">&lt;-</span> <span class="fu">lagsarlm</span>(NO2 <span class="sc">~</span> Pct0_14<span class="sc">+</span>Pct_65<span class="sc">+</span>Pct_Img<span class="sc">+</span>Pct_brevet<span class="sc">+</span>NivVieMed,</span>
<span id="cb456-3"><a href="sect061.html#cb456-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">listw =</span> W.Rook,    <span class="co"># matrice de pondération spatiale</span></span>
<span id="cb456-4"><a href="sect061.html#cb456-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> LyonIris,   <span class="co"># dataframe</span></span>
<span id="cb456-5"><a href="sect061.html#cb456-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">type =</span> <span class="st">&quot;mixed&quot;</span>)</span>
<span id="cb456-6"><a href="sect061.html#cb456-6" aria-hidden="true" tabindex="-1"></a><span class="do">## 7.2. Résultats du modèle</span></span>
<span id="cb456-7"><a href="sect061.html#cb456-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Résultats du modèles</span></span>
<span id="cb456-8"><a href="sect061.html#cb456-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Modele.DurbinSpatial, <span class="at">Nagelkerke=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Call:lagsarlm(formula = NO2 ~ Pct0_14 + Pct_65 + Pct_Img + Pct_brevet + 
##     NivVieMed, data = LyonIris, listw = W.Rook, type = &quot;mixed&quot;)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -12.60922  -1.77753  -0.43909   0.99252  18.15526 
## 
## Type: mixed 
## Coefficients: (asymptotic standard errors) 
##                  Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)     8.1130457  2.5671301  3.1604 0.001576
## Pct0_14        -0.0574046  0.0344908 -1.6643 0.096043
## Pct_65         -0.0238715  0.0293647 -0.8129 0.416256
## Pct_Img         0.0048364  0.0266560  0.1814 0.856025
## Pct_brevet      0.0112746  0.0195259  0.5774 0.563656
## NivVieMed      -0.1463876  0.0605853 -2.4162 0.015682
## lag.Pct0_14    -0.1242574  0.0581170 -2.1381 0.032512
## lag.Pct_65      0.0255480  0.0499646  0.5113 0.609125
## lag.Pct_Img     0.1559952  0.0482138  3.2355 0.001214
## lag.Pct_brevet -0.0883930  0.0342496 -2.5809 0.009856
## lag.NivVieMed   0.1032469  0.0960201  1.0753 0.282257
## 
## Rho: 0.84127, LR test value: 492.38, p-value: &lt; 2.22e-16
## Asymptotic standard error: 0.023363
##     z-value: 36.009, p-value: &lt; 2.22e-16
## Wald statistic: 1296.7, p-value: &lt; 2.22e-16
## 
## Log likelihood: -1353.106 for mixed model
## ML residual variance (sigma squared): 9.9845, (sigma: 3.1598)
## Nagelkerke pseudo-R-squared: 0.8002 
## Number of observations: 506 
## Number of parameters estimated: 13 
## AIC: 2732.2, (AIC for lm: 3222.6)
## LM test for residual autocorrelation
## test value: 0.0748, p-value: 0.78447</code></pre>
<p><strong>Effets directs, indirects et totaux</strong></p>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="sect061.html#cb458-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effets directs, indirects et totaux (uniquement les coefficients)</span></span>
<span id="cb458-2"><a href="sect061.html#cb458-2" aria-hidden="true" tabindex="-1"></a><span class="fu">impacts</span>(Modele.DurbinSpatial, <span class="at">listw =</span> W.Rook, <span class="at">R =</span> <span class="dv">999</span>)</span></code></pre></div>
<pre><code>## Impact measures (mixed, exact):
##                 Direct    Indirect       Total
## Pct0_14    -0.12369039 -1.02079497 -1.14448536
## Pct_65     -0.02177191  0.03233406  0.01056215
## Pct_Img     0.06632543  0.94692639  1.01325182
## Pct_brevet -0.01903815 -0.46681402 -0.48585217
## NivVieMed  -0.15403413 -0.11775603 -0.27179016</code></pre>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="sect061.html#cb460-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effets directs, indirects et totaux (coefficients, valeurs de z et de p)</span></span>
<span id="cb460-2"><a href="sect061.html#cb460-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">impacts</span>(Modele.DurbinSpatial, <span class="at">listw =</span> W.Rook, <span class="at">R =</span> <span class="dv">999</span>), <span class="at">zstats =</span> <span class="cn">TRUE</span>, <span class="at">short =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Impact measures (mixed, exact):
##                 Direct    Indirect       Total
## Pct0_14    -0.12369039 -1.02079497 -1.14448536
## Pct_65     -0.02177191  0.03233406  0.01056215
## Pct_Img     0.06632543  0.94692639  1.01325182
## Pct_brevet -0.01903815 -0.46681402 -0.48585217
## NivVieMed  -0.15403413 -0.11775603 -0.27179016
## ========================================================
## Simulation results ( variance matrix):
## ========================================================
## Simulated standard errors
##                Direct  Indirect     Total
## Pct0_14    0.04387620 0.3238569 0.3511112
## Pct_65     0.03564555 0.2798638 0.3023572
## Pct_Img    0.03208904 0.2730492 0.2910092
## Pct_brevet 0.02419487 0.1929199 0.2082737
## NivVieMed  0.06923741 0.5025663 0.5366255
## 
## Simulated z-values:
##                Direct    Indirect       Total
## Pct0_14    -2.8402032 -3.20678815 -3.31279040
## Pct_65     -0.6312146  0.06884458 -0.01069228
## Pct_Img     2.0462274  3.47880743  3.48974241
## Pct_brevet -0.7646549 -2.38010280 -2.29347248
## NivVieMed  -2.2104748 -0.21362006 -0.48526546
## 
## Simulated p-values:
##            Direct    Indirect   Total     
## Pct0_14    0.0045085 0.00134226 0.00092370
## Pct_65     0.5279002 0.94511333 0.99146896
## Pct_Img    0.0407340 0.00050365 0.00048349
## Pct_brevet 0.4444770 0.01730781 0.02182082
## NivVieMed  0.0270722 0.83084335 0.62748806</code></pre>
<p><strong>Dépendance du modèle spatiale SDM?</strong></p>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb462-1"><a href="sect061.html#cb462-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.mc</span>(<span class="fu">resid</span>(Modele.DurbinSpatial), W.Rook, <span class="at">nsim=</span><span class="dv">999</span>)</span></code></pre></div>
<pre><code>## 
##  Monte-Carlo simulation of Moran I
## 
## data:  resid(Modele.DurbinSpatial) 
## weights: W.Rook  
## number of simulations + 1: 1000 
## 
## statistic = -0.0046127, observed rank = 470, p-value = 0.53
## alternative hypothesis: greater</code></pre>
</div>
<div id="sect06125" class="section level4 hasAnchor" number="6.1.2.5">
<h4><span class="header-section-number">6.1.2.5</span> Modèle SDEM : autocorrélation spatiale sur les variables indépendantes et sur le terme d’erreur<a href="sect061.html#sect06125" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Le modèle SDEM (<em>Spatial Durbin Error Model</em> en anglais) est un autre modèle mixte qui intègre à la fois l’autocorrélation spatiale sur les valeurs indépendantes (<span class="math inline">\(WX\)</span>, <strong>externalités</strong>) et sur le terme d’erreur (<span class="math inline">\(u = \lambda Wu + \epsilon\)</span>). Il s’écrit alors :</p>
<p><span class="math display" id="eq:SDEM">\[\begin{equation}
y = X\beta + WX\theta + u \textrm{, } u = \lambda Wu + \epsilon
\tag{6.7}
\end{equation}\]</span>
</p>
<p>avec :</p>
<ul>
<li><span class="math inline">\(y\)</span>, la variable dépendante</li>
<li><span class="math inline">\(W\)</span>, la matrice de pondération spatiale</li>
<li><span class="math inline">\(X\)</span>, les variables indépendantes</li>
<li><span class="math inline">\(\beta\)</span>, les coefficients des variables dépendantes</li>
<li><span class="math inline">\(WX\)</span>, les variables dépendantes spatiales décalés</li>
<li><span class="math inline">\(\theta\)</span>, les coefficients des variables dépendantes spatiales décalées</li>
<li><span class="math inline">\(\lambda\)</span> (prononcez <em>lambda</em>), le coefficient sur le terme d’erreur spatialement décalée</li>
<li><span class="math inline">\(X\)</span>, les variables indépendantes</li>
<li><span class="math inline">\(\beta\)</span>, les coefficients des variables dépendantes</li>
<li><span class="math inline">\(\epsilon\)</span>, les résidus.</li>
</ul>
<p><strong>Construction du modèle SDEM dans R</strong></p>
<p>Le modèle SDEM est construit avec la fonction <code>errorsarlm</code> du <em>package</em> <code>spatialreg</code>. Notez que le paramètre <code>etype = "mixed"</code> qui spécifie l’utilisation d’un modèle mixte.</p>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb464-1"><a href="sect061.html#cb464-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Construction du modèle</span></span>
<span id="cb464-2"><a href="sect061.html#cb464-2" aria-hidden="true" tabindex="-1"></a>Modele.DurbinErreur <span class="ot">&lt;-</span> <span class="fu">errorsarlm</span>(NO2 <span class="sc">~</span> Pct0_14<span class="sc">+</span>Pct_65<span class="sc">+</span>Pct_Img<span class="sc">+</span>Pct_brevet<span class="sc">+</span>NivVieMed,</span>
<span id="cb464-3"><a href="sect061.html#cb464-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">listw=</span>W.Rook,    <span class="co"># matrice de pondération spatiale</span></span>
<span id="cb464-4"><a href="sect061.html#cb464-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">data =</span> LyonIris, <span class="co"># dataframe</span></span>
<span id="cb464-5"><a href="sect061.html#cb464-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">etype =</span> <span class="st">&#39;emixed&#39;</span>)</span>
<span id="cb464-6"><a href="sect061.html#cb464-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb464-7"><a href="sect061.html#cb464-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Résultats du modèle</span></span>
<span id="cb464-8"><a href="sect061.html#cb464-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Modele.DurbinErreur, <span class="at">Nagelkerke=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Call:errorsarlm(formula = NO2 ~ Pct0_14 + Pct_65 + Pct_Img + Pct_brevet + 
##     NivVieMed, data = LyonIris, listw = W.Rook, etype = &quot;emixed&quot;)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -12.99324  -1.82407  -0.45644   1.06084  18.21108 
## 
## Type: error 
## Coefficients: (asymptotic standard errors) 
##                  Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept)    37.0610133  6.5010177  5.7008 1.192e-08
## Pct0_14        -0.0819977  0.0416988 -1.9664   0.04925
## Pct_65         -0.0263294  0.0347137 -0.7585   0.44817
## Pct_Img         0.0046560  0.0310281  0.1501   0.88072
## Pct_brevet      0.0097849  0.0238839  0.4097   0.68203
## NivVieMed      -0.1678555  0.0680048 -2.4683   0.01358
## lag.Pct0_14    -0.1767469  0.1023451 -1.7270   0.08417
## lag.Pct_65      0.0105325  0.0891835  0.1181   0.90599
## lag.Pct_Img     0.0927851  0.0797036  1.1641   0.24437
## lag.Pct_brevet -0.0380482  0.0566883 -0.6712   0.50210
## lag.NivVieMed  -0.1025307  0.1724055 -0.5947   0.55204
## 
## Lambda: 0.8976, LR test value: 464.09, p-value: &lt; 2.22e-16
## Asymptotic standard error: 0.018242
##     z-value: 49.204, p-value: &lt; 2.22e-16
## Wald statistic: 2421, p-value: &lt; 2.22e-16
## 
## Log likelihood: -1367.25 for error model
## ML residual variance (sigma squared): 10.046, (sigma: 3.1696)
## Nagelkerke pseudo-R-squared: 0.78871 
## Number of observations: 506 
## Number of parameters estimated: 13 
## AIC: NA (not available for weighted model), (AIC for lm: 3222.6)</code></pre>
<p><strong>Effets directs, indirects et totaux</strong></p>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="sect061.html#cb466-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Effets directs, indirects et totaux (uniquement les coefficients)</span></span>
<span id="cb466-2"><a href="sect061.html#cb466-2" aria-hidden="true" tabindex="-1"></a><span class="fu">impacts</span>(Modele.DurbinErreur, <span class="at">listw =</span> W.Rook, <span class="at">R =</span> <span class="dv">999</span>)</span></code></pre></div>
<pre><code>## Impact measures (SDEM, glht):
##                  Direct    Indirect       Total
## Pct0_14    -0.081997661 -0.17674688 -0.25874455
## Pct_65     -0.026329377  0.01053246 -0.01579692
## Pct_Img     0.004656049  0.09278514  0.09744119
## Pct_brevet  0.009784949 -0.03804816 -0.02826321
## NivVieMed  -0.167855503 -0.10253070 -0.27038620</code></pre>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="sect061.html#cb468-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Effets directs, indirects et totaux (coefficients, valeurs de z et de p)</span></span>
<span id="cb468-2"><a href="sect061.html#cb468-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">impacts</span>(Modele.DurbinErreur, <span class="at">listw =</span> W.Rook, <span class="at">R =</span> <span class="dv">999</span>), <span class="at">zstats =</span> <span class="cn">TRUE</span>, <span class="at">short =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Impact measures (SDEM, glht, n):
##                  Direct    Indirect       Total
## Pct0_14    -0.081997661 -0.17674688 -0.25874455
## Pct_65     -0.026329377  0.01053246 -0.01579692
## Pct_Img     0.004656049  0.09278514  0.09744119
## Pct_brevet  0.009784949 -0.03804816 -0.02826321
## NivVieMed  -0.167855503 -0.10253070 -0.27038620
## ========================================================
## Standard errors:
##                Direct   Indirect      Total
## Pct0_14    0.04169878 0.10234506 0.13146452
## Pct_65     0.03471367 0.08918350 0.11192948
## Pct_Img    0.03102807 0.07970364 0.09949722
## Pct_brevet 0.02388387 0.05668833 0.07344175
## NivVieMed  0.06800483 0.17240548 0.21172909
## ========================================================
## Z-values:
##                Direct   Indirect      Total
## Pct0_14    -1.9664284 -1.7269703 -1.9681701
## Pct_65     -0.7584729  0.1180987 -0.1411328
## Pct_Img     0.1500592  1.1641268  0.9793358
## Pct_brevet  0.4096885 -0.6711815 -0.3848384
## NivVieMed  -2.4682881 -0.5947067 -1.2770386
## 
## p-values:
##            Direct   Indirect Total   
## Pct0_14    0.049249 0.084173 0.049048
## Pct_65     0.448168 0.905989 0.887765
## Pct_Img    0.880718 0.244373 0.327414
## Pct_brevet 0.682034 0.502105 0.700357
## NivVieMed  0.013576 0.552040 0.201589</code></pre>
<p><strong>Dépendance du modèle spatiale SDEM?</strong></p>
<div class="sourceCode" id="cb470"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb470-1"><a href="sect061.html#cb470-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.mc</span>(<span class="fu">resid</span>(Modele.DurbinErreur), W.Rook, <span class="at">nsim=</span><span class="dv">999</span>)</span></code></pre></div>
<pre><code>## 
##  Monte-Carlo simulation of Moran I
## 
## data:  resid(Modele.DurbinErreur) 
## weights: W.Rook  
## number of simulations + 1: 1000 
## 
## statistic = -0.010362, observed rank = 381, p-value = 0.619
## alternative hypothesis: greater</code></pre>
</div>
</div>
<div id="sect0613" class="section level3 hasAnchor" number="6.1.3">
<h3><span class="header-section-number">6.1.3</span> Quel modèle choisir?<a href="sect061.html#sect0613" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="sect06131" class="section level4 hasAnchor" number="6.1.3.1">
<h4><span class="header-section-number">6.1.3.1</span> Tests du multiplicateur de Lagrange sur le modèle MCO<a href="sect061.html#sect06131" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>L’utilisation des tests du multiplicateur de Lagrange (simple et robuste) a été largement popularisée par Anselin <em>et al.</em> <span class="citation">(<a href="#ref-anselin1996simple" role="doc-biblioref">1996</a>)</span> pour vérifier si le recours à un modèle autorégressif est nécessaire, comparativement à un modèle de régression classique (MCO). Les tests sont calculés sur le modèle MCO avec le fonction <code>lm.LMtests</code> et une matrice pondération spatiale. Ces tests permettent aussi de choisir entre les modèles SAR et SEM. La démarche suivante peut être utilisée pour choisir un modèle :</p>
<ol style="list-style-type: decimal">
<li>Si toutes les valeurs des tests (simples et robustes) sont non significatives (<em>p</em> &gt; 0,05) alors le recours à un modèle autorégressif n’est pas nécessaire. Nous pouvons conserver le modèle de régression classique (MCO).</li>
<li>Si les valeurs de <code>LMlag</code> ou <code>RLMlag</code> sont non significatives (<em>p</em> &gt; 0,05) alors le recours au modèle SAR n’est pas nécessaire.</li>
<li>Si les valeurs de <code>LMerr</code> ou <code>RLMerr</code> sont non significatives (<em>p</em> &gt; 0,05) alors le recours au modèle SEM n’est pas nécessaire.</li>
<li>Si les valeurs de <code>RLMlag</code> et <code>RLMerr</code> sont significatives (<em>p</em> &lt; 0,001), nous choisissons le modèle ayant la plus forte statistique.</li>
</ol>
<p>Dans les résultats ci-dessous, nous ne retenons pas le modèle SEM car la valeur de 0,740 pour le <code>RLMerr</code> n’est pas significative (<em>p</em> = 0,3898). Par contre, les valeurs <code>LMlag</code> et de <code>RLMlag</code> (555 et 123) sont significatives, ce que justifie la sélection du modèle SAR.</p>
<div class="sourceCode" id="cb472"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb472-1"><a href="sect061.html#cb472-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm.LMtests</span>(<span class="at">model =</span> Modele.MCO,</span>
<span id="cb472-2"><a href="sect061.html#cb472-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">listw =</span> W.Rook,</span>
<span id="cb472-3"><a href="sect061.html#cb472-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">test =</span> <span class="fu">c</span>(<span class="st">&quot;LMlag&quot;</span>,<span class="st">&quot;LMerr&quot;</span>,<span class="st">&quot;RLMlag&quot;</span>,<span class="st">&quot;RLMerr&quot;</span>)))</span></code></pre></div>
<pre><code>##  Lagrange multiplier diagnostics for spatial dependence
## data:  
## model: lm(formula = NO2 ~ Pct0_14 + Pct_65 + Pct_Img + Pct_brevet +
## NivVieMed, data = LyonIris)
## weights: W.Rook
##  
##        statistic parameter p.value    
## LMlag  554.65778         1  &lt;2e-16 ***
## LMerr  432.83282         1  &lt;2e-16 ***
## RLMlag 122.56452         1  &lt;2e-16 ***
## RLMerr   0.73955         1  0.3898    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="sect06132" class="section level4 hasAnchor" number="6.1.3.2">
<h4><span class="header-section-number">6.1.3.2</span> Comparaison des modèles mixtes et non mixtes<a href="sect061.html#sect06132" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Nous avons vu qu’il existe deux modèles mixtes (SDM et SDEM). Il convient alors de vérifier si le recours d’un modèle mixte est justifié comparativement à un modèle non mixte. Dans le code ci-dessous, nous vérifions ci le modèle SDM est statistiquement différent du modèle SAR avec les fonctions <code>LR.Sarlm</code> et <code>anova</code>. Les résultats signalent un écart significatif des valeurs du log-vraisemblance (26,101, <em>p</em> &lt; 0,001). Par conséquent, ce modèle mixte a un apport significatif.</p>
<div class="sourceCode" id="cb474"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb474-1"><a href="sect061.html#cb474-1" aria-hidden="true" tabindex="-1"></a><span class="do">## SDM et SEM sont-ils significativement différents?</span></span>
<span id="cb474-2"><a href="sect061.html#cb474-2" aria-hidden="true" tabindex="-1"></a><span class="fu">LR.Sarlm</span>(Modele.DurbinSpatial, Modele.SAR)</span></code></pre></div>
<pre><code>## 
##  Likelihood ratio for spatial linear models
## 
## data:  
## Likelihood ratio = 26.101, df = 5, p-value = 8.528e-05
## sample estimates:
## Log likelihood of Modele.DurbinSpatial           Log likelihood of Modele.SAR 
##                              -1353.106                              -1366.157</code></pre>
<div class="sourceCode" id="cb476"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb476-1"><a href="sect061.html#cb476-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(Modele.DurbinSpatial, Modele.SAR)</span></code></pre></div>
<pre><code>##                      Model df    AIC  logLik Test L.Ratio    p-value
## Modele.DurbinSpatial     1 13 2732.2 -1353.1    1                   
## Modele.SAR               2  8 2748.3 -1366.2    2  26.101 8.5283e-05</code></pre>
<p>À l’inverse, la différence entre les valeurs du log-vraisemblance du modèle SDEM et SEM n’est pas significative (4,9728, <em>p</em> = 0,42), signalant que l’utilisation d’un modèle SDEM comparativement à un modèle SEM n’est pas nécessaire.</p>
<div class="sourceCode" id="cb478"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb478-1"><a href="sect061.html#cb478-1" aria-hidden="true" tabindex="-1"></a><span class="do">## SDEM et SEM sont-ils significativement différents?</span></span>
<span id="cb478-2"><a href="sect061.html#cb478-2" aria-hidden="true" tabindex="-1"></a><span class="fu">LR.Sarlm</span>(Modele.DurbinErreur, Modele.SEM)</span></code></pre></div>
<pre><code>## 
##  Likelihood ratio for spatial linear models
## 
## data:  
## Likelihood ratio = 4.9728, df = 5, p-value = 0.4192
## sample estimates:
## Log likelihood of Modele.DurbinErreur          Log likelihood of Modele.SEM 
##                             -1367.250                             -1369.737</code></pre>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="sect061.html#cb480-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(Modele.DurbinErreur, Modele.SEM)</span></code></pre></div>
<pre><code>##                     Model df    AIC  logLik Test L.Ratio p-value
## Modele.DurbinErreur     1 13 2760.5 -1367.2    1                
## Modele.SEM              2  8 2755.5 -1369.7    2  4.9728  0.4192</code></pre>
</div>
<div id="sect06133" class="section level4 hasAnchor" number="6.1.3.3">
<h4><span class="header-section-number">6.1.3.3</span> Mesures AIC et BIC et dépendance spatiale<a href="sect061.html#sect06133" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Les mesures AIC et BIC sont largement utilisées pour évaluer la qualité d’ajustement du modèle. Plus leurs valeurs sont faibles, meilleur est le modèle. Il est donc possible de comparer leurs valeurs pour les différents modèles (MCO, SLX, SAR, SEM, SDM et SDEM). Nous pouvons aussi comparer l’autocorrélation spatiale des résidus des modèles avec le <em>I</em> de Moran.</p>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="sect061.html#cb482-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Valeurs d&#39;AIC et de BIC</span></span>
<span id="cb482-2"><a href="sect061.html#cb482-2" aria-hidden="true" tabindex="-1"></a>AICs <span class="ot">&lt;-</span> <span class="fu">AIC</span>(Modele.MCO, Modele.SLX, Modele.SAR, Modele.SEM, </span>
<span id="cb482-3"><a href="sect061.html#cb482-3" aria-hidden="true" tabindex="-1"></a>            Modele.DurbinSpatial, Modele.DurbinErreur)</span>
<span id="cb482-4"><a href="sect061.html#cb482-4" aria-hidden="true" tabindex="-1"></a>BICs <span class="ot">&lt;-</span> <span class="fu">BIC</span>(Modele.MCO, Modele.SLX, Modele.SAR, Modele.SEM, </span>
<span id="cb482-5"><a href="sect061.html#cb482-5" aria-hidden="true" tabindex="-1"></a>            Modele.DurbinSpatial, Modele.DurbinErreur)</span>
<span id="cb482-6"><a href="sect061.html#cb482-6" aria-hidden="true" tabindex="-1"></a><span class="do">## AUtocorrélation spatiale des résidus</span></span>
<span id="cb482-7"><a href="sect061.html#cb482-7" aria-hidden="true" tabindex="-1"></a>IMoran.MCO <span class="ot">&lt;-</span> <span class="fu">moran.mc</span>(<span class="fu">resid</span>(Modele.MCO), W.Rook, <span class="at">nsim=</span><span class="dv">999</span>)</span>
<span id="cb482-8"><a href="sect061.html#cb482-8" aria-hidden="true" tabindex="-1"></a>IMoran.SLX <span class="ot">&lt;-</span> <span class="fu">moran.mc</span>(<span class="fu">resid</span>(Modele.SLX), W.Rook, <span class="at">nsim=</span><span class="dv">999</span>)</span>
<span id="cb482-9"><a href="sect061.html#cb482-9" aria-hidden="true" tabindex="-1"></a>IMoran.SLM <span class="ot">&lt;-</span> <span class="fu">moran.mc</span>(<span class="fu">resid</span>(Modele.SAR), W.Rook, <span class="at">nsim=</span><span class="dv">999</span>)</span>
<span id="cb482-10"><a href="sect061.html#cb482-10" aria-hidden="true" tabindex="-1"></a>IMoran.SEM <span class="ot">&lt;-</span> <span class="fu">moran.mc</span>(<span class="fu">resid</span>(Modele.SEM), W.Rook, <span class="at">nsim=</span><span class="dv">999</span>)</span>
<span id="cb482-11"><a href="sect061.html#cb482-11" aria-hidden="true" tabindex="-1"></a>IMoran.DurbinS <span class="ot">&lt;-</span> <span class="fu">moran.mc</span>(<span class="fu">resid</span>(Modele.DurbinSpatial), W.Rook, <span class="at">nsim=</span><span class="dv">999</span>)</span>
<span id="cb482-12"><a href="sect061.html#cb482-12" aria-hidden="true" tabindex="-1"></a>IMoran.DurbinE <span class="ot">&lt;-</span> <span class="fu">moran.mc</span>(<span class="fu">resid</span>(Modele.DurbinErreur), W.Rook, <span class="at">nsim=</span><span class="dv">999</span>)</span>
<span id="cb482-13"><a href="sect061.html#cb482-13" aria-hidden="true" tabindex="-1"></a>MoranI.s <span class="ot">&lt;-</span> <span class="fu">c</span>(IMoran.MCO<span class="sc">$</span>statistic, IMoran.SLX<span class="sc">$</span>statistic,</span>
<span id="cb482-14"><a href="sect061.html#cb482-14" aria-hidden="true" tabindex="-1"></a>             IMoran.SLM<span class="sc">$</span>statistic, IMoran.SEM<span class="sc">$</span>statistic,</span>
<span id="cb482-15"><a href="sect061.html#cb482-15" aria-hidden="true" tabindex="-1"></a>             IMoran.DurbinS<span class="sc">$</span>statistic, IMoran.DurbinE<span class="sc">$</span>statistic)</span>
<span id="cb482-16"><a href="sect061.html#cb482-16" aria-hidden="true" tabindex="-1"></a>MoranI.p <span class="ot">&lt;-</span> <span class="fu">c</span>(IMoran.MCO<span class="sc">$</span>p.value, IMoran.SLX<span class="sc">$</span>p.value,</span>
<span id="cb482-17"><a href="sect061.html#cb482-17" aria-hidden="true" tabindex="-1"></a>             IMoran.SLM<span class="sc">$</span>p.value, IMoran.SEM<span class="sc">$</span>p.value,</span>
<span id="cb482-18"><a href="sect061.html#cb482-18" aria-hidden="true" tabindex="-1"></a>             IMoran.DurbinS<span class="sc">$</span>p.value, IMoran.DurbinE<span class="sc">$</span>p.value)</span>
<span id="cb482-19"><a href="sect061.html#cb482-19" aria-hidden="true" tabindex="-1"></a><span class="do">## Tableau</span></span>
<span id="cb482-20"><a href="sect061.html#cb482-20" aria-hidden="true" tabindex="-1"></a>Comparaison <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Modele =</span> <span class="fu">c</span>(<span class="st">&quot;MCO&quot;</span>, <span class="st">&quot;SLX&quot;</span>, <span class="st">&quot;SLM&quot;</span>, <span class="st">&quot;SEM&quot;</span>, <span class="st">&quot;Durbin S&quot;</span>, <span class="st">&quot;Durbin E&quot;</span>),</span>
<span id="cb482-21"><a href="sect061.html#cb482-21" aria-hidden="true" tabindex="-1"></a>                          <span class="at">AIC =</span> AICs<span class="sc">$</span>AIC,</span>
<span id="cb482-22"><a href="sect061.html#cb482-22" aria-hidden="true" tabindex="-1"></a>                          <span class="at">BIC =</span> BICs<span class="sc">$</span>BIC,</span>
<span id="cb482-23"><a href="sect061.html#cb482-23" aria-hidden="true" tabindex="-1"></a>                          <span class="at">dl =</span> AICs<span class="sc">$</span>df,</span>
<span id="cb482-24"><a href="sect061.html#cb482-24" aria-hidden="true" tabindex="-1"></a>                          <span class="at">MoranI =</span> MoranI.s,</span>
<span id="cb482-25"><a href="sect061.html#cb482-25" aria-hidden="true" tabindex="-1"></a>                          <span class="at">MoranIp =</span> MoranI.p)</span>
<span id="cb482-26"><a href="sect061.html#cb482-26" aria-hidden="true" tabindex="-1"></a>Comparaison</span></code></pre></div>
<pre><code>##     Modele      AIC      BIC dl       MoranI MoranIp
## 1      MCO 3366.626 3396.212  7  0.587312061   0.001
## 2      SLX 3222.594 3273.313 12  0.604660275   0.001
## 3      SLM 2748.314 2782.126  8 -0.014281059   0.640
## 4      SEM 2755.474 2789.286  8 -0.011826630   0.618
## 5 Durbin S 2732.212 2787.157 13 -0.004612686   0.514
## 6 Durbin E 2760.501 2815.446 13 -0.010361614   0.621</code></pre>
<p>Quelques lignes de code suffissent pour créer deux graphiques permettant de comparer visuellement les résultats des différents modèles (figure <a href="sect061.html#fig:GraphComparaison">6.3</a>). Les résultats démontrent que :</p>
<ul>
<li>les modèles MCO et SLX ont un problème de dépendance spatiale puisque leur résidus sont significativement autocorrélés.
spatialement. Il ne devraient donc pas être retenus.</li>
<li>Le modèle mixte SDM et le modèle non mixte SEM ont les valeurs sont les plus performants avec les valeurs d’AIC les plus faibles.</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:GraphComparaison"></span>
<img src="GMQ405_files/figure-html/GraphComparaison-1.png" alt="Compararison des différents modèles" width="100%" />
<p class="caption">
Figure 6.3: Compararison des différents modèles
</p>
</div>
</div>
</div>
</div>
<h3>Références</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-anselin1996simple" class="csl-entry">
Anselin, Luc, Anil K Bera, Raymond Florax et Mann J Yoon. 1996. <span>« Simple diagnostic tests for spatial dependence. »</span> <em>Regional science and urban economics</em> 26 (1): 77‑104.
</div>
<div id="ref-anselin2014modern" class="csl-entry">
Anselin, Luc et Sergio J Rey. 2014. <em>Modern spatial econometrics in practice: A guide to GeoDa, GeoDaSpace and PySAL</em>. GeoDa Press LLC.
</div>
<div id="ref-RBoldAir" class="csl-entry">
Apparicio, Philippe et Jérémy Gelb. 2022. <em>Méthodes quantitatives en sciences sociales : un grand bol d’R</em>. FabriqueREL, Licence CC BY-SA. <a href="https://laeq.github.io/LivreMethoQuantBolR/">https://laeq.github.io/LivreMethoQuantBolR/</a>.
</div>
<div id="ref-bivand2021review" class="csl-entry">
Bivand, Roger, Giovanni Millo et Gianfranco Piras. 2021. <span>« A review of software for spatial econometrics in R. »</span> <em>Mathematics</em> 9 (11): 1276.
</div>
<div id="ref-bivand2008applied" class="csl-entry">
Bivand, Roger, Edzer J Pebesma, Virgilio Gómez-Rubio et Edzer Jan Pebesma. 2008. <em>Applied spatial data analysis with R</em>. Vol. 747248717. Springer.
</div>
<div id="ref-dube2014econometrie" class="csl-entry">
Dubé, Jean et Diègo Legros. 2014. <em>Econom<span>é</span>trie spatiale appliqu<span>é</span>e des microdonn<span>é</span>es</em>. ISTE Group.
</div>
<div id="ref-lesage2008introduction" class="csl-entry">
LeSage, James P et R. Kelly Pace. 2008. <em>An introduction to spatial econometrics</em>. 123. CRC Press.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap06.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sect062.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["GMQ405.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
