<!DOCTYPE html>
<html lang="fr" xml:lang="fr">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8.1 Méthodes de classification non supervisée avec contrainte spatiale | Notes de cours GMQ405 : Modélisation et analyse spatiale</title>
  <meta name="description" content="Mettre le description du cours." />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="8.1 Méthodes de classification non supervisée avec contrainte spatiale | Notes de cours GMQ405 : Modélisation et analyse spatiale" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/introduction/ImageCouverture.png" />
  <meta property="og:description" content="Mettre le description du cours." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8.1 Méthodes de classification non supervisée avec contrainte spatiale | Notes de cours GMQ405 : Modélisation et analyse spatiale" />
  
  <meta name="twitter:description" content="Mettre le description du cours." />
  <meta name="twitter:image" content="/images/introduction/ImageCouverture.png" />

<meta name="author" content="Philippe Apparicio, département de géomatique appliquée, Université de Sherbrooke" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap08.html"/>
<link rel="next" href="sect082.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.1.2/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.1.2/leaflet-providers-plugin.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/quizlib.min.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">GMQ405 : modélisation et analyse spatiale</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenue</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html"><i class="fa fa-check"></i>Préface</a>
<ul>
<li class="chapter" data-level="" data-path="sect001.html"><a href="sect001.html"><i class="fa fa-check"></i>Un manuel sous la forme d’une ressource éducative libre</a></li>
<li class="chapter" data-level="" data-path="sect002.html"><a href="sect002.html"><i class="fa fa-check"></i>Comment lire ce manuel?</a></li>
<li class="chapter" data-level="" data-path="sect003.html"><a href="sect003.html"><i class="fa fa-check"></i>Comment utiliser les données du livre pour reproduire les exemples?</a></li>
<li class="chapter" data-level="" data-path="sect004.html"><a href="sect004.html"><i class="fa fa-check"></i>Structure du livre</a></li>
<li class="chapter" data-level="" data-path="sect005.html"><a href="sect005.html"><i class="fa fa-check"></i>Pourquoi faut-il programmer en géomatique appliquée et utiliser R?</a></li>
<li class="chapter" data-level="" data-path="sect006.html"><a href="sect006.html"><i class="fa fa-check"></i>Remerciements</a></li>
</ul></li>
<li class="part"><span><b>I Découverte de R</b></span></li>
<li class="chapter" data-level="1" data-path="chap01.html"><a href="chap01.html"><i class="fa fa-check"></i><b>1</b> Manipulation des données spatiales dans R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="sect011.html"><a href="sect011.html"><i class="fa fa-check"></i><b>1.1</b> Importation de données géographiques</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="sect011.html"><a href="sect011.html#sect0111"><i class="fa fa-check"></i><b>1.1.1</b> Importation de données vectorielles</a></li>
<li class="chapter" data-level="1.1.2" data-path="sect011.html"><a href="sect011.html#sect0112"><i class="fa fa-check"></i><b>1.1.2</b> Importation de données <em>raster</em></a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="sect012.html"><a href="sect012.html"><i class="fa fa-check"></i><b>1.2</b> Manipulation de données vectorielles</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="sect012.html"><a href="sect012.html#sect0121"><i class="fa fa-check"></i><b>1.2.1</b> Fonctions relatives à la projection cartographique</a></li>
<li class="chapter" data-level="1.2.2" data-path="sect012.html"><a href="sect012.html#sect0122"><i class="fa fa-check"></i><b>1.2.2</b> Fonctions d’opérations géométriques sur une couche</a></li>
<li class="chapter" data-level="1.2.3" data-path="sect012.html"><a href="sect012.html#sect01213"><i class="fa fa-check"></i><b>1.2.3</b> Fonctions d’opérations géométriques entre deux couches</a></li>
<li class="chapter" data-level="1.2.4" data-path="sect012.html"><a href="sect012.html#sect0124"><i class="fa fa-check"></i><b>1.2.4</b> Fonctions de mesures géométriques et de récupération des coordonnées géographiques</a></li>
<li class="chapter" data-level="1.2.5" data-path="sect012.html"><a href="sect012.html#sect0125"><i class="fa fa-check"></i><b>1.2.5</b> Jointures spatiales</a></li>
<li class="chapter" data-level="1.2.6" data-path="sect012.html"><a href="sect012.html#sect0126"><i class="fa fa-check"></i><b>1.2.6</b> Requêtes spatiales</a></li>
<li class="chapter" data-level="1.2.7" data-path="sect012.html"><a href="sect012.html#sect0127"><i class="fa fa-check"></i><b>1.2.7</b> Manipulation des données attributaires</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="sect013.html"><a href="sect013.html"><i class="fa fa-check"></i><b>1.3</b> Manipulation de données matricielles (<em>raster</em>)</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="sect013.html"><a href="sect013.html#sect0131"><i class="fa fa-check"></i><b>1.3.1</b> Mosaïquage et découpage d’images</a></li>
<li class="chapter" data-level="1.3.2" data-path="sect013.html"><a href="sect013.html#sect0132"><i class="fa fa-check"></i><b>1.3.2</b> Requêtes attributaires sur des images</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="sect014.html"><a href="sect014.html"><i class="fa fa-check"></i><b>1.4</b> Exportation de données spatiales de R vers des formats géographiques</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="sect014.html"><a href="sect014.html#sect0141"><i class="fa fa-check"></i><b>1.4.1</b> Exportation de données vectorielles <code>sf</code></a></li>
<li class="chapter" data-level="1.4.2" data-path="sect014.html"><a href="sect014.html#sect0142"><i class="fa fa-check"></i><b>1.4.2</b> Exportation de données <em>raster</em></a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="sect015.html"><a href="sect015.html"><i class="fa fa-check"></i><b>1.5</b> Cartographie avec R</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="sect015.html"><a href="sect015.html#sect0151"><i class="fa fa-check"></i><b>1.5.1</b> Manipulation des couches géométriques</a></li>
<li class="chapter" data-level="1.5.2" data-path="sect015.html"><a href="sect015.html#sect0152"><i class="fa fa-check"></i><b>1.5.2</b> Cartes interactives</a></li>
<li class="chapter" data-level="1.5.3" data-path="sect015.html"><a href="sect015.html#sect0153"><i class="fa fa-check"></i><b>1.5.3</b> Mise en page d’une carte</a></li>
<li class="chapter" data-level="1.5.4" data-path="sect015.html"><a href="sect015.html#sect0154"><i class="fa fa-check"></i><b>1.5.4</b> Exportation d’une carte</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="sect016.html"><a href="sect016.html"><i class="fa fa-check"></i><b>1.6</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="1.7" data-path="sect017.html"><a href="sect017.html"><i class="fa fa-check"></i><b>1.7</b> Exercices de révision</a></li>
</ul></li>
<li class="part"><span><b>II Autocorrélation spatiale</b></span></li>
<li class="chapter" data-level="2" data-path="chap02.html"><a href="chap02.html"><i class="fa fa-check"></i><b>2</b> Autocorrélation spatiale</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sect021.html"><a href="sect021.html"><i class="fa fa-check"></i><b>2.1</b> Notion d’autocorrélation spatiale</a></li>
<li class="chapter" data-level="2.2" data-path="sect022.html"><a href="sect022.html"><i class="fa fa-check"></i><b>2.2</b> Matrices de pondération spatiale</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="sect022.html"><a href="sect022.html#sect0221"><i class="fa fa-check"></i><b>2.2.1</b> Matrices de contiguïté</a></li>
<li class="chapter" data-level="2.2.2" data-path="sect022.html"><a href="sect022.html#sect0222"><i class="fa fa-check"></i><b>2.2.2</b> Matrices de proximité spatiale</a></li>
<li class="chapter" data-level="2.2.3" data-path="sect022.html"><a href="sect022.html#sect0223"><i class="fa fa-check"></i><b>2.2.3</b> Standardisation des matrices de pondération spatiale en ligne</a></li>
<li class="chapter" data-level="2.2.4" data-path="sect022.html"><a href="sect022.html#sect0224"><i class="fa fa-check"></i><b>2.2.4</b> Construction de matrices de pondération spatiale dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="sect023.html"><a href="sect023.html"><i class="fa fa-check"></i><b>2.3</b> Autocorrélation spatiale globale</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="sect023.html"><a href="sect023.html#sect0231"><i class="fa fa-check"></i><b>2.3.1</b> Statistique du <em>I</em> de Moran</a></li>
<li class="chapter" data-level="2.3.2" data-path="sect023.html"><a href="sect023.html#sect0232"><i class="fa fa-check"></i><b>2.3.2</b> Statistiques de comptage de jointure (<em>Join Count Statistics</em>)</a></li>
<li class="chapter" data-level="2.3.3" data-path="sect023.html"><a href="sect023.html#sect0233"><i class="fa fa-check"></i><b>2.3.3</b> Indice de Lee : autocorrélation spatiale dans un contexte bivarié</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="sect024.html"><a href="sect024.html"><i class="fa fa-check"></i><b>2.4</b> Autocorrélation spatiale locale</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="sect024.html"><a href="sect024.html#sect0241"><i class="fa fa-check"></i><b>2.4.1</b> Statistiques locales de Getis et Ord : repérer les points chauds et froids pour une variable continue</a></li>
<li class="chapter" data-level="2.4.2" data-path="sect024.html"><a href="sect024.html#sect0242"><i class="fa fa-check"></i><b>2.4.2</b> Version locale du <em>I</em> de Moran</a></li>
<li class="chapter" data-level="2.4.3" data-path="sect024.html"><a href="sect024.html#sect0243"><i class="fa fa-check"></i><b>2.4.3</b> Typologie basée sur le diagramme de Moran</a></li>
<li class="chapter" data-level="2.4.4" data-path="sect024.html"><a href="sect024.html#sect0244"><i class="fa fa-check"></i><b>2.4.4</b> Version locale des statistiques de comptage de jointure (<em>Join Count Statistics</em>)</a></li>
<li class="chapter" data-level="2.4.5" data-path="sect024.html"><a href="sect024.html#sect0245"><i class="fa fa-check"></i><b>2.4.5</b> Version locale de l’indice de Lee</a></li>
<li class="chapter" data-level="2.4.6" data-path="sect024.html"><a href="sect024.html#sect0246"><i class="fa fa-check"></i><b>2.4.6</b> Typologie basée sur le diagramme de Moran dans un contexte bivarié</a></li>
<li class="chapter" data-level="2.4.7" data-path="sect024.html"><a href="sect024.html#sect0247"><i class="fa fa-check"></i><b>2.4.7</b> Autocorrélation locale pour une variable qualitative (catégorielle) : l’indicateur ELSA</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="sect025.html"><a href="sect025.html"><i class="fa fa-check"></i><b>2.5</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="2.6" data-path="sect026.html"><a href="sect026.html"><i class="fa fa-check"></i><b>2.6</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap03.html"><a href="chap03.html"><i class="fa fa-check"></i><b>3</b> Méthodes de répartition ponctuelle</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sect031.html"><a href="sect031.html"><i class="fa fa-check"></i><b>3.1</b> Fréquence et densité des points dans l’espace d’étude</a></li>
<li class="chapter" data-level="3.2" data-path="sect032.html"><a href="sect032.html"><i class="fa fa-check"></i><b>3.2</b> Analyse centrographique</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sect032.html"><a href="sect032.html#sect0311"><i class="fa fa-check"></i><b>3.2.1</b> Paramètres de tendance centrale d’un semis de points</a></li>
<li class="chapter" data-level="3.2.2" data-path="sect032.html"><a href="sect032.html#sect0312"><i class="fa fa-check"></i><b>3.2.2</b> Paramètres de dispersion d’un semis de points</a></li>
<li class="chapter" data-level="3.2.3" data-path="sect032.html"><a href="sect032.html#sect0313"><i class="fa fa-check"></i><b>3.2.3</b> Mise en œuvre de l’analyse centrographique dans R</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sect033.html"><a href="sect033.html"><i class="fa fa-check"></i><b>3.3</b> Forme d’un semis de points</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="sect033.html"><a href="sect033.html#sect0331"><i class="fa fa-check"></i><b>3.3.1</b> Méthode du plus proche voisin</a></li>
<li class="chapter" data-level="3.3.2" data-path="sect033.html"><a href="sect033.html#sect0332"><i class="fa fa-check"></i><b>3.3.2</b> Méthode des quadrats</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="sect034.html"><a href="sect034.html"><i class="fa fa-check"></i><b>3.4</b> Identification des agrégats spatiaux</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="sect034.html"><a href="sect034.html#sect0341"><i class="fa fa-check"></i><b>3.4.1</b> Cartographie de la densité dans une maille irrégulière</a></li>
<li class="chapter" data-level="3.4.2" data-path="sect034.html"><a href="sect034.html#sect0342"><i class="fa fa-check"></i><b>3.4.2</b> Cartographie de la densité dans une maille régulière</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="sect035.html"><a href="sect035.html"><i class="fa fa-check"></i><b>3.5</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="3.6" data-path="sect036.html"><a href="sect036.html"><i class="fa fa-check"></i><b>3.6</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap04.html"><a href="chap04.html"><i class="fa fa-check"></i><b>4</b> Méthodes de détection d’agrégats spatiaux et spatio-temporels</a>
<ul>
<li class="chapter" data-level="4.1" data-path="sect041.html"><a href="sect041.html"><i class="fa fa-check"></i><b>4.1</b> Agrégats d’entités spatiales ponctuelles</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="sect041.html"><a href="sect041.html#sect0411"><i class="fa fa-check"></i><b>4.1.1</b> DBSCAN : agrégats spatiaux</a></li>
<li class="chapter" data-level="4.1.2" data-path="sect041.html"><a href="sect041.html#sect0412"><i class="fa fa-check"></i><b>4.1.2</b> ST-DBSCAN : agrégats spatio-temporels</a></li>
<li class="chapter" data-level="4.1.3" data-path="sect041.html"><a href="sect041.html#sect0414"><i class="fa fa-check"></i><b>4.1.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="sect042.html"><a href="sect042.html"><i class="fa fa-check"></i><b>4.2</b> Méthodes de balayage de Kulldorff</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="sect042.html"><a href="sect042.html#sect0421"><i class="fa fa-check"></i><b>4.2.1</b> Objectifs de la méthode, types d’analyses, de modèles et d’agrégats</a></li>
<li class="chapter" data-level="4.2.2" data-path="sect042.html"><a href="sect042.html#sect0422"><i class="fa fa-check"></i><b>4.2.2</b> Principes de base de la méthode</a></li>
<li class="chapter" data-level="4.2.3" data-path="sect042.html"><a href="sect042.html#sect043"><i class="fa fa-check"></i><b>4.2.3</b> Mise en oeuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="sect044.html"><a href="sect044.html"><i class="fa fa-check"></i><b>4.3</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="4.4" data-path="sect045.html"><a href="sect045.html"><i class="fa fa-check"></i><b>4.4</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap05.html"><a href="chap05.html"><i class="fa fa-check"></i><b>5</b> Mesures d’accessibilité spatiale selon les différents de modes de transport</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sect051.html"><a href="sect051.html"><i class="fa fa-check"></i><b>5.1</b> Notions relatives à l’analyse de réseau</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="sect051.html"><a href="sect051.html#sect0511"><i class="fa fa-check"></i><b>5.1.1</b> Définition d’un réseau</a></li>
<li class="chapter" data-level="5.1.2" data-path="sect051.html"><a href="sect051.html#sect0512"><i class="fa fa-check"></i><b>5.1.2</b> Principaux problèmes résolus en analyse de réseau</a></li>
<li class="chapter" data-level="5.1.3" data-path="sect051.html"><a href="sect051.html#sect0513"><i class="fa fa-check"></i><b>5.1.3</b> Analyse de réseau et entités polygonales</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="sect052.html"><a href="sect052.html"><i class="fa fa-check"></i><b>5.2</b> Construction d’un réseau avec R5R</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="sect052.html"><a href="sect052.html#sect0521"><i class="fa fa-check"></i><b>5.2.1</b> Extraction des données spatiales pour R5R</a></li>
<li class="chapter" data-level="5.2.2" data-path="sect052.html"><a href="sect052.html#sect0522"><i class="fa fa-check"></i><b>5.2.2</b> Construction du réseau avec R5R</a></li>
<li class="chapter" data-level="5.2.3" data-path="sect052.html"><a href="sect052.html#sect0523"><i class="fa fa-check"></i><b>5.2.3</b> Calcul d’itinéraires avec R5R selon le mode de transport</a></li>
<li class="chapter" data-level="5.2.4" data-path="sect052.html"><a href="sect052.html#sect0524"><i class="fa fa-check"></i><b>5.2.4</b> Calcul de matrices OD selon différents modes de transport</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="sect053.html"><a href="sect053.html"><i class="fa fa-check"></i><b>5.3</b> Mesures d’accessibilité</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="sect053.html"><a href="sect053.html#sect0531"><i class="fa fa-check"></i><b>5.3.1</b> Notion d’accessibilité</a></li>
<li class="chapter" data-level="5.3.2" data-path="sect053.html"><a href="sect053.html#sect0532"><i class="fa fa-check"></i><b>5.3.2</b> Accessibilité spatiale potentielle</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="sect054.html"><a href="sect054.html"><i class="fa fa-check"></i><b>5.4</b> Mesures d’accessibilité spatiale potentielle dans R</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="sect054.html"><a href="sect054.html#sect0541"><i class="fa fa-check"></i><b>5.4.1</b> Accessibilité spatiale potentielle aux supermarchés</a></li>
<li class="chapter" data-level="5.4.2" data-path="sect054.html"><a href="sect054.html#sect0542"><i class="fa fa-check"></i><b>5.4.2</b> Accessibilité spatiale potentielle aux patinoires extérieures</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="sect055.html"><a href="sect055.html"><i class="fa fa-check"></i><b>5.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap06.html"><a href="chap06.html"><i class="fa fa-check"></i><b>6</b> Analyses d’évènements localisés sur un réseau</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sect061.html"><a href="sect061.html"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="sect062.html"><a href="sect062.html"><i class="fa fa-check"></i><b>6.2</b> Cartographie de la densité d’évènements sur un réseau</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="sect062.html"><a href="sect062.html#sect0621"><i class="fa fa-check"></i><b>6.2.1</b> Explication du NKDE et du TNKDE</a></li>
<li class="chapter" data-level="6.2.2" data-path="sect062.html"><a href="sect062.html#sect0622"><i class="fa fa-check"></i><b>6.2.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sect063.html"><a href="sect063.html"><i class="fa fa-check"></i><b>6.3</b> Mesure d’autocorrélation spatiale sur un réseau</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="sect063.html"><a href="sect063.html#sect0631"><i class="fa fa-check"></i><b>6.3.1</b> Getis et Ord</a></li>
<li class="chapter" data-level="6.3.2" data-path="sect063.html"><a href="sect063.html#sect0632"><i class="fa fa-check"></i><b>6.3.2</b> Typologie basée sur le diagramme de Moran</a></li>
<li class="chapter" data-level="6.3.3" data-path="sect063.html"><a href="sect063.html#sect0633"><i class="fa fa-check"></i><b>6.3.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="sect064.html"><a href="sect064.html"><i class="fa fa-check"></i><b>6.4</b> DBSCAN sur un réseau</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="sect064.html"><a href="sect064.html#sect0641"><i class="fa fa-check"></i><b>6.4.1</b> Explication du NKDE et du TNKDE</a></li>
<li class="chapter" data-level="6.4.2" data-path="sect064.html"><a href="sect064.html#sect0642"><i class="fa fa-check"></i><b>6.4.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="sect065.html"><a href="sect065.html"><i class="fa fa-check"></i><b>6.5</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="6.6" data-path="sect066.html"><a href="sect066.html"><i class="fa fa-check"></i><b>6.6</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap07.html"><a href="chap07.html"><i class="fa fa-check"></i><b>7</b> Introduction aux modèles de régression spatiale</a>
<ul>
<li class="chapter" data-level="7.1" data-path="sect071.html"><a href="sect071.html"><i class="fa fa-check"></i><b>7.1</b> Modèles économétriques spatiaux</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="sect071.html"><a href="sect071.html#sect0711"><i class="fa fa-check"></i><b>7.1.1</b> Bref retour sur la régression linéaire multiple</a></li>
<li class="chapter" data-level="7.1.2" data-path="sect071.html"><a href="sect071.html#sect0712"><i class="fa fa-check"></i><b>7.1.2</b> Les différents modèles spatiaux autorégressifs</a></li>
<li class="chapter" data-level="7.1.3" data-path="sect071.html"><a href="sect071.html#sect0713"><i class="fa fa-check"></i><b>7.1.3</b> Quel modèle choisir?</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="sect072.html"><a href="sect072.html"><i class="fa fa-check"></i><b>7.2</b> Modèles généralisés additifs (GAM) avec une <em>spline</em> bivariée sur les coordonnées géographiques</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="sect072.html"><a href="sect072.html#sect0721"><i class="fa fa-check"></i><b>7.2.1</b> Principe de base d’un GAM intégrant l’espace</a></li>
<li class="chapter" data-level="7.2.2" data-path="sect072.html"><a href="sect072.html#sect0722"><i class="fa fa-check"></i><b>7.2.2</b> Construction d’un modèle GAM dans R</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="sect073.html"><a href="sect073.html"><i class="fa fa-check"></i><b>7.3</b> Régression géographiquement pondérée</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="sect073.html"><a href="sect073.html#sect0731"><i class="fa fa-check"></i><b>7.3.1</b> Principe de base</a></li>
<li class="chapter" data-level="7.3.2" data-path="sect073.html"><a href="sect073.html#sect0732"><i class="fa fa-check"></i><b>7.3.2</b> Construction et analyse du modèle GWR dans R</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="sect074.html"><a href="sect074.html"><i class="fa fa-check"></i><b>7.4</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="7.5" data-path="sect075.html"><a href="sect075.html"><i class="fa fa-check"></i><b>7.5</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap08.html"><a href="chap08.html"><i class="fa fa-check"></i><b>8</b> Méthodes de classification non supervisée spatiale</a>
<ul>
<li class="chapter" data-level="8.1" data-path="sect081.html"><a href="sect081.html"><i class="fa fa-check"></i><b>8.1</b> Méthodes de classification non supervisée avec contrainte spatiale</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="sect081.html"><a href="sect081.html#sect0811"><i class="fa fa-check"></i><b>8.1.1</b> Algorithmes AZP</a></li>
<li class="chapter" data-level="8.1.2" data-path="sect081.html"><a href="sect081.html#sect0812"><i class="fa fa-check"></i><b>8.1.2</b> Algorithme SKATER</a></li>
<li class="chapter" data-level="8.1.3" data-path="sect081.html"><a href="sect081.html#sect0813"><i class="fa fa-check"></i><b>8.1.3</b> Algorithmes REDCAP</a></li>
<li class="chapter" data-level="8.1.4" data-path="sect081.html"><a href="sect081.html#sect0814"><i class="fa fa-check"></i><b>8.1.4</b> Algorithme du <em>max-p-regions problem</em></a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="sect082.html"><a href="sect082.html"><i class="fa fa-check"></i><b>8.2</b> Méthodes de classification non supervisée avec une dimension spatiale</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="sect082.html"><a href="sect082.html#sect0821"><i class="fa fa-check"></i><b>8.2.1</b> Classification ascendante hiérarchique spatiale (<em>ClustGeo</em>)</a></li>
<li class="chapter" data-level="8.2.2" data-path="sect082.html"><a href="sect082.html#sect0822"><i class="fa fa-check"></i><b>8.2.2</b> <em>Spatial fuzzy c-means</em></a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="sect083.html"><a href="sect083.html"><i class="fa fa-check"></i><b>8.3</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="8.4" data-path="sect084.html"><a href="sect084.html"><i class="fa fa-check"></i><b>8.4</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap09.html"><a href="chap09.html"><i class="fa fa-check"></i><b>9</b> Méthodes d’interpolation spatiale</a>
<ul>
<li class="chapter" data-level="9.1" data-path="sect091.html"><a href="sect091.html"><i class="fa fa-check"></i><b>9.1</b> Méthodes déterministes</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="sect091.html"><a href="sect091.html#sect0911"><i class="fa fa-check"></i><b>9.1.1</b> Interpolation polynomiale locale</a></li>
<li class="chapter" data-level="9.1.2" data-path="sect091.html"><a href="sect091.html#sect0912"><i class="fa fa-check"></i><b>9.1.2</b> Interpolation de l’inverse à la distance (<em>IDW</em>)</a></li>
<li class="chapter" data-level="9.1.3" data-path="sect091.html"><a href="sect091.html#sect0913"><i class="fa fa-check"></i><b>9.1.3</b> Fonctions relationnelles</a></li>
<li class="chapter" data-level="9.1.4" data-path="sect091.html"><a href="sect091.html#sect0914"><i class="fa fa-check"></i><b>9.1.4</b> Fonctions conditionnelles</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="sect092.html"><a href="sect092.html"><i class="fa fa-check"></i><b>9.2</b> Méthodes géostatistiques</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="sect092.html"><a href="sect092.html#sect0921"><i class="fa fa-check"></i><b>9.2.1</b> Krigeage simple</a></li>
<li class="chapter" data-level="9.2.2" data-path="sect092.html"><a href="sect092.html#sect0922"><i class="fa fa-check"></i><b>9.2.2</b> Krigeage universel</a></li>
<li class="chapter" data-level="9.2.3" data-path="sect092.html"><a href="sect092.html#sect0923"><i class="fa fa-check"></i><b>9.2.3</b> Co-krigeage</a></li>
<li class="chapter" data-level="9.2.4" data-path="sect092.html"><a href="sect092.html#sect0924"><i class="fa fa-check"></i><b>9.2.4</b> Krigeage résiduel</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="sect093.html"><a href="sect093.html"><i class="fa fa-check"></i><b>9.3</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="9.4" data-path="sect094.html"><a href="sect094.html"><i class="fa fa-check"></i><b>9.4</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap10.html"><a href="chap10.html"><i class="fa fa-check"></i><b>10</b> Correction des exercices</a>
<ul>
<li class="chapter" data-level="10.1" data-path="sect1001.html"><a href="sect1001.html"><i class="fa fa-check"></i><b>10.1</b> Exercices du chapitre 1</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="sect1001.html"><a href="sect1001.html#sect10011"><i class="fa fa-check"></i><b>10.1.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.1.2" data-path="sect1001.html"><a href="sect1001.html#sect10012"><i class="fa fa-check"></i><b>10.1.2</b> Exercice 2</a></li>
<li class="chapter" data-level="10.1.3" data-path="sect1001.html"><a href="sect1001.html#sect10013"><i class="fa fa-check"></i><b>10.1.3</b> Exercice 3</a></li>
<li class="chapter" data-level="10.1.4" data-path="sect1001.html"><a href="sect1001.html#sect10014"><i class="fa fa-check"></i><b>10.1.4</b> Exercice 4</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="sect1002.html"><a href="sect1002.html"><i class="fa fa-check"></i><b>10.2</b> Exercices du chapitre 2</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="sect1002.html"><a href="sect1002.html#sect10021"><i class="fa fa-check"></i><b>10.2.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.2.2" data-path="sect1002.html"><a href="sect1002.html#sect10022"><i class="fa fa-check"></i><b>10.2.2</b> Exercice 2</a></li>
<li class="chapter" data-level="10.2.3" data-path="sect1002.html"><a href="sect1002.html#sect10023"><i class="fa fa-check"></i><b>10.2.3</b> Exercice 3</a></li>
<li class="chapter" data-level="10.2.4" data-path="sect1002.html"><a href="sect1002.html#sect10024"><i class="fa fa-check"></i><b>10.2.4</b> Exercice 4</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="sect1003.html"><a href="sect1003.html"><i class="fa fa-check"></i><b>10.3</b> Exercices du chapitre 3</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="sect1003.html"><a href="sect1003.html#sect10031"><i class="fa fa-check"></i><b>10.3.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.3.2" data-path="sect1003.html"><a href="sect1003.html#sect10032"><i class="fa fa-check"></i><b>10.3.2</b> Exercice 2</a></li>
<li class="chapter" data-level="10.3.3" data-path="sect1003.html"><a href="sect1003.html#sect10033"><i class="fa fa-check"></i><b>10.3.3</b> Exercice 3</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="sect1004.html"><a href="sect1004.html"><i class="fa fa-check"></i><b>10.4</b> Exercices du chapitre 4</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="sect1004.html"><a href="sect1004.html#sect10041"><i class="fa fa-check"></i><b>10.4.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.4.2" data-path="sect1004.html"><a href="sect1004.html#sect10042"><i class="fa fa-check"></i><b>10.4.2</b> Exercice 2</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="sect1005.html"><a href="sect1005.html"><i class="fa fa-check"></i><b>10.5</b> Exercices du chapitre 5</a></li>
<li class="chapter" data-level="10.6" data-path="sect1006.html"><a href="sect1006.html"><i class="fa fa-check"></i><b>10.6</b> Exercices du chapitre 6</a></li>
<li class="chapter" data-level="10.7" data-path="sect1007.html"><a href="sect1007.html"><i class="fa fa-check"></i><b>10.7</b> Exercices du chapitre 7</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="sect1007.html"><a href="sect1007.html#sect10071"><i class="fa fa-check"></i><b>10.7.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.7.2" data-path="sect1007.html"><a href="sect1007.html#sect10072"><i class="fa fa-check"></i><b>10.7.2</b> Exercice 2</a></li>
<li class="chapter" data-level="10.7.3" data-path="sect1007.html"><a href="sect1007.html#sect10073"><i class="fa fa-check"></i><b>10.7.3</b> Exercice 3</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="sect1008.html"><a href="sect1008.html"><i class="fa fa-check"></i><b>10.8</b> Exercices du chapitre 8</a>
<ul>
<li class="chapter" data-level="10.8.1" data-path="sect1008.html"><a href="sect1008.html#sect10081"><i class="fa fa-check"></i><b>10.8.1</b> Exercice 1</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="sect1009.html"><a href="sect1009.html"><i class="fa fa-check"></i><b>10.9</b> Exercices du chapitre 9</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notes de cours GMQ405 :
Modélisation et analyse spatiale</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sect081" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Méthodes de classification non supervisée avec contrainte spatiale<a href="sect081.html#sect081" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Nous avons vu que l’objectif d’une méthode non supervisée appliquée à des données spatiales est de regrouper en <em>n</em> classes les unités spatiales d’une couche géographique. Prenons l’exemple de quatre variables environnementales cartographiés à la figure <a href="sect081.html#fig:figVarEnv">8.1</a> pour les IRIS de la ville de Lyon, dont trois considérées comme des nuisances (bruit, dioxyde d’azote et particules fines) et une considérée comme avantageuse (végétation).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figVarEnv"></span>
<img src="GMQ405_files/figure-html/figVarEnv-1.png" alt="Cartographie des variables environnementales" width="100%" />
<p class="caption">
Figure 8.1: Cartographie des variables environnementales
</p>
</div>
<p>Il est possible de regrouper les unités spatiales avec ou sans contrainte spatiale :</p>
<ul>
<li><p><strong>Sans contrainte spatiale</strong>, nous cherchons à regrouper les IRIS (unités spatiales) avec des valeurs similaires pour les quatre variables retenues (L<sub>den</sub>, NO<sub>2</sub>, PM<sub>2,5</sub> et pourcentage de canopée). Cette approche est illustrée à la figure <a href="sect081.html#fig:figKmeansSkater">8.2</a>.a avec l’algorithme k-moyennes (<em>k-means</em> en anglais) avec cinq classes.</p></li>
<li><p><strong>Avec contrainte spatiale</strong>, nous cherchons à regrouper les IRIS (unités spatiales) avec des valeurs similaires pour les quatre variables retenues, tout en nous assurant que les regroupements forment des régions avec une absence de mitage. Cette approche est illustrée à la figure <a href="sect081.html#fig:figKmeansSkater">8.2</a>.b avec l’algorithme SKATER (<em>Spatial ’K’luster Analysis by Tree Edge Removal</em>) avec cinq classes. Autrement dit, l’objectif des méthodes de classification non supervisée avec contrainte spatiale est d’agréger <em>n</em> unités spatiales en <em>m</em> régions non discontinues (avec <em>n</em> &lt; <em>m</em>) <span class="citation">(<a href="#ref-openshaw1995algorithms">Openshaw et Rao 1995, 428</a>)</span>.</p></li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figKmeansSkater"></span>
<img src="GMQ405_files/figure-html/figKmeansSkater-1.png" alt="Classification non supervisée avec et sans contrainte spatiale" width="85%" />
<p class="caption">
Figure 8.2: Classification non supervisée avec et sans contrainte spatiale
</p>
</div>
<div class="bloc_objectif">
<p><strong>Intérêt et limites des méthodes de classification avec une contrainte spatiale</strong></p>
<p>Selon Gelb et Apparicio <span class="citation">(<a href="#ref-ClassificationFloue">2021, 7</a>)</span>, le résultat d’une méthode de classification avec une contrainte spatiale est « la création de régions très cohérentes spatialement, c’est-à-dire avec une absence de mitage. Autrement dit, avec ces méthodes, il n’est pas possible d’identifier de groupes qui seraient spatialement discontinus, c’est-à-dire composés de plusieurs ensembles régionaux séparés. L’impossibilité d’obtenir du mitage au sein des différentes régions peut masquer la présence de valeurs fortement dissemblables localement, malgré la prise en compte de l’espace. Or, ces observations systématiquement différentes de leurs voisines doivent faire l’objet d’une attention particulière dans les exercices de classification intégrant l’espace, ce que ne permettent pas ces méthodes d’agrégation spatiale.</p>
<p>[…] Les limites de ces méthodes, particulièrement celles relatives au mitage, ont conduit plus récemment à la mise au point de nouvelles méthodes incluant l’espace dans le processus de classification, sans imposer une contrainte de contiguïté. Plus spécifiquement, ces nouvelles méthodes sont des modifications des algorithmes classiques, tels que la CAH ou le FCM, pour intégrer la dimension spatiale en parallèle à la dimension sémantique des données. En d’autres termes, l’espace n’est plus intégré comme une contrainte dans les algorithmes de classification, mais plutôt comme une donnée supplémentaire ».</p>
</div>
<p>Les principaux algorithmes de classification supervisée avec contrainte spatiale (<em>Spatially Constrained Clustering Methods</em> en anglais) sont :</p>
<ul>
<li>La méthode de zonage automatique (<em>Automatic Zoning Procedure</em> en anglais) (AZP) proposée par Openshaw <span class="citation">(<a href="#ref-openshaw1977geographical">1977</a>)</span>, puis améliorée par Openshaw et Rao <span class="citation">(<a href="#ref-openshaw1995algorithms">1995</a>)</span>.</li>
<li>L’algorithme SKATER (<em>Spatial ’K’luster Analysis by Tree Edge Removal</em>) <span class="citation">(<a href="#ref-assunccao2006efficient">Assunção et al. 2006</a>)</span>.</li>
<li>L’Algorithme REDCAP (<em>Regionalization with dynamically constrained agglomerative clustering and partitioning</em>) <span class="citation">(<a href="#ref-guo2008regionalization">Guo 2008</a>)</span>.</li>
<li>L’Algorithme du <em>max-p-regions problem</em> <span class="citation">(<a href="#ref-duque2012max">Duque, Anselin et Rey 2012</a>)</span>.</li>
</ul>
<p>Pour mettre en œuvre ces différents algorithmes, nous utilisons le <em>package</em> <code>rgeoda</code> <span class="citation">(<a href="#ref-packagergeoda">Li et Anselin 2023</a>)</span>. Notez que l’algorithme SKATER est aussi implémenté dans le <em>package</em> <code>spded</code> (fonction <code>skater</code>).</p>
<div id="sect0811" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Algorithmes AZP<a href="sect081.html#sect0811" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>L’algorithme AZP (<em>Automatic Zoning Problem</em>) est une approche itérative et heuristique visant à regrouper des polygones adjacents en <em>m</em> régions, tout en maximisant la variance interrégionale (variance interclasse) et minimisant la variance intrarégionale (variance intraclasse) calculées sur les <em>p</em> variables. Autrement dit, il vise à créer des régions non discontinues les plus homogènes possibles et les plus dissemblables entre elles sur la base des <em>p</em> variables. Pour utiliser l’AZP, il faut spécifier le nombre de régions (<em>m</em>) désiré. Notez qu’il existe trois algorithmes pour l’AZP :</p>
<ol style="list-style-type: decimal">
<li>AZP (<em>Automatic Zoning Procedure</em>), soit la première version par Stan Openshaw <span class="citation">(<a href="#ref-openshaw1977geographical">1977</a>)</span>.</li>
<li>AZP-SA (<em>A simulated annealing AZP method</em>) <span class="citation">(<a href="#ref-openshaw1995algorithms">Openshaw et Rao 1995</a>)</span>.</li>
<li>AZP-TABU (<em>A tabu search heuristic version of AZP</em>) <span class="citation">(<a href="#ref-openshaw1995algorithms">Openshaw et Rao 1995</a>)</span>.</li>
</ol>
<p>Pour une description détaillée de ces trois algorithmes, vous pouvez consulter Openshaw et Rao <span class="citation">(<a href="#ref-openshaw1995algorithms">1995</a>)</span> ou encore le <a href="https://geodacenter.github.io/workbook/9d_spatial4/lab9d.html#principle">lien suivant</a>.</p>
<p>Appliquons ces algorithmes aux 506 IRIS de la ville de Lyon avec les quatre variables environnementales préalablement centrées réduites (bruit, dioxyde d’azote, particules fines et pourcentage de végétation) et une matrice de contiguïté selon le partage d’un nœud. Le <em>package</em> <code>rgeoda</code> comprend trois fonctions pour l’AZP : <code>azp_greedy</code> (AZP), <code>azp_sa</code> (AZP-SA), <code>azp_tabu</code> (AZP-TABU). Pour l’exercice, nous fixons le nombre de régions à 5. Notez que par défaut, les variables seront centrées réduites (moyenne = 0 et écart-type = 1) avec le paramètre <code>scale_method="standardize"</code>.</p>
<div class="sourceCode" id="cb552"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb552-1"><a href="sect081.html#cb552-1" tabindex="-1"></a><span class="fu">library</span>(rgeoda)</span>
<span id="cb552-2"><a href="sect081.html#cb552-2" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb552-3"><a href="sect081.html#cb552-3" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb552-4"><a href="sect081.html#cb552-4" tabindex="-1"></a><span class="do">## Variables</span></span>
<span id="cb552-5"><a href="sect081.html#cb552-5" tabindex="-1"></a>VarsEnv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Lden&quot;</span>, <span class="st">&quot;NO2&quot;</span>, <span class="st">&quot;PM25&quot;</span>, <span class="st">&quot;VegHautPrt&quot;</span>)</span>
<span id="cb552-6"><a href="sect081.html#cb552-6" tabindex="-1"></a><span class="do">## Dataframe sans la géométrie et les quatre variables</span></span>
<span id="cb552-7"><a href="sect081.html#cb552-7" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;data/chap08/DonneesLyon.Rdata&quot;</span>)</span>
<span id="cb552-8"><a href="sect081.html#cb552-8" tabindex="-1"></a>Data <span class="ot">&lt;-</span> <span class="fu">st_drop_geometry</span>(LyonIris[VarsEnv])</span>
<span id="cb552-9"><a href="sect081.html#cb552-9" tabindex="-1"></a><span class="do">## Création d&#39;une matrice de contiguïté avec rgeoda</span></span>
<span id="cb552-10"><a href="sect081.html#cb552-10" tabindex="-1"></a>queen_w <span class="ot">&lt;-</span> <span class="fu">queen_weights</span>(LyonIris)</span>
<span id="cb552-11"><a href="sect081.html#cb552-11" tabindex="-1"></a><span class="do">## Calcul des trois algorithmes</span></span>
<span id="cb552-12"><a href="sect081.html#cb552-12" tabindex="-1"></a>azp <span class="ot">&lt;-</span> rgeoda<span class="sc">::</span><span class="fu">azp_greedy</span>(<span class="at">p=</span><span class="dv">5</span>,       <span class="co"># Nombre de régions</span></span>
<span id="cb552-13"><a href="sect081.html#cb552-13" tabindex="-1"></a>                          <span class="at">w=</span>queen_w, <span class="co"># Matrice contiguïté</span></span>
<span id="cb552-14"><a href="sect081.html#cb552-14" tabindex="-1"></a>                          <span class="at">df=</span>Data,   <span class="co"># Tableau de données</span></span>
<span id="cb552-15"><a href="sect081.html#cb552-15" tabindex="-1"></a>                          <span class="at">scale_method =</span> <span class="st">&quot;standardize&quot;</span>) <span class="co"># cote z</span></span>
<span id="cb552-16"><a href="sect081.html#cb552-16" tabindex="-1"></a>azp.sa <span class="ot">&lt;-</span> rgeoda<span class="sc">::</span><span class="fu">azp_sa</span>(<span class="at">p=</span><span class="dv">5</span>, <span class="at">w=</span>queen_w, <span class="at">df=</span>Data, <span class="at">cooling_rate =</span> <span class="fl">0.85</span>)</span>
<span id="cb552-17"><a href="sect081.html#cb552-17" tabindex="-1"></a>azp.tab <span class="ot">&lt;-</span> rgeoda<span class="sc">::</span><span class="fu">azp_tabu</span>(<span class="at">p=</span><span class="dv">5</span>, <span class="at">w=</span>queen_w, <span class="at">df=</span>Data, <span class="at">tabu_length =</span> <span class="dv">10</span>, <span class="at">conv_tabu =</span> <span class="dv">10</span>)</span>
<span id="cb552-18"><a href="sect081.html#cb552-18" tabindex="-1"></a><span class="do">## Création des trois champs dans la couche de Lyon</span></span>
<span id="cb552-19"><a href="sect081.html#cb552-19" tabindex="-1"></a>LyonIris<span class="sc">$</span>Azp <span class="ot">&lt;-</span> <span class="fu">as.character</span>(azp<span class="sc">$</span>Clusters)</span>
<span id="cb552-20"><a href="sect081.html#cb552-20" tabindex="-1"></a>LyonIris<span class="sc">$</span>Azp_sa <span class="ot">&lt;-</span> <span class="fu">as.character</span>(azp.sa<span class="sc">$</span>Clusters)</span>
<span id="cb552-21"><a href="sect081.html#cb552-21" tabindex="-1"></a>LyonIris<span class="sc">$</span>Azp_tab <span class="ot">&lt;-</span> <span class="fu">as.character</span>(azp.tab<span class="sc">$</span>Clusters)</span></code></pre></div>
<p>Cartographions les résultats des trois algorithmes AZP (figure <a href="sect081.html#fig:CartoAZP">8.3</a>).</p>
<div class="sourceCode" id="cb553"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb553-1"><a href="sect081.html#cb553-1" tabindex="-1"></a><span class="do">## Cartographie des résultats</span></span>
<span id="cb553-2"><a href="sect081.html#cb553-2" tabindex="-1"></a>Carte.AZP1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span><span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb553-3"><a href="sect081.html#cb553-3" tabindex="-1"></a>              <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;Azp&quot;</span>, <span class="at">palette =</span> <span class="st">&quot;Set1&quot;</span>, <span class="at">title =</span><span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb553-4"><a href="sect081.html#cb553-4" tabindex="-1"></a>              <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, </span>
<span id="cb553-5"><a href="sect081.html#cb553-5" tabindex="-1"></a>                <span class="at">main.title =</span> <span class="st">&quot;a. AZP&quot;</span>, </span>
<span id="cb553-6"><a href="sect081.html#cb553-6" tabindex="-1"></a>                <span class="at">main.title.position =</span> <span class="st">&quot;center&quot;</span>, </span>
<span id="cb553-7"><a href="sect081.html#cb553-7" tabindex="-1"></a>                <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb553-8"><a href="sect081.html#cb553-8" tabindex="-1"></a>Carte.AZP2 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span><span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb553-9"><a href="sect081.html#cb553-9" tabindex="-1"></a>              <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;Azp_sa&quot;</span>, <span class="at">palette =</span> <span class="st">&quot;Set1&quot;</span>, <span class="at">title =</span><span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb553-10"><a href="sect081.html#cb553-10" tabindex="-1"></a>              <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, </span>
<span id="cb553-11"><a href="sect081.html#cb553-11" tabindex="-1"></a>                <span class="at">main.title =</span> <span class="st">&quot;b. AZP Simulated Annealing&quot;</span>, </span>
<span id="cb553-12"><a href="sect081.html#cb553-12" tabindex="-1"></a>                <span class="at">main.title.position =</span> <span class="st">&quot;center&quot;</span>, </span>
<span id="cb553-13"><a href="sect081.html#cb553-13" tabindex="-1"></a>                <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb553-14"><a href="sect081.html#cb553-14" tabindex="-1"></a>Carte.AZP3 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span><span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb553-15"><a href="sect081.html#cb553-15" tabindex="-1"></a>              <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;Azp_tab&quot;</span>, <span class="at">palette =</span> <span class="st">&quot;Set1&quot;</span>, <span class="at">title =</span><span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb553-16"><a href="sect081.html#cb553-16" tabindex="-1"></a>              <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, </span>
<span id="cb553-17"><a href="sect081.html#cb553-17" tabindex="-1"></a>                <span class="at">main.title =</span> <span class="st">&quot;c. AZP Tabu Search&quot;</span>, </span>
<span id="cb553-18"><a href="sect081.html#cb553-18" tabindex="-1"></a>                <span class="at">main.title.position =</span> <span class="st">&quot;center&quot;</span>, </span>
<span id="cb553-19"><a href="sect081.html#cb553-19" tabindex="-1"></a>                <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb553-20"><a href="sect081.html#cb553-20" tabindex="-1"></a><span class="fu">tmap_arrange</span>(Carte.AZP1, Carte.AZP2, Carte.AZP3, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:CartoAZP"></span>
<img src="GMQ405_files/figure-html/CartoAZP-1.png" alt="Regroupements des 505 IRIS en cinq régions selon les trois algorithmes AZP" width="100%" />
<p class="caption">
Figure 8.3: Regroupements des 505 IRIS en cinq régions selon les trois algorithmes AZP
</p>
</div>
<p>Par la suite, nous comparons les résultats obtenus des trois algorithmes en reportant :</p>
<ol style="list-style-type: decimal">
<li>Les variances totale, intrarégionale et interrégionale, et surtout le ratio entre les variances intergroupe et totale. Ce ratio varie de 0 à 1 et exprime la proportion de la variance des variables qui est expliquée par les différentes régions obtenues; plus il est élevé, meilleur est le résultat. Par conséquent, il peut être utilisé pour identifier la solution optimale entre les trois algorithmes.</li>
<li>Le nombre d’observations par région.</li>
<li>Les valeurs moyennes des variables centrées réduites par région.</li>
</ol>
<div class="sourceCode" id="cb554"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb554-1"><a href="sect081.html#cb554-1" tabindex="-1"></a><span class="do">## Calcul du ratio entre les variances intergroupes et totale</span></span>
<span id="cb554-2"><a href="sect081.html#cb554-2" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Ratio des variances interrégionale et totale&quot;</span>,</span>
<span id="cb554-3"><a href="sect081.html#cb554-3" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">AZP : &quot;</span>, <span class="fu">round</span>(azp<span class="sc">$</span><span class="st">`</span><span class="at">The ratio of between to total sum of squares</span><span class="st">`</span>, <span class="dv">3</span>),</span>
<span id="cb554-4"><a href="sect081.html#cb554-4" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">AZP-SA : &quot;</span>, <span class="fu">round</span>(azp.sa<span class="sc">$</span><span class="st">`</span><span class="at">The ratio of between to total sum of squares</span><span class="st">`</span>, <span class="dv">3</span>),</span>
<span id="cb554-5"><a href="sect081.html#cb554-5" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">AZP-TABU : &quot;</span>, <span class="fu">round</span>(azp.tab<span class="sc">$</span><span class="st">`</span><span class="at">The ratio of between to total sum of squares</span><span class="st">`</span>, <span class="dv">3</span>)</span>
<span id="cb554-6"><a href="sect081.html#cb554-6" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Ratio des variances interrégionale et totale 
## AZP :  0.436 
## AZP-SA :  0.518 
## AZP-TABU :  0.428</code></pre>
<p>À la lecture des valeurs du ratio entre la variance interrégionale et la variance totale ci-dessus, celle la plus élevée est obtenue pour l’AZP-SA (0,518), suivies de celles de l’AZP (0,436) et de l’AZP-TABU (0,428). Nous retenons alors l’AZP-SA.</p>
<div class="sourceCode" id="cb556"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb556-1"><a href="sect081.html#cb556-1" tabindex="-1"></a><span class="do">## Nombre d&#39;observations par région</span></span>
<span id="cb556-2"><a href="sect081.html#cb556-2" tabindex="-1"></a><span class="fu">table</span>(LyonIris<span class="sc">$</span>Azp)</span></code></pre></div>
<pre><code>## 
##   1   2   3   4   5 
## 186 176 104  27  13</code></pre>
<div class="sourceCode" id="cb558"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb558-1"><a href="sect081.html#cb558-1" tabindex="-1"></a><span class="fu">table</span>(LyonIris<span class="sc">$</span>Azp_sa)</span></code></pre></div>
<pre><code>## 
##   1   2   3   4   5 
## 221 107  87  51  40</code></pre>
<div class="sourceCode" id="cb560"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb560-1"><a href="sect081.html#cb560-1" tabindex="-1"></a><span class="fu">table</span>(LyonIris<span class="sc">$</span>Azp_tab)</span></code></pre></div>
<pre><code>## 
##   1   2   3   4   5 
## 191 186  91  27  11</code></pre>
<div class="sourceCode" id="cb562"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb562-1"><a href="sect081.html#cb562-1" tabindex="-1"></a><span class="do">## Valeurs moyennes des variables centrées réduites par région</span></span>
<span id="cb562-2"><a href="sect081.html#cb562-2" tabindex="-1"></a>Data<span class="sc">$</span>Azp <span class="ot">&lt;-</span> azp<span class="sc">$</span>Clusters</span>
<span id="cb562-3"><a href="sect081.html#cb562-3" tabindex="-1"></a>Data<span class="sc">$</span>Azp_sa <span class="ot">&lt;-</span> azp.sa<span class="sc">$</span>Clusters</span>
<span id="cb562-4"><a href="sect081.html#cb562-4" tabindex="-1"></a>Data<span class="sc">$</span>Azp_tab <span class="ot">&lt;-</span> azp.tab<span class="sc">$</span>Clusters</span>
<span id="cb562-5"><a href="sect081.html#cb562-5" tabindex="-1"></a><span class="fu">aggregate</span>(<span class="fu">cbind</span>(Lden,NO2,PM25,VegHautPrt) <span class="sc">~</span> Azp, <span class="at">data =</span> Data, <span class="at">FUN =</span> mean)</span></code></pre></div>
<pre><code>##   Azp     Lden      NO2     PM25 VegHautPrt
## 1   1 58.05464 35.21961 18.85212   15.45333
## 2   2 55.42159 26.45169 16.32884   13.98563
## 3   3 53.23122 23.63965 14.95293   30.42529
## 4   4 52.26742 22.99701 14.58065   20.39444
## 5   5 48.71652 18.24301 13.07043   33.07154</code></pre>
<div class="sourceCode" id="cb564"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb564-1"><a href="sect081.html#cb564-1" tabindex="-1"></a><span class="fu">aggregate</span>(<span class="fu">cbind</span>(Lden,NO2,PM25,VegHautPrt) <span class="sc">~</span> Azp_sa, <span class="at">data =</span> Data, <span class="at">FUN =</span> mean)</span></code></pre></div>
<pre><code>##   Azp_sa     Lden      NO2     PM25 VegHautPrt
## 1      1 57.41952 35.02151 18.80132   14.41317
## 2      2 55.11019 22.52804 15.55562   14.12178
## 3      3 51.08297 20.48809 14.16951   28.66000
## 4      4 54.23625 24.47389 14.96836   22.30059
## 5      5 58.40430 33.55155 17.08480   28.83775</code></pre>
<div class="sourceCode" id="cb566"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb566-1"><a href="sect081.html#cb566-1" tabindex="-1"></a><span class="fu">aggregate</span>(<span class="fu">cbind</span>(Lden,NO2,PM25,VegHautPrt) <span class="sc">~</span> Azp_tab, <span class="at">data =</span> Data, <span class="at">FUN =</span> mean)</span></code></pre></div>
<pre><code>##   Azp_tab     Lden      NO2     PM25 VegHautPrt
## 1       1 55.24285 26.04447 16.19300   14.67712
## 2       2 58.05464 35.21961 18.85212   15.45333
## 3       3 53.19298 23.97221 14.99671   31.90967
## 4       4 52.26742 22.99701 14.58065   20.39444
## 5       5 48.32861 17.74683 12.84853   31.68364</code></pre>
<p>Les résultats finaux de l’AZP-SA sont présentés au tableau <a href="sect081.html#tab:dataAZPsa">8.1</a> et à la figure <a href="sect081.html#fig:CartoAZPsa">8.4</a>. L’analyse conjointe du tableau et de la carte permet ainsi d’interpréter chacune des classes. En guise d’exemple, nous pouvons conclure que :</p>
<ul>
<li><strong>la région 1</strong> comprend 221 IRIS localisés au centre de la ville de Lyon et caractérisés par des niveaux moyens élevés de bruit (57,4), de dioxyde d’azote (35) et de particules fines (18,8) élevés et un faible pourcentage de canopée (14,4%),</li>
<li>tandis que <strong>la région 2</strong> comprend 107 IRIS localisés à l’extrême ouest de la ville et caractérisés par les plus faibles niveaux de polluants (51,1, 20,5 et 14,2) et une forte moyenne pour la canopée (28,7%).</li>
</ul>
<table>
<caption>
<span id="tab:dataAZPsa">Tableau 8.1: </span>Valeurs moyennes des variables pour les quatre régions obtenus par l’AZP-SA
</caption>
<thead>
<tr>
<th style="text-align:center;">
Région
</th>
<th style="text-align:center;">
Lden
</th>
<th style="text-align:center;">
NO2
</th>
<th style="text-align:center;">
PM25
</th>
<th style="text-align:center;">
Végétation
</th>
<th style="text-align:center;">
Nombre d’IRIS
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
57,4
</td>
<td style="text-align:center;">
35,0
</td>
<td style="text-align:center;">
18,8
</td>
<td style="text-align:center;">
14,4
</td>
<td style="text-align:center;">
221
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
55,1
</td>
<td style="text-align:center;">
22,5
</td>
<td style="text-align:center;">
15,6
</td>
<td style="text-align:center;">
14,1
</td>
<td style="text-align:center;">
107
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
51,1
</td>
<td style="text-align:center;">
20,5
</td>
<td style="text-align:center;">
14,2
</td>
<td style="text-align:center;">
28,7
</td>
<td style="text-align:center;">
87
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
54,2
</td>
<td style="text-align:center;">
24,5
</td>
<td style="text-align:center;">
15,0
</td>
<td style="text-align:center;">
22,3
</td>
<td style="text-align:center;">
51
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
58,4
</td>
<td style="text-align:center;">
33,6
</td>
<td style="text-align:center;">
17,1
</td>
<td style="text-align:center;">
28,8
</td>
<td style="text-align:center;">
40
</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:CartoAZPsa"></span>
<img src="GMQ405_files/figure-html/CartoAZPsa-1.png" alt="Regroupement des IRIS en cinq régions selon l'AZP-TABU" width="100%" />
<p class="caption">
Figure 8.4: Regroupement des IRIS en cinq régions selon l’AZP-TABU
</p>
</div>
<p>Nous avons vu que pour les algorithmes AZP, il faut spécifier le nombre de régions. Nous l’avons fixé arbitrairement à 5. Comme pour n’importe quelle méthode de classification non supervisée, déterminer le nombre de classes optimal est une étape cruciale qui peut s’appuyer sur différentes techniques, dont la méthode du coude basée sur l’inertie expliquée (ici le ratio entre les variances interrégionale et totale), l’indicateur de silhouette et la méthode GAP. Pour une description détaillée de ces méthodes, consultez la <a href="https://laeq.github.io/LivreMethoQuantBolR/sect133.html#sect1332">section suivante</a> <span class="citation">(<a href="#ref-RBoldAir">Apparicio et Gelb 2022</a>)</span>. Le code ci-dessous permet de réaliser un graphique avec les valeurs du ratio (inertie expliquée) obtenues avec l’algorithme AZP-TABU calculé de 2 à 10 régions. À la lecture de la figure <a href="sect081.html#fig:AZPCoude">8.5</a>, nous observons deux ruptures (coudes) très nettes à 5 et 8.</p>
<div class="sourceCode" id="cb568"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb568-1"><a href="sect081.html#cb568-1" tabindex="-1"></a>nregions <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb568-2"><a href="sect081.html#cb568-2" tabindex="-1"></a>Data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">scale</span>(<span class="fu">st_drop_geometry</span>(LyonIris)[VarsEnv]))</span>
<span id="cb568-3"><a href="sect081.html#cb568-3" tabindex="-1"></a>queen_w <span class="ot">&lt;-</span> <span class="fu">queen_weights</span>(LyonIris)</span>
<span id="cb568-4"><a href="sect081.html#cb568-4" tabindex="-1"></a>inertie <span class="ot">&lt;-</span> <span class="fu">sapply</span>(nregions, <span class="cf">function</span>(k){</span>
<span id="cb568-5"><a href="sect081.html#cb568-5" tabindex="-1"></a>  <span class="co"># calcul de l&#39;AZP-TABU avec k</span></span>
<span id="cb568-6"><a href="sect081.html#cb568-6" tabindex="-1"></a>  resultat <span class="ot">&lt;-</span> <span class="fu">azp_tabu</span>(<span class="at">p=</span>k, <span class="at">w=</span>queen_w, <span class="at">df=</span>Data, <span class="at">tabu_length =</span> <span class="dv">10</span>, <span class="at">conv_tabu =</span> <span class="dv">10</span>)</span>
<span id="cb568-7"><a href="sect081.html#cb568-7" tabindex="-1"></a>  <span class="co"># récupération du ratio</span></span>
<span id="cb568-8"><a href="sect081.html#cb568-8" tabindex="-1"></a>  ratios <span class="ot">&lt;-</span> resultat<span class="sc">$</span><span class="st">`</span><span class="at">The ratio of between to total sum of squares</span><span class="st">`</span></span>
<span id="cb568-9"><a href="sect081.html#cb568-9" tabindex="-1"></a>  <span class="fu">return</span>(ratios)</span>
<span id="cb568-10"><a href="sect081.html#cb568-10" tabindex="-1"></a>})</span>
<span id="cb568-11"><a href="sect081.html#cb568-11" tabindex="-1"></a></span>
<span id="cb568-12"><a href="sect081.html#cb568-12" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">k =</span> nregions, <span class="at">ratio =</span> inertie)</span>
<span id="cb568-13"><a href="sect081.html#cb568-13" tabindex="-1"></a><span class="fu">ggplot</span>(df) <span class="sc">+</span> </span>
<span id="cb568-14"><a href="sect081.html#cb568-14" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> k, <span class="at">y =</span> ratio)) <span class="sc">+</span> </span>
<span id="cb568-15"><a href="sect081.html#cb568-15" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> k, <span class="at">y =</span> ratio), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb568-16"><a href="sect081.html#cb568-16" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Nombre de régions&quot;</span>, <span class="at">y =</span> <span class="st">&quot;inertie expliquée (%)&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:AZPCoude"></span>
<img src="GMQ405_files/figure-html/AZPCoude-1.png" alt="Méthode du coude reposant sur l'inertie expliquée pour l'AZP-TABU" width="75%" />
<p class="caption">
Figure 8.5: Méthode du coude reposant sur l’inertie expliquée pour l’AZP-TABU
</p>
</div>
</div>
<div id="sect0812" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Algorithme SKATER<a href="sect081.html#sect0812" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>L’algorithme SKATER (<em>Spatial ’K’luster Analysis by Tree Edge Removal</em>) <span class="citation">(<a href="#ref-assunccao2006efficient">Assunção et al. 2006</a>)</span> permet aussi de créer des régions sans discontinuité, en recourant à une technique de la théorie des graphes, soit celle de l’arbre couvrant de poids minimal (<em>minimum spanning tree</em>). Succinctement, la classification est obtenue avec les étapes suivantes :</p>
<ol style="list-style-type: decimal">
<li>Création d’un graphe de connectivité pour les polygones de la couche géographique. Dans ce graphe, les nœuds sont les centroïdes des polygones et les arêtes représentent les liaisons entre deux entités spatiales voisines.</li>
<li>Pour chaque arête, nous calculons la dissimilarité (appelée coût) des deux polygones voisins en fonction des <em>p</em> variables.</li>
<li>Pour chaque polygone, nous retenons l’arête avec le coût minimal. Autrement dit, pour chaque polygone, nous retenons son polygone voisin qui lui est le plus semblable selon les <em>p</em> variables. Nous obtenons ainsi l’arbre couvrant de poids minimal.</li>
<li>Cet arbre est ensuite élagué en supprimant les arêtes avec les plus forts coûts et en créant ainsi des sous-graphes en <em>m</em> régions sans discontinuité.</li>
</ol>
<p>Pour une description plus détaillée de l’algorithme, consultez l’article d’Assunção <em>et al.</em> <span class="citation">(<a href="#ref-assunccao2006efficient">2006</a>)</span>.</p>
<p>Le code ci-dessous permet de centrer et de réduire les quatre variables (fonction <code>scale</code>) et de construire la matrice de voisinage entre les polygones de la couche <code>LyonIris</code> (fonction <code>poly2nb</code> de <code>spdep</code>).</p>
<div class="sourceCode" id="cb569"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb569-1"><a href="sect081.html#cb569-1" tabindex="-1"></a><span class="fu">library</span>(rgdal)</span>
<span id="cb569-2"><a href="sect081.html#cb569-2" tabindex="-1"></a><span class="fu">library</span>(spdep)</span>
<span id="cb569-3"><a href="sect081.html#cb569-3" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb569-4"><a href="sect081.html#cb569-4" tabindex="-1"></a><span class="do">## Variables</span></span>
<span id="cb569-5"><a href="sect081.html#cb569-5" tabindex="-1"></a>VarsEnv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Lden&quot;</span>, <span class="st">&quot;NO2&quot;</span>, <span class="st">&quot;PM25&quot;</span>, <span class="st">&quot;VegHautPrt&quot;</span>)</span>
<span id="cb569-6"><a href="sect081.html#cb569-6" tabindex="-1"></a><span class="do">## Dataframe sans la géométrie et les quatre variables</span></span>
<span id="cb569-7"><a href="sect081.html#cb569-7" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;data/chap08/DonneesLyon.Rdata&quot;</span>)</span>
<span id="cb569-8"><a href="sect081.html#cb569-8" tabindex="-1"></a>Data <span class="ot">&lt;-</span> <span class="fu">st_drop_geometry</span>(LyonIris[VarsEnv])</span>
<span id="cb569-9"><a href="sect081.html#cb569-9" tabindex="-1"></a><span class="do">## Données centrées et réduites</span></span>
<span id="cb569-10"><a href="sect081.html#cb569-10" tabindex="-1"></a>LyonIrisZscore <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">scale</span>(Data))</span>
<span id="cb569-11"><a href="sect081.html#cb569-11" tabindex="-1"></a><span class="do">## Matrice voisinage</span></span>
<span id="cb569-12"><a href="sect081.html#cb569-12" tabindex="-1"></a>Lyon.nb <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(LyonIris)</span></code></pre></div>
<p>Calculons les coûts pour les arêtes reliant les nœuds avec la fonction <code>nbcosts</code>. Nous constatons que le polygone 1 est voisin des polygones 27, 26, 44 et 74 avec des coûts de 1,34, 1,74, 1,15 et 16,3. Par conséquent, parmi ses quatre voisins, le polygone 1 est le plus semblable au polygone 44 (coût minimal).</p>
<div class="sourceCode" id="cb570"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb570-1"><a href="sect081.html#cb570-1" tabindex="-1"></a><span class="do">## Calcul des coûts pour les arêtes</span></span>
<span id="cb570-2"><a href="sect081.html#cb570-2" tabindex="-1"></a>lcosts <span class="ot">&lt;-</span> <span class="fu">nbcosts</span>(Lyon.nb, LyonIrisZscore)</span>
<span id="cb570-3"><a href="sect081.html#cb570-3" tabindex="-1"></a><span class="fu">head</span>(Lyon.nb, <span class="at">n=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [[1]]
## [1] 27 36 44 73</code></pre>
<div class="sourceCode" id="cb572"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb572-1"><a href="sect081.html#cb572-1" tabindex="-1"></a><span class="fu">head</span>(lcosts, <span class="at">n=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [[1]]
## [1] 1.343210 1.735894 1.153787 1.632583</code></pre>
<p>À partir de ces coûts, nous pouvons trouver l’arbre couvrant de poids minimal (<em>minimum spanning tree</em>), objet dénommée ici <code>Lyon.mst</code> qui comprend trois colonnes :</p>
<ul>
<li>La première pour l’identifiant du polygone.</li>
<li>La seconde pour l’identifiant du polygone voisin.</li>
<li>La troisième pour la valeur du coût minimal (similarité selon les variables retenues).</li>
</ul>
<div class="sourceCode" id="cb574"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb574-1"><a href="sect081.html#cb574-1" tabindex="-1"></a><span class="do">## Matrice de pondération spatiale avec les coûts</span></span>
<span id="cb574-2"><a href="sect081.html#cb574-2" tabindex="-1"></a>Lyon.w <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(Lyon.nb, lcosts, <span class="at">style=</span><span class="st">&quot;B&quot;</span>)</span>
<span id="cb574-3"><a href="sect081.html#cb574-3" tabindex="-1"></a><span class="do">### Trouver l&#39;arbre couvrant de poids minimal</span></span>
<span id="cb574-4"><a href="sect081.html#cb574-4" tabindex="-1"></a>Lyon.mst <span class="ot">&lt;-</span> <span class="fu">mstree</span>(Lyon.w)</span>
<span id="cb574-5"><a href="sect081.html#cb574-5" tabindex="-1"></a><span class="fu">head</span>(Lyon.mst, <span class="at">n=</span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>##      [,1] [,2]      [,3]
## [1,]  499  478 0.5025378
## [2,]  478   46 0.4618205
## [3,]   46    7 1.3665949</code></pre>
<p>Le code ci-dessous permet de visualiser le graphe de connectivité et l’arbre couvrant de poids minimal (figure <a href="sect081.html#fig:ArbreMinimum">8.6</a>).</p>
<div class="sourceCode" id="cb576"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb576-1"><a href="sect081.html#cb576-1" tabindex="-1"></a><span class="do">## Visualisation du graphe de connectivité </span></span>
<span id="cb576-2"><a href="sect081.html#cb576-2" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(<span class="fu">st_centroid</span>(LyonIris))</span>
<span id="cb576-3"><a href="sect081.html#cb576-3" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(LyonIris), <span class="at">border=</span><span class="st">&quot;gray&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>, <span class="at">col=</span><span class="st">&quot;wheat&quot;</span>)</span>
<span id="cb576-4"><a href="sect081.html#cb576-4" tabindex="-1"></a><span class="fu">plot</span>(Lyon.nb, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>, <span class="at">lwd=</span><span class="dv">1</span>)</span>
<span id="cb576-5"><a href="sect081.html#cb576-5" tabindex="-1"></a><span class="do">## Visualisation de l&#39;arbre couvrant de poids minimal</span></span>
<span id="cb576-6"><a href="sect081.html#cb576-6" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(LyonIris), <span class="at">border=</span><span class="st">&quot;gray&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>, <span class="at">col=</span><span class="st">&quot;wheat&quot;</span>)</span>
<span id="cb576-7"><a href="sect081.html#cb576-7" tabindex="-1"></a><span class="fu">plot</span>(Lyon.mst, coords, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, <span class="at">cex.lab=</span><span class="fl">0.7</span>, <span class="at">add=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ArbreMinimum"></span>
<img src="images/Chap08/ArbreMinimum.png" alt="Graphe de connectivité et arbre couvrant de poids minimal" width="100%" />
<p class="caption">
Figure 8.6: Graphe de connectivité et arbre couvrant de poids minimal
</p>
</div>
<p>Le code ci-dessous permet de réaliser une classification SKATER avec cinq régions avec le <em>package</em> <code>spdep</code>.</p>
<div class="sourceCode" id="cb577"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb577-1"><a href="sect081.html#cb577-1" tabindex="-1"></a><span class="do">## SKATER avec le package spdep</span></span>
<span id="cb577-2"><a href="sect081.html#cb577-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123456789</span>)</span>
<span id="cb577-3"><a href="sect081.html#cb577-3" tabindex="-1"></a>skater5.spdep <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">skater</span>(<span class="at">edges =</span> Lyon.mst[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="co"># deux première colonnes de l&#39;arbre </span></span>
<span id="cb577-4"><a href="sect081.html#cb577-4" tabindex="-1"></a>                               <span class="at">data =</span> <span class="fu">data.frame</span>(LyonIrisZscore),</span>
<span id="cb577-5"><a href="sect081.html#cb577-5" tabindex="-1"></a>                               <span class="at">method =</span> <span class="st">&quot;euclidean&quot;</span>,</span>
<span id="cb577-6"><a href="sect081.html#cb577-6" tabindex="-1"></a>                               <span class="at">ncuts =</span> <span class="dv">4</span>)  <span class="co"># k-1 régions</span></span>
<span id="cb577-7"><a href="sect081.html#cb577-7" tabindex="-1"></a><span class="fu">table</span>(skater5.spdep<span class="sc">$</span>groups)</span></code></pre></div>
<pre><code>## 
##   1   2   3   4   5 
##  48 215  89  57  97</code></pre>
<p>Toutefois, il est plus simple d’utiliser la fonction <code>skater</code> de <code>rgeoda</code> qui ne nécessite pas de créer au préalable l’arbre couvrant de poids minimal.</p>
<div class="sourceCode" id="cb579"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb579-1"><a href="sect081.html#cb579-1" tabindex="-1"></a><span class="do">## SKATER avec le package rgeoda</span></span>
<span id="cb579-2"><a href="sect081.html#cb579-2" tabindex="-1"></a><span class="fu">library</span>(rgeoda)</span>
<span id="cb579-3"><a href="sect081.html#cb579-3" tabindex="-1"></a>Data <span class="ot">&lt;-</span> <span class="fu">st_drop_geometry</span>(LyonIris[VarsEnv])</span>
<span id="cb579-4"><a href="sect081.html#cb579-4" tabindex="-1"></a>queen_w <span class="ot">&lt;-</span> <span class="fu">queen_weights</span>(LyonIris)</span>
<span id="cb579-5"><a href="sect081.html#cb579-5" tabindex="-1"></a>skater5.rgeoda <span class="ot">&lt;-</span> rgeoda<span class="sc">::</span><span class="fu">skater</span>(<span class="at">k =</span> <span class="dv">5</span>,        <span class="co"># k-1 régions</span></span>
<span id="cb579-6"><a href="sect081.html#cb579-6" tabindex="-1"></a>                                 <span class="at">w =</span> queen_w,  <span class="co"># matrice de contiguité</span></span>
<span id="cb579-7"><a href="sect081.html#cb579-7" tabindex="-1"></a>                                 <span class="at">scale_method =</span> <span class="st">&quot;standardize&quot;</span>,</span>
<span id="cb579-8"><a href="sect081.html#cb579-8" tabindex="-1"></a>                                 <span class="at">df =</span> Data)    <span class="co"># dataframe</span></span>
<span id="cb579-9"><a href="sect081.html#cb579-9" tabindex="-1"></a><span class="fu">table</span>(skater5.rgeoda<span class="sc">$</span>Clusters)</span></code></pre></div>
<pre><code>## 
##   1   2   3   4   5 
## 248 125  51  48  34</code></pre>
<p>La figure <a href="sect081.html#fig:SkaterAB">8.7</a> démontre que les résultats obtenus sont légèrement différents avec les deux <code>packages</code>.</p>
<div class="sourceCode" id="cb581"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb581-1"><a href="sect081.html#cb581-1" tabindex="-1"></a>LyonIris<span class="sc">$</span>skater5spdep <span class="ot">&lt;-</span> <span class="fu">as.character</span>(skater5.spdep<span class="sc">$</span>groups)</span>
<span id="cb581-2"><a href="sect081.html#cb581-2" tabindex="-1"></a>LyonIris<span class="sc">$</span>skater5rgeoda <span class="ot">&lt;-</span> <span class="fu">as.character</span>(skater5.rgeoda<span class="sc">$</span>Clusters)</span>
<span id="cb581-3"><a href="sect081.html#cb581-3" tabindex="-1"></a></span>
<span id="cb581-4"><a href="sect081.html#cb581-4" tabindex="-1"></a>Carte.SkaterA <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span><span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb581-5"><a href="sect081.html#cb581-5" tabindex="-1"></a>              <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;skater5spdep&quot;</span>, <span class="at">palette =</span> <span class="st">&quot;Set1&quot;</span>, <span class="at">title =</span><span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb581-6"><a href="sect081.html#cb581-6" tabindex="-1"></a>              <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, </span>
<span id="cb581-7"><a href="sect081.html#cb581-7" tabindex="-1"></a>                <span class="at">main.title =</span> <span class="st">&quot;a. SKATER spdep&quot;</span>, </span>
<span id="cb581-8"><a href="sect081.html#cb581-8" tabindex="-1"></a>                <span class="at">main.title.position =</span> <span class="st">&quot;center&quot;</span>, </span>
<span id="cb581-9"><a href="sect081.html#cb581-9" tabindex="-1"></a>                <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb581-10"><a href="sect081.html#cb581-10" tabindex="-1"></a>Carte.SkaterB <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span><span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb581-11"><a href="sect081.html#cb581-11" tabindex="-1"></a>              <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;skater5rgeoda&quot;</span>, <span class="at">palette =</span> <span class="st">&quot;Set1&quot;</span>, <span class="at">title =</span><span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb581-12"><a href="sect081.html#cb581-12" tabindex="-1"></a>              <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, </span>
<span id="cb581-13"><a href="sect081.html#cb581-13" tabindex="-1"></a>                <span class="at">main.title =</span> <span class="st">&quot;b. SKATER rgeoda&quot;</span>, </span>
<span id="cb581-14"><a href="sect081.html#cb581-14" tabindex="-1"></a>                <span class="at">main.title.position =</span> <span class="st">&quot;center&quot;</span>, </span>
<span id="cb581-15"><a href="sect081.html#cb581-15" tabindex="-1"></a>                <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb581-16"><a href="sect081.html#cb581-16" tabindex="-1"></a><span class="fu">tmap_arrange</span>(Carte.SkaterA, Carte.SkaterB)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:SkaterAB"></span>
<img src="GMQ405_files/figure-html/SkaterAB-1.png" alt="Résultats de l'algorithme SKATER avec cinq classes obtenus avec les *packages* `spdep` et `rgeoda`" width="85%" />
<p class="caption">
Figure 8.7: Résultats de l’algorithme SKATER avec cinq classes obtenus avec les <em>packages</em> <code>spdep</code> et <code>rgeoda</code>
</p>
</div>
<div class="bloc_aller_loin">
<p><strong>Algorithme SKATER avec un seuil minimal pour les classes</strong></p>
<p>Dans une classification non supervisée avec une contrainte spatiale, il est possible de fixer un seuil minimal pour chaque région à partir d’une variable. L’exemple le plus classique est l’obtention de <em>p</em> régions qui doivent au moins avoir un nombre d’habitants fixé par la personne utilisatrice. Pour ce faire, nous utilisons deux paramètres de la fonction <code>spdep::skater</code>, soit <code>crit = 50000</code> pour fixer le seuil et <code>vec.crit = df$Population</code> pour indiquer le vecteur sur lequel est calculé le critère.</p>
<div class="sourceCode" id="cb582"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb582-1"><a href="sect081.html#cb582-1" tabindex="-1"></a><span class="st">`</span><span class="at">clus10_min &lt;- spdep::skater(edges = ct_mst[,1:2], </span></span>
<span id="cb582-2"><a href="sect081.html#cb582-2" tabindex="-1"></a><span class="at">                     data = dfs,               # dataframe avec les variables centrées réduites</span></span>
<span id="cb582-3"><a href="sect081.html#cb582-3" tabindex="-1"></a><span class="at">                     crit = 50000,             # seuil fixé</span></span>
<span id="cb582-4"><a href="sect081.html#cb582-4" tabindex="-1"></a><span class="at">                     vec.crit = df$Population, # variable population du dataframe</span></span>
<span id="cb582-5"><a href="sect081.html#cb582-5" tabindex="-1"></a><span class="at">                     ncuts = 4)</span></span></code></pre></div>
<p><strong>Fonction skater : différences entre les <em>packages</em> rgeoda et spdep</strong></p>
<p>La fonction <code>skater</code> de <code>rgeoda</code> a deux principaux avantages :</p>
<ol style="list-style-type: decimal">
<li>Comme décrit précédemment, l’avantage de la fonction <code>skater</code> de <code>rgeoda</code> est qu’elle ne nécessite pas de calculer au préalable l’arbre couvrant de poids minimal.</li>
<li>scale_method = c(“raw”, “standardize”, “demean”, “mad”, “range_standardize”, “range_adjust”) permet de transformer directement les variables. La méthode par défaut est la cote z (moyenne = 0 et écart-type = 1).</li>
</ol>
<p>Avec la fonction <code>skater</code> de <code>spdep</code>, vous devez préalablement transformer vos variables et construire l’arbre couvrant de poids minimal. Par contre, elle intègre de nombreux types de distance pour évaluer la dissimilarité entre les unités spatiales avec le paramètre <code>method = c("euclidean",  "maximum", "manhattan", "canberra", "binary", "minkowski",  "mahalanobis")</code> tandis que le paramètre <code>distance_method = c("euclidean", "manhattan")</code> de <code>rgeoda</code> ne comprend que deux types de distance.</p>
</div>
</div>
<div id="sect0813" class="section level3 hasAnchor" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Algorithmes REDCAP<a href="sect081.html#sect0813" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Les différentes versions de l’algorithme REDCAP (<em>Regionalization with dynamically constrained agglomerative clustering and partitioning</em>) proposé par Diansheng Guo <span class="citation">(<a href="#ref-guo2008regionalization">2008</a>)</span> sont aussi basées sur la construction d’un arbre (<em>spanning tree</em>) dont l’élagage est obtenu de cinq différentes façons :</p>
<ul>
<li>Premier ordre et saut minimal (<em>First-order and Single-linkage</em>) qui fournit un résultats identique à l’algorithme SKATER.</li>
<li>Ordre complet et saut maximal (<em>Full-order and Complete-linkage</em>).</li>
<li>Ordre complet et saut moyen (<em>Full-order and Average-linkage</em>).</li>
<li>Ordre complet et saut minimal (<em>Full-order and Single-linkage</em>).</li>
<li>Ordre complet et critère de Ward (<em>Full-order and Ward-linkage</em>).</li>
</ul>
<p>Le code ci-dessous permet de calculer les cinq versions de l’algorithmes REDCAP avec cinq régions et de comparer leurs résultats à partir du ratio (entre les variances interrégionale et totale) et du nombre d’observations par région.</p>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="sect081.html#cb583-1" tabindex="-1"></a><span class="fu">library</span>(rgeoda)</span>
<span id="cb583-2"><a href="sect081.html#cb583-2" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb583-3"><a href="sect081.html#cb583-3" tabindex="-1"></a><span class="do">## Préparation des données </span></span>
<span id="cb583-4"><a href="sect081.html#cb583-4" tabindex="-1"></a>Data <span class="ot">&lt;-</span> <span class="fu">st_drop_geometry</span>(LyonIris[VarsEnv])</span>
<span id="cb583-5"><a href="sect081.html#cb583-5" tabindex="-1"></a>queen_w <span class="ot">&lt;-</span> <span class="fu">queen_weights</span>(LyonIris)</span>
<span id="cb583-6"><a href="sect081.html#cb583-6" tabindex="-1"></a><span class="do">## Algorithmes REDCAP</span></span>
<span id="cb583-7"><a href="sect081.html#cb583-7" tabindex="-1"></a>redcap5.A <span class="ot">&lt;-</span> <span class="fu">redcap</span>(<span class="at">k =</span> <span class="dv">5</span>, <span class="at">w =</span> queen_w, <span class="at">scale_method =</span> <span class="st">&quot;standardize&quot;</span>, <span class="at">df =</span> Data,</span>
<span id="cb583-8"><a href="sect081.html#cb583-8" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">&quot;firstorder-singlelinkage&quot;</span>)</span>
<span id="cb583-9"><a href="sect081.html#cb583-9" tabindex="-1"></a>redcap5.B <span class="ot">&lt;-</span> <span class="fu">redcap</span>(<span class="at">k =</span> <span class="dv">5</span>, <span class="at">w =</span> queen_w, <span class="at">scale_method =</span> <span class="st">&quot;standardize&quot;</span>, <span class="at">df =</span> Data,</span>
<span id="cb583-10"><a href="sect081.html#cb583-10" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">&quot;fullorder-completelinkage&quot;</span>)</span>
<span id="cb583-11"><a href="sect081.html#cb583-11" tabindex="-1"></a>redcap5.C <span class="ot">&lt;-</span> <span class="fu">redcap</span>(<span class="at">k =</span> <span class="dv">5</span>, <span class="at">w =</span> queen_w, <span class="at">scale_method =</span> <span class="st">&quot;standardize&quot;</span>, <span class="at">df =</span> Data,</span>
<span id="cb583-12"><a href="sect081.html#cb583-12" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">&quot;fullorder-averagelinkage&quot;</span>)</span>
<span id="cb583-13"><a href="sect081.html#cb583-13" tabindex="-1"></a>redcap5.D <span class="ot">&lt;-</span> <span class="fu">redcap</span>(<span class="at">k =</span> <span class="dv">5</span>, <span class="at">w =</span> queen_w, <span class="at">scale_method =</span> <span class="st">&quot;standardize&quot;</span>, <span class="at">df =</span> Data,</span>
<span id="cb583-14"><a href="sect081.html#cb583-14" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">&quot;fullorder-singlelinkage&quot;</span>)</span>
<span id="cb583-15"><a href="sect081.html#cb583-15" tabindex="-1"></a>redcap5.E <span class="ot">&lt;-</span> <span class="fu">redcap</span>(<span class="at">k =</span> <span class="dv">5</span>, <span class="at">w =</span> queen_w, <span class="at">scale_method =</span> <span class="st">&quot;standardize&quot;</span>, <span class="at">df =</span> Data,</span>
<span id="cb583-16"><a href="sect081.html#cb583-16" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">&quot;fullorder-wardlinkage&quot;</span>)</span>
<span id="cb583-17"><a href="sect081.html#cb583-17" tabindex="-1"></a><span class="do">## Comparaison des résultats</span></span>
<span id="cb583-18"><a href="sect081.html#cb583-18" tabindex="-1"></a>Ratios <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Methode =</span> <span class="fu">c</span>(<span class="st">&quot;firstorder-singlelinkage&quot;</span>, </span>
<span id="cb583-19"><a href="sect081.html#cb583-19" tabindex="-1"></a>                                  <span class="st">&quot;fullorder-completelinkage&quot;</span>, </span>
<span id="cb583-20"><a href="sect081.html#cb583-20" tabindex="-1"></a>                                  <span class="st">&quot;fullorder-averagelinkage&quot;</span>,</span>
<span id="cb583-21"><a href="sect081.html#cb583-21" tabindex="-1"></a>                                  <span class="st">&quot;fullorder-singlelinkage&quot;</span>, </span>
<span id="cb583-22"><a href="sect081.html#cb583-22" tabindex="-1"></a>                                  <span class="st">&quot;fullorder-wardlinkage&quot;</span>),</span>
<span id="cb583-23"><a href="sect081.html#cb583-23" tabindex="-1"></a>                      <span class="at">ratio =</span> <span class="fu">c</span>(redcap5.A<span class="sc">$</span><span class="st">`</span><span class="at">The ratio of between to total sum of squares</span><span class="st">`</span>,</span>
<span id="cb583-24"><a href="sect081.html#cb583-24" tabindex="-1"></a>                                redcap5.B<span class="sc">$</span><span class="st">`</span><span class="at">The ratio of between to total sum of squares</span><span class="st">`</span>,</span>
<span id="cb583-25"><a href="sect081.html#cb583-25" tabindex="-1"></a>                                redcap5.C<span class="sc">$</span><span class="st">`</span><span class="at">The ratio of between to total sum of squares</span><span class="st">`</span>,</span>
<span id="cb583-26"><a href="sect081.html#cb583-26" tabindex="-1"></a>                                redcap5.D<span class="sc">$</span><span class="st">`</span><span class="at">The ratio of between to total sum of squares</span><span class="st">`</span>,</span>
<span id="cb583-27"><a href="sect081.html#cb583-27" tabindex="-1"></a>                                redcap5.E<span class="sc">$</span><span class="st">`</span><span class="at">The ratio of between to total sum of squares</span><span class="st">`</span>)</span>
<span id="cb583-28"><a href="sect081.html#cb583-28" tabindex="-1"></a>                      )</span>
<span id="cb583-29"><a href="sect081.html#cb583-29" tabindex="-1"></a>Nobs <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">rbind</span>(<span class="fu">table</span>(redcap5.A<span class="sc">$</span>Clusters), </span>
<span id="cb583-30"><a href="sect081.html#cb583-30" tabindex="-1"></a>              <span class="fu">table</span>(redcap5.B<span class="sc">$</span>Clusters), </span>
<span id="cb583-31"><a href="sect081.html#cb583-31" tabindex="-1"></a>              <span class="fu">table</span>(redcap5.C<span class="sc">$</span>Clusters), </span>
<span id="cb583-32"><a href="sect081.html#cb583-32" tabindex="-1"></a>              <span class="fu">table</span>(redcap5.D<span class="sc">$</span>Clusters), </span>
<span id="cb583-33"><a href="sect081.html#cb583-33" tabindex="-1"></a>              <span class="fu">table</span>(redcap5.E<span class="sc">$</span>Clusters))</span>
<span id="cb583-34"><a href="sect081.html#cb583-34" tabindex="-1"></a>              )</span>
<span id="cb583-35"><a href="sect081.html#cb583-35" tabindex="-1"></a><span class="fu">names</span>(Nobs) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;C1&quot;</span>, <span class="st">&quot;C2&quot;</span>, <span class="st">&quot;C3&quot;</span>, <span class="st">&quot;C4&quot;</span>, <span class="st">&quot;C5&quot;</span>)</span>
<span id="cb583-36"><a href="sect081.html#cb583-36" tabindex="-1"></a>Ratios <span class="ot">&lt;-</span> <span class="fu">cbind</span>(Ratios, Nobs)</span>
<span id="cb583-37"><a href="sect081.html#cb583-37" tabindex="-1"></a>Ratios</span></code></pre></div>
<pre><code>##                     Methode     ratio  C1  C2  C3 C4 C5
## 1  firstorder-singlelinkage 0.4081577 248 125  51 48 34
## 2 fullorder-completelinkage 0.4728026 173 156 115 47 15
## 3  fullorder-averagelinkage 0.4993184 148 141 106 63 48
## 4   fullorder-singlelinkage 0.3976055 227 102  73 53 51
## 5     fullorder-wardlinkage 0.5185455 166 134 120 51 35</code></pre>
<p>À la lecture des valeurs du ratio ci-dessous, la meilleure classification serait celle obtenue avec un ordre complet et le critère de Ward. Cartographions les résultats des quatre versions de l’algorithme RECAP avec un ordre complet (figure <a href="sect081.html#fig:CartoREDCAP">8.8</a>).</p>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="sect081.html#cb585-1" tabindex="-1"></a><span class="do">## Ajout des champs dans la couche</span></span>
<span id="cb585-2"><a href="sect081.html#cb585-2" tabindex="-1"></a>LyonIris<span class="sc">$</span>RC5.FOcompletelinkage  <span class="ot">&lt;-</span> <span class="fu">as.character</span>(redcap5.B<span class="sc">$</span>Clusters)</span>
<span id="cb585-3"><a href="sect081.html#cb585-3" tabindex="-1"></a>LyonIris<span class="sc">$</span>RC5.FOaveragelinkage   <span class="ot">&lt;-</span> <span class="fu">as.character</span>(redcap5.C<span class="sc">$</span>Clusters)</span>
<span id="cb585-4"><a href="sect081.html#cb585-4" tabindex="-1"></a>LyonIris<span class="sc">$</span>RC5.FOsinglelinkage    <span class="ot">&lt;-</span> <span class="fu">as.character</span>(redcap5.D<span class="sc">$</span>Clusters)</span>
<span id="cb585-5"><a href="sect081.html#cb585-5" tabindex="-1"></a>LyonIris<span class="sc">$</span>RC5.FOwardlinkage      <span class="ot">&lt;-</span> <span class="fu">as.character</span>(redcap5.E<span class="sc">$</span>Clusters)</span>
<span id="cb585-6"><a href="sect081.html#cb585-6" tabindex="-1"></a><span class="do">## Cartographie des résultats</span></span>
<span id="cb585-7"><a href="sect081.html#cb585-7" tabindex="-1"></a>Carte.RCb <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span><span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb585-8"><a href="sect081.html#cb585-8" tabindex="-1"></a>              <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;RC5.FOcompletelinkage&quot;</span>, <span class="at">palette =</span> <span class="st">&quot;Set1&quot;</span>, <span class="at">title =</span><span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb585-9"><a href="sect081.html#cb585-9" tabindex="-1"></a>              <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, </span>
<span id="cb585-10"><a href="sect081.html#cb585-10" tabindex="-1"></a>                <span class="at">main.title =</span> <span class="st">&quot;a. Saut maximal&quot;</span>, </span>
<span id="cb585-11"><a href="sect081.html#cb585-11" tabindex="-1"></a>                <span class="at">main.title.position =</span> <span class="st">&quot;center&quot;</span>, </span>
<span id="cb585-12"><a href="sect081.html#cb585-12" tabindex="-1"></a>                <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb585-13"><a href="sect081.html#cb585-13" tabindex="-1"></a>Carte.RCc <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span><span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb585-14"><a href="sect081.html#cb585-14" tabindex="-1"></a>              <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;RC5.FOaveragelinkage&quot;</span>, <span class="at">palette =</span> <span class="st">&quot;Set1&quot;</span>, <span class="at">title =</span><span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb585-15"><a href="sect081.html#cb585-15" tabindex="-1"></a>              <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, </span>
<span id="cb585-16"><a href="sect081.html#cb585-16" tabindex="-1"></a>                <span class="at">main.title =</span> <span class="st">&quot;b. Saut moyen&quot;</span>, </span>
<span id="cb585-17"><a href="sect081.html#cb585-17" tabindex="-1"></a>                <span class="at">main.title.position =</span> <span class="st">&quot;center&quot;</span>, </span>
<span id="cb585-18"><a href="sect081.html#cb585-18" tabindex="-1"></a>                <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb585-19"><a href="sect081.html#cb585-19" tabindex="-1"></a>Carte.RCd <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span><span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb585-20"><a href="sect081.html#cb585-20" tabindex="-1"></a>              <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;RC5.FOsinglelinkage&quot;</span>, <span class="at">palette =</span> <span class="st">&quot;Set1&quot;</span>, <span class="at">title =</span><span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb585-21"><a href="sect081.html#cb585-21" tabindex="-1"></a>              <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, </span>
<span id="cb585-22"><a href="sect081.html#cb585-22" tabindex="-1"></a>                <span class="at">main.title =</span> <span class="st">&quot;c. Saut minimal&quot;</span>, </span>
<span id="cb585-23"><a href="sect081.html#cb585-23" tabindex="-1"></a>                <span class="at">main.title.position =</span> <span class="st">&quot;center&quot;</span>, </span>
<span id="cb585-24"><a href="sect081.html#cb585-24" tabindex="-1"></a>                <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb585-25"><a href="sect081.html#cb585-25" tabindex="-1"></a>Carte.RCe <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span><span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb585-26"><a href="sect081.html#cb585-26" tabindex="-1"></a>              <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;RC5.FOwardlinkage&quot;</span>, <span class="at">palette =</span> <span class="st">&quot;Set1&quot;</span>, <span class="at">title =</span><span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb585-27"><a href="sect081.html#cb585-27" tabindex="-1"></a>              <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, </span>
<span id="cb585-28"><a href="sect081.html#cb585-28" tabindex="-1"></a>                <span class="at">main.title =</span> <span class="st">&quot;d. Critère de Ward&quot;</span>, </span>
<span id="cb585-29"><a href="sect081.html#cb585-29" tabindex="-1"></a>                <span class="at">main.title.position =</span> <span class="st">&quot;center&quot;</span>, </span>
<span id="cb585-30"><a href="sect081.html#cb585-30" tabindex="-1"></a>                <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb585-31"><a href="sect081.html#cb585-31" tabindex="-1"></a><span class="fu">tmap_arrange</span>(Carte.RCb, Carte.RCc, Carte.RCd, Carte.RCe, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:CartoREDCAP"></span>
<img src="GMQ405_files/figure-html/CartoREDCAP-1.png" alt="Regroupements des 505 IRIS en cinq régions selon les quatre versions de l'algorithme REDCAP avec un lien complet" width="100%" />
<p class="caption">
Figure 8.8: Regroupements des 505 IRIS en cinq régions selon les quatre versions de l’algorithme REDCAP avec un lien complet
</p>
</div>
</div>
<div id="sect0814" class="section level3 hasAnchor" number="8.1.4">
<h3><span class="header-section-number">8.1.4</span> Algorithme du <em>max-p-regions problem</em><a href="sect081.html#sect0814" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cet algorithme, proposé par Duque <em>et al.</em> <span class="citation">(<a href="#ref-duque2012max">2012</a>)</span>, n’est pas abordé dans le cours. Il peut être calculé avec trois fonctions du package <code>rgeoda</code>, soit <code>maxp_greedy</code>, <code>maxp_sa</code> et <code>maxp_tabu</code>.</p>
</div>
</div>
<h3>Références</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-RBoldAir" class="csl-entry">
Apparicio, Philippe et Jérémy Gelb. 2022. <em>Méthodes quantitatives en sciences sociales : un grand bol d’R</em>. FabriqueREL, Licence CC BY-SA. <a href="https://laeq.github.io/LivreMethoQuantBolR/">https://laeq.github.io/LivreMethoQuantBolR/</a>.
</div>
<div id="ref-assunccao2006efficient" class="csl-entry">
Assunção, Renato M, Marcos Corrêa Neves, Gilberto Câmara et Corina da Costa Freitas. 2006. <span>« Efficient regionalization techniques for socio-economic geographical units using minimum spanning trees. »</span> <em>International Journal of Geographical Information Science</em> 20 (7): 797‑811. <a href="https://doi.org/10.1080/13658810600665111">https://doi.org/10.1080/13658810600665111</a>.
</div>
<div id="ref-duque2012max" class="csl-entry">
Duque, Juan C, Luc Anselin et Sergio J Rey. 2012. <span>« The max-p-regions problem. »</span> <em>Journal of Regional Science</em> 52 (3): 397‑419. <a href="https://doi.org/10.1111/j.1467-9787.2011.00743.x">https://doi.org/10.1111/j.1467-9787.2011.00743.x</a>.
</div>
<div id="ref-ClassificationFloue" class="csl-entry">
Gelb, Jérémy et Philippe Apparicio. 2021. <span>« Apport de la classification floue c-means spatiale en géographie: essai de taxinomie socio-résidentielle et environnementale à Lyon. »</span> <em>Cybergeo: European Journal of Geography</em>. <a href="https://doi.org/10.4000/cybergeo.36414">https://doi.org/10.4000/cybergeo.36414</a>.
</div>
<div id="ref-guo2008regionalization" class="csl-entry">
Guo, Diansheng. 2008. <span>« Regionalization with dynamically constrained agglomerative clustering and partitioning (REDCAP). »</span> <em>International Journal of Geographical Information Science</em> 22 (7): 801‑823. <a href="https://doi.org/10.1080/13658810600665111">https://doi.org/10.1080/13658810600665111</a>.
</div>
<div id="ref-packagergeoda" class="csl-entry">
Li, Xun et Luc Anselin. 2023. <em>rgeoda: R Library for Spatial Data Analysis</em>. s.n. <a href="https://CRAN.R-project.org/package=rgeoda">https://CRAN.R-project.org/package=rgeoda</a>.
</div>
<div id="ref-openshaw1977geographical" class="csl-entry">
Openshaw, Stan. 1977. <span>« A geographical solution to scale and aggregation problems in region-building, partitioning and spatial modelling. »</span> <em>Transactions of the institute of british geographers</em>: 459‑472. <a href="https://doi.org/10.2307/622300">https://doi.org/10.2307/622300</a>.
</div>
<div id="ref-openshaw1995algorithms" class="csl-entry">
Openshaw, Stan et Liang Rao. 1995. <span>« Algorithms for reengineering 1991 Census geography. »</span> <em>Environment and planning A</em> 27 (3): 425‑446. <a href="https://doi.org/10.1068/a270425">https://doi.org/10.1068/a270425</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap08.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sect082.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["GMQ405.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
