<!DOCTYPE html>
<html lang="fr" xml:lang="fr">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7.3 Régression géographiquement pondérée | Notes de cours GMQ405 : Modélisation et analyse spatiale</title>
  <meta name="description" content="Mettre le description du cours." />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="7.3 Régression géographiquement pondérée | Notes de cours GMQ405 : Modélisation et analyse spatiale" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/introduction/ImageCouverture.png" />
  <meta property="og:description" content="Mettre le description du cours." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7.3 Régression géographiquement pondérée | Notes de cours GMQ405 : Modélisation et analyse spatiale" />
  
  <meta name="twitter:description" content="Mettre le description du cours." />
  <meta name="twitter:image" content="/images/introduction/ImageCouverture.png" />

<meta name="author" content="Philippe Apparicio, département de géomatique appliquée, Université de Sherbrooke" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sect072.html"/>
<link rel="next" href="sect074.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.1.2/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.1.2/leaflet-providers-plugin.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/quizlib.min.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">GMQ405 : modélisation et analyse spatiale</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenue</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html"><i class="fa fa-check"></i>Préface</a>
<ul>
<li class="chapter" data-level="" data-path="sect001.html"><a href="sect001.html"><i class="fa fa-check"></i>Un manuel sous la forme d’une ressource éducative libre</a></li>
<li class="chapter" data-level="" data-path="sect002.html"><a href="sect002.html"><i class="fa fa-check"></i>Comment lire ce manuel?</a></li>
<li class="chapter" data-level="" data-path="sect003.html"><a href="sect003.html"><i class="fa fa-check"></i>Comment utiliser les données du livre pour reproduire les exemples?</a></li>
<li class="chapter" data-level="" data-path="sect004.html"><a href="sect004.html"><i class="fa fa-check"></i>Structure du livre</a></li>
<li class="chapter" data-level="" data-path="sect005.html"><a href="sect005.html"><i class="fa fa-check"></i>Pourquoi faut-il programmer en géomatique appliquée et utiliser R?</a></li>
<li class="chapter" data-level="" data-path="sect006.html"><a href="sect006.html"><i class="fa fa-check"></i>Remerciements</a></li>
</ul></li>
<li class="part"><span><b>I Découverte de R</b></span></li>
<li class="chapter" data-level="1" data-path="chap01.html"><a href="chap01.html"><i class="fa fa-check"></i><b>1</b> Manipulation des données spatiales dans R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="sect011.html"><a href="sect011.html"><i class="fa fa-check"></i><b>1.1</b> Importation de données géographiques</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="sect011.html"><a href="sect011.html#sect0111"><i class="fa fa-check"></i><b>1.1.1</b> Importation de données vectorielles</a></li>
<li class="chapter" data-level="1.1.2" data-path="sect011.html"><a href="sect011.html#sect0112"><i class="fa fa-check"></i><b>1.1.2</b> Importation de données <em>raster</em></a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="sect012.html"><a href="sect012.html"><i class="fa fa-check"></i><b>1.2</b> Manipulation de données vectorielles</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="sect012.html"><a href="sect012.html#sect0121"><i class="fa fa-check"></i><b>1.2.1</b> Fonctions relatives à la projection cartographique</a></li>
<li class="chapter" data-level="1.2.2" data-path="sect012.html"><a href="sect012.html#sect0122"><i class="fa fa-check"></i><b>1.2.2</b> Fonctions d’opérations géométriques sur une couche</a></li>
<li class="chapter" data-level="1.2.3" data-path="sect012.html"><a href="sect012.html#sect01213"><i class="fa fa-check"></i><b>1.2.3</b> Fonctions d’opérations géométriques entre deux couches</a></li>
<li class="chapter" data-level="1.2.4" data-path="sect012.html"><a href="sect012.html#sect0124"><i class="fa fa-check"></i><b>1.2.4</b> Fonctions de mesures géométriques et de récupération des coordonnées géographiques</a></li>
<li class="chapter" data-level="1.2.5" data-path="sect012.html"><a href="sect012.html#sect0125"><i class="fa fa-check"></i><b>1.2.5</b> Jointures spatiales</a></li>
<li class="chapter" data-level="1.2.6" data-path="sect012.html"><a href="sect012.html#sect0126"><i class="fa fa-check"></i><b>1.2.6</b> Requêtes spatiales</a></li>
<li class="chapter" data-level="1.2.7" data-path="sect012.html"><a href="sect012.html#sect0127"><i class="fa fa-check"></i><b>1.2.7</b> Manipulation des données attributaires</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="sect013.html"><a href="sect013.html"><i class="fa fa-check"></i><b>1.3</b> Manipulation de données matricielles (<em>raster</em>)</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="sect013.html"><a href="sect013.html#sect0131"><i class="fa fa-check"></i><b>1.3.1</b> Mosaïquage et découpage d’images</a></li>
<li class="chapter" data-level="1.3.2" data-path="sect013.html"><a href="sect013.html#sect0132"><i class="fa fa-check"></i><b>1.3.2</b> Requêtes attributaires sur des images</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="sect014.html"><a href="sect014.html"><i class="fa fa-check"></i><b>1.4</b> Exportation de données spatiales de R vers des formats géographiques</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="sect014.html"><a href="sect014.html#sect0141"><i class="fa fa-check"></i><b>1.4.1</b> Exportation de données vectorielles <code>sf</code></a></li>
<li class="chapter" data-level="1.4.2" data-path="sect014.html"><a href="sect014.html#sect0142"><i class="fa fa-check"></i><b>1.4.2</b> Exportation de données <em>raster</em></a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="sect015.html"><a href="sect015.html"><i class="fa fa-check"></i><b>1.5</b> Cartographie avec R</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="sect015.html"><a href="sect015.html#sect0151"><i class="fa fa-check"></i><b>1.5.1</b> Manipulation des couches géométriques</a></li>
<li class="chapter" data-level="1.5.2" data-path="sect015.html"><a href="sect015.html#sect0152"><i class="fa fa-check"></i><b>1.5.2</b> Cartes interactives</a></li>
<li class="chapter" data-level="1.5.3" data-path="sect015.html"><a href="sect015.html#sect0153"><i class="fa fa-check"></i><b>1.5.3</b> Mise en page d’une carte</a></li>
<li class="chapter" data-level="1.5.4" data-path="sect015.html"><a href="sect015.html#sect0154"><i class="fa fa-check"></i><b>1.5.4</b> Exportation d’une carte</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="sect016.html"><a href="sect016.html"><i class="fa fa-check"></i><b>1.6</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="1.7" data-path="sect017.html"><a href="sect017.html"><i class="fa fa-check"></i><b>1.7</b> Exercices de révision</a></li>
</ul></li>
<li class="part"><span><b>II Autocorrélation spatiale</b></span></li>
<li class="chapter" data-level="2" data-path="chap02.html"><a href="chap02.html"><i class="fa fa-check"></i><b>2</b> Autocorrélation spatiale</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sect021.html"><a href="sect021.html"><i class="fa fa-check"></i><b>2.1</b> Notion d’autocorrélation spatiale</a></li>
<li class="chapter" data-level="2.2" data-path="sect022.html"><a href="sect022.html"><i class="fa fa-check"></i><b>2.2</b> Matrices de pondération spatiale</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="sect022.html"><a href="sect022.html#sect0221"><i class="fa fa-check"></i><b>2.2.1</b> Matrices de contiguïté</a></li>
<li class="chapter" data-level="2.2.2" data-path="sect022.html"><a href="sect022.html#sect0222"><i class="fa fa-check"></i><b>2.2.2</b> Matrices de proximité spatiale</a></li>
<li class="chapter" data-level="2.2.3" data-path="sect022.html"><a href="sect022.html#sect0223"><i class="fa fa-check"></i><b>2.2.3</b> Standardisation des matrices de pondération spatiale en ligne</a></li>
<li class="chapter" data-level="2.2.4" data-path="sect022.html"><a href="sect022.html#sect0224"><i class="fa fa-check"></i><b>2.2.4</b> Construction de matrices de pondération spatiale dans R</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="sect023.html"><a href="sect023.html"><i class="fa fa-check"></i><b>2.3</b> Autocorrélation spatiale globale</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="sect023.html"><a href="sect023.html#sect0231"><i class="fa fa-check"></i><b>2.3.1</b> Statistique du <em>I</em> de Moran</a></li>
<li class="chapter" data-level="2.3.2" data-path="sect023.html"><a href="sect023.html#sect0232"><i class="fa fa-check"></i><b>2.3.2</b> Statistiques de comptage de jointure (<em>Join Count Statistics</em>)</a></li>
<li class="chapter" data-level="2.3.3" data-path="sect023.html"><a href="sect023.html#sect0233"><i class="fa fa-check"></i><b>2.3.3</b> Indice de Lee : autocorrélation spatiale dans un contexte bivariée</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="sect024.html"><a href="sect024.html"><i class="fa fa-check"></i><b>2.4</b> Autocorrélation spatiale locale</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="sect024.html"><a href="sect024.html#sect0241"><i class="fa fa-check"></i><b>2.4.1</b> Statistiques locales de Getis et Ord : repérer les points chauds et froids pour une variable continue</a></li>
<li class="chapter" data-level="2.4.2" data-path="sect024.html"><a href="sect024.html#sect0242"><i class="fa fa-check"></i><b>2.4.2</b> Version locale du <em>I</em> de Moran</a></li>
<li class="chapter" data-level="2.4.3" data-path="sect024.html"><a href="sect024.html#sect0243"><i class="fa fa-check"></i><b>2.4.3</b> Typologie basée sur le diagramme de Moran</a></li>
<li class="chapter" data-level="2.4.4" data-path="sect024.html"><a href="sect024.html#sect0244"><i class="fa fa-check"></i><b>2.4.4</b> Version locale des statistiques de comptage de jointure (<em>Join Count Statistics</em>)</a></li>
<li class="chapter" data-level="2.4.5" data-path="sect024.html"><a href="sect024.html#sect0245"><i class="fa fa-check"></i><b>2.4.5</b> Version locale de l’indice de Lee</a></li>
<li class="chapter" data-level="2.4.6" data-path="sect024.html"><a href="sect024.html#sect0246"><i class="fa fa-check"></i><b>2.4.6</b> Typologie basée sur le diagramme de Moran dans un contexte bivarié</a></li>
<li class="chapter" data-level="2.4.7" data-path="sect024.html"><a href="sect024.html#sect0247"><i class="fa fa-check"></i><b>2.4.7</b> Autocorrélation locale pour une variable qualitative (catégorielle) : l’indicateur ELSA</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="sect025.html"><a href="sect025.html"><i class="fa fa-check"></i><b>2.5</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="2.6" data-path="sect026.html"><a href="sect026.html"><i class="fa fa-check"></i><b>2.6</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap03.html"><a href="chap03.html"><i class="fa fa-check"></i><b>3</b> Méthodes de répartition ponctuelle</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sect031.html"><a href="sect031.html"><i class="fa fa-check"></i><b>3.1</b> Fréquence et densité des points dans l’espace d’étude</a></li>
<li class="chapter" data-level="3.2" data-path="sect032.html"><a href="sect032.html"><i class="fa fa-check"></i><b>3.2</b> Analyse centrographique</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sect032.html"><a href="sect032.html#sect0311"><i class="fa fa-check"></i><b>3.2.1</b> Paramètres de tendance centrale d’un semis de points</a></li>
<li class="chapter" data-level="3.2.2" data-path="sect032.html"><a href="sect032.html#sect0312"><i class="fa fa-check"></i><b>3.2.2</b> Paramètres de dispersion d’un semis de points</a></li>
<li class="chapter" data-level="3.2.3" data-path="sect032.html"><a href="sect032.html#sect0313"><i class="fa fa-check"></i><b>3.2.3</b> Mise en œuvre de l’analyse centrographique dans R</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sect033.html"><a href="sect033.html"><i class="fa fa-check"></i><b>3.3</b> Forme d’un semis de points</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="sect033.html"><a href="sect033.html#sect0331"><i class="fa fa-check"></i><b>3.3.1</b> Méthode du plus proche voisin</a></li>
<li class="chapter" data-level="3.3.2" data-path="sect033.html"><a href="sect033.html#sect0332"><i class="fa fa-check"></i><b>3.3.2</b> Méthode des quadrats</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="sect034.html"><a href="sect034.html"><i class="fa fa-check"></i><b>3.4</b> Identification des agrégats spatiaux</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="sect034.html"><a href="sect034.html#sect0341"><i class="fa fa-check"></i><b>3.4.1</b> Cartographie de la densité dans une maille irrégulière</a></li>
<li class="chapter" data-level="3.4.2" data-path="sect034.html"><a href="sect034.html#sect0342"><i class="fa fa-check"></i><b>3.4.2</b> Cartographie de la densité dans une maille régulière</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="sect035.html"><a href="sect035.html"><i class="fa fa-check"></i><b>3.5</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="3.6" data-path="sect036.html"><a href="sect036.html"><i class="fa fa-check"></i><b>3.6</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap04.html"><a href="chap04.html"><i class="fa fa-check"></i><b>4</b> Méthodes de détection d’agrégats spatiaux et spatio-temporels</a>
<ul>
<li class="chapter" data-level="4.1" data-path="sect041.html"><a href="sect041.html"><i class="fa fa-check"></i><b>4.1</b> Agrégats d’entités spatiales ponctuelles</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="sect041.html"><a href="sect041.html#sect0411"><i class="fa fa-check"></i><b>4.1.1</b> DBSCAN : agrégats spatiaux</a></li>
<li class="chapter" data-level="4.1.2" data-path="sect041.html"><a href="sect041.html#sect0412"><i class="fa fa-check"></i><b>4.1.2</b> ST-DBSCAN : agrégats spatio-temporels</a></li>
<li class="chapter" data-level="4.1.3" data-path="sect041.html"><a href="sect041.html#sect0414"><i class="fa fa-check"></i><b>4.1.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="sect042.html"><a href="sect042.html"><i class="fa fa-check"></i><b>4.2</b> Méthodes de balayage de Kulldorff</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="sect042.html"><a href="sect042.html#sect0421"><i class="fa fa-check"></i><b>4.2.1</b> Objectifs de la méthode, types d’analyses, de modèles et d’agrégats</a></li>
<li class="chapter" data-level="4.2.2" data-path="sect042.html"><a href="sect042.html#sect0422"><i class="fa fa-check"></i><b>4.2.2</b> Principes de base de la méthode</a></li>
<li class="chapter" data-level="4.2.3" data-path="sect042.html"><a href="sect042.html#sect043"><i class="fa fa-check"></i><b>4.2.3</b> Mise en oeuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="sect044.html"><a href="sect044.html"><i class="fa fa-check"></i><b>4.3</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="4.4" data-path="sect045.html"><a href="sect045.html"><i class="fa fa-check"></i><b>4.4</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap05.html"><a href="chap05.html"><i class="fa fa-check"></i><b>5</b> Mesures d’accessibilité spatiale selon les différents de modes de transport</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sect051.html"><a href="sect051.html"><i class="fa fa-check"></i><b>5.1</b> Notions relatives à l’analyse de réseau</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="sect051.html"><a href="sect051.html#sect0511"><i class="fa fa-check"></i><b>5.1.1</b> Définition d’un réseau</a></li>
<li class="chapter" data-level="5.1.2" data-path="sect051.html"><a href="sect051.html#sect0512"><i class="fa fa-check"></i><b>5.1.2</b> Principaux problèmes résolus en analyse de réseau</a></li>
<li class="chapter" data-level="5.1.3" data-path="sect051.html"><a href="sect051.html#sect0513"><i class="fa fa-check"></i><b>5.1.3</b> Analyse de réseau et entités polygonales</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="sect052.html"><a href="sect052.html"><i class="fa fa-check"></i><b>5.2</b> Construction d’un réseau avec R5R</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="sect052.html"><a href="sect052.html#sect0521"><i class="fa fa-check"></i><b>5.2.1</b> Extraction des données spatiales pour R5R</a></li>
<li class="chapter" data-level="5.2.2" data-path="sect052.html"><a href="sect052.html#sect0522"><i class="fa fa-check"></i><b>5.2.2</b> Construction du réseau avec R5R</a></li>
<li class="chapter" data-level="5.2.3" data-path="sect052.html"><a href="sect052.html#sect0523"><i class="fa fa-check"></i><b>5.2.3</b> Calcul d’itinéraires avec R5R selon le mode de transport</a></li>
<li class="chapter" data-level="5.2.4" data-path="sect052.html"><a href="sect052.html#sect0524"><i class="fa fa-check"></i><b>5.2.4</b> Calcul de matrices OD selon différents modes de transport</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="sect053.html"><a href="sect053.html"><i class="fa fa-check"></i><b>5.3</b> Mesures d’accessibilité</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="sect053.html"><a href="sect053.html#sect0531"><i class="fa fa-check"></i><b>5.3.1</b> Notion d’accessibilité</a></li>
<li class="chapter" data-level="5.3.2" data-path="sect053.html"><a href="sect053.html#sect0532"><i class="fa fa-check"></i><b>5.3.2</b> Accessibilité spatiale potentielle</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="sect054.html"><a href="sect054.html"><i class="fa fa-check"></i><b>5.4</b> Mesures d’accessibilité spatiale potentielle dans R</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="sect054.html"><a href="sect054.html#sect0541"><i class="fa fa-check"></i><b>5.4.1</b> Accessibilité spatiale potentielle aux supermarchés</a></li>
<li class="chapter" data-level="5.4.2" data-path="sect054.html"><a href="sect054.html#sect0542"><i class="fa fa-check"></i><b>5.4.2</b> Accessibilité spatiale potentielle aux patinoires extérieures</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="sect055.html"><a href="sect055.html"><i class="fa fa-check"></i><b>5.5</b> Quiz de révision du chapitre</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap06.html"><a href="chap06.html"><i class="fa fa-check"></i><b>6</b> Analyses d’évènements localisés sur un réseau</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sect061.html"><a href="sect061.html"><i class="fa fa-check"></i><b>6.1</b> Cartographie de la densité d’évènements sur un réseau</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="sect061.html"><a href="sect061.html#sect0611"><i class="fa fa-check"></i><b>6.1.1</b> Explication du NKDE et du TNKDE</a></li>
<li class="chapter" data-level="6.1.2" data-path="sect061.html"><a href="sect061.html#sect0612"><i class="fa fa-check"></i><b>6.1.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sect062.html"><a href="sect062.html"><i class="fa fa-check"></i><b>6.2</b> Mesure d’autocorrélation spatiale sur un réseau</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="sect062.html"><a href="sect062.html#sect0621"><i class="fa fa-check"></i><b>6.2.1</b> Getis et Ord</a></li>
<li class="chapter" data-level="6.2.2" data-path="sect062.html"><a href="sect062.html#sect0622"><i class="fa fa-check"></i><b>6.2.2</b> Typologie basée sur le diagramme de Moran</a></li>
<li class="chapter" data-level="6.2.3" data-path="sect062.html"><a href="sect062.html#sect0623"><i class="fa fa-check"></i><b>6.2.3</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sect063.html"><a href="sect063.html"><i class="fa fa-check"></i><b>6.3</b> DBSCAN sur un réseau</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="sect063.html"><a href="sect063.html#sect0631"><i class="fa fa-check"></i><b>6.3.1</b> Explication du NKDE et du TNKDE</a></li>
<li class="chapter" data-level="6.3.2" data-path="sect063.html"><a href="sect063.html#sect0632"><i class="fa fa-check"></i><b>6.3.2</b> Mise en œuvre dans R</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="sect064.html"><a href="sect064.html"><i class="fa fa-check"></i><b>6.4</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="6.5" data-path="sect065.html"><a href="sect065.html"><i class="fa fa-check"></i><b>6.5</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap07.html"><a href="chap07.html"><i class="fa fa-check"></i><b>7</b> Introduction aux modèles de régression spatiale</a>
<ul>
<li class="chapter" data-level="7.1" data-path="sect071.html"><a href="sect071.html"><i class="fa fa-check"></i><b>7.1</b> Modèles économétriques spatiaux</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="sect071.html"><a href="sect071.html#sect0711"><i class="fa fa-check"></i><b>7.1.1</b> Bref retour sur la régression linéaire multiple</a></li>
<li class="chapter" data-level="7.1.2" data-path="sect071.html"><a href="sect071.html#sect0712"><i class="fa fa-check"></i><b>7.1.2</b> Les différents modèles spatiaux autorégressifs</a></li>
<li class="chapter" data-level="7.1.3" data-path="sect071.html"><a href="sect071.html#sect0713"><i class="fa fa-check"></i><b>7.1.3</b> Quel modèle choisir?</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="sect072.html"><a href="sect072.html"><i class="fa fa-check"></i><b>7.2</b> Modèles généralisés additifs (GAM) avec une <em>spline</em> bivariée sur les coordonnées géographiques</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="sect072.html"><a href="sect072.html#sect0721"><i class="fa fa-check"></i><b>7.2.1</b> Principe de base d’un GAM intégrant l’espace</a></li>
<li class="chapter" data-level="7.2.2" data-path="sect072.html"><a href="sect072.html#sect0722"><i class="fa fa-check"></i><b>7.2.2</b> Construction d’un modèle GAM dans R</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="sect073.html"><a href="sect073.html"><i class="fa fa-check"></i><b>7.3</b> Régression géographiquement pondérée</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="sect073.html"><a href="sect073.html#sect0731"><i class="fa fa-check"></i><b>7.3.1</b> Principe de base</a></li>
<li class="chapter" data-level="7.3.2" data-path="sect073.html"><a href="sect073.html#sect0732"><i class="fa fa-check"></i><b>7.3.2</b> Construction et analyse du modèle GWR dans R</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="sect074.html"><a href="sect074.html"><i class="fa fa-check"></i><b>7.4</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="7.5" data-path="sect075.html"><a href="sect075.html"><i class="fa fa-check"></i><b>7.5</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap08.html"><a href="chap08.html"><i class="fa fa-check"></i><b>8</b> Méthodes de classification non supervisée spatiale</a>
<ul>
<li class="chapter" data-level="8.1" data-path="sect081.html"><a href="sect081.html"><i class="fa fa-check"></i><b>8.1</b> Méthodes de classification non supervisée avec contrainte spatiale</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="sect081.html"><a href="sect081.html#sect0811"><i class="fa fa-check"></i><b>8.1.1</b> Algorithmes AZP</a></li>
<li class="chapter" data-level="8.1.2" data-path="sect081.html"><a href="sect081.html#sect0812"><i class="fa fa-check"></i><b>8.1.2</b> Algorithme SKATER</a></li>
<li class="chapter" data-level="8.1.3" data-path="sect081.html"><a href="sect081.html#sect0813"><i class="fa fa-check"></i><b>8.1.3</b> Algorithmes REDCAP</a></li>
<li class="chapter" data-level="8.1.4" data-path="sect081.html"><a href="sect081.html#sect0814"><i class="fa fa-check"></i><b>8.1.4</b> Algorithme du <em>max-p-regions problem</em></a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="sect082.html"><a href="sect082.html"><i class="fa fa-check"></i><b>8.2</b> Méthodes de classification non supervisée avec une dimension spatiale</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="sect082.html"><a href="sect082.html#sect0821"><i class="fa fa-check"></i><b>8.2.1</b> Classification ascendante hiérarchique spatiale (<em>ClustGeo</em>)</a></li>
<li class="chapter" data-level="8.2.2" data-path="sect082.html"><a href="sect082.html#sect0822"><i class="fa fa-check"></i><b>8.2.2</b> <em>Spatial fuzzy c-means</em></a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="sect083.html"><a href="sect083.html"><i class="fa fa-check"></i><b>8.3</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="8.4" data-path="sect084.html"><a href="sect084.html"><i class="fa fa-check"></i><b>8.4</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap09.html"><a href="chap09.html"><i class="fa fa-check"></i><b>9</b> Méthodes d’interpolation spatiale</a>
<ul>
<li class="chapter" data-level="9.1" data-path="sect091.html"><a href="sect091.html"><i class="fa fa-check"></i><b>9.1</b> Méthodes déterministes</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="sect091.html"><a href="sect091.html#sect0911"><i class="fa fa-check"></i><b>9.1.1</b> Interpolation polynomiale locale</a></li>
<li class="chapter" data-level="9.1.2" data-path="sect091.html"><a href="sect091.html#sect0912"><i class="fa fa-check"></i><b>9.1.2</b> Interpolation de l’inverse à la distance (<em>IDW</em>)</a></li>
<li class="chapter" data-level="9.1.3" data-path="sect091.html"><a href="sect091.html#sect0913"><i class="fa fa-check"></i><b>9.1.3</b> Fonctions relationnelles</a></li>
<li class="chapter" data-level="9.1.4" data-path="sect091.html"><a href="sect091.html#sect0914"><i class="fa fa-check"></i><b>9.1.4</b> Fonctions conditionnelles</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="sect092.html"><a href="sect092.html"><i class="fa fa-check"></i><b>9.2</b> Méthodes géostatistiques</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="sect092.html"><a href="sect092.html#sect0921"><i class="fa fa-check"></i><b>9.2.1</b> Krigeage simple</a></li>
<li class="chapter" data-level="9.2.2" data-path="sect092.html"><a href="sect092.html#sect0922"><i class="fa fa-check"></i><b>9.2.2</b> Krigeage universel</a></li>
<li class="chapter" data-level="9.2.3" data-path="sect092.html"><a href="sect092.html#sect0923"><i class="fa fa-check"></i><b>9.2.3</b> Co-krigeage</a></li>
<li class="chapter" data-level="9.2.4" data-path="sect092.html"><a href="sect092.html#sect0924"><i class="fa fa-check"></i><b>9.2.4</b> Krigeage résiduel</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="sect093.html"><a href="sect093.html"><i class="fa fa-check"></i><b>9.3</b> Quiz de révision du chapitre</a></li>
<li class="chapter" data-level="9.4" data-path="sect094.html"><a href="sect094.html"><i class="fa fa-check"></i><b>9.4</b> Exercices de révision</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap10.html"><a href="chap10.html"><i class="fa fa-check"></i><b>10</b> Correction des exercices</a>
<ul>
<li class="chapter" data-level="10.1" data-path="sect1001.html"><a href="sect1001.html"><i class="fa fa-check"></i><b>10.1</b> Exercices du chapitre 1</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="sect1001.html"><a href="sect1001.html#sect10011"><i class="fa fa-check"></i><b>10.1.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.1.2" data-path="sect1001.html"><a href="sect1001.html#sect10012"><i class="fa fa-check"></i><b>10.1.2</b> Exercice 2</a></li>
<li class="chapter" data-level="10.1.3" data-path="sect1001.html"><a href="sect1001.html#sect10013"><i class="fa fa-check"></i><b>10.1.3</b> Exercice 3</a></li>
<li class="chapter" data-level="10.1.4" data-path="sect1001.html"><a href="sect1001.html#sect10014"><i class="fa fa-check"></i><b>10.1.4</b> Exercice 4</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="sect1002.html"><a href="sect1002.html"><i class="fa fa-check"></i><b>10.2</b> Exercices du chapitre 2</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="sect1002.html"><a href="sect1002.html#sect10021"><i class="fa fa-check"></i><b>10.2.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.2.2" data-path="sect1002.html"><a href="sect1002.html#sect10022"><i class="fa fa-check"></i><b>10.2.2</b> Exercice 2</a></li>
<li class="chapter" data-level="10.2.3" data-path="sect1002.html"><a href="sect1002.html#sect10023"><i class="fa fa-check"></i><b>10.2.3</b> Exercice 3</a></li>
<li class="chapter" data-level="10.2.4" data-path="sect1002.html"><a href="sect1002.html#sect10024"><i class="fa fa-check"></i><b>10.2.4</b> Exercice 4</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="sect1003.html"><a href="sect1003.html"><i class="fa fa-check"></i><b>10.3</b> Exercices du chapitre 3</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="sect1003.html"><a href="sect1003.html#sect10031"><i class="fa fa-check"></i><b>10.3.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.3.2" data-path="sect1003.html"><a href="sect1003.html#sect10032"><i class="fa fa-check"></i><b>10.3.2</b> Exercice 2</a></li>
<li class="chapter" data-level="10.3.3" data-path="sect1003.html"><a href="sect1003.html#sect10033"><i class="fa fa-check"></i><b>10.3.3</b> Exercice 3</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="sect1004.html"><a href="sect1004.html"><i class="fa fa-check"></i><b>10.4</b> Exercices du chapitre 4</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="sect1004.html"><a href="sect1004.html#sect10041"><i class="fa fa-check"></i><b>10.4.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.4.2" data-path="sect1004.html"><a href="sect1004.html#sect10042"><i class="fa fa-check"></i><b>10.4.2</b> Exercice 2</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="sect1005.html"><a href="sect1005.html"><i class="fa fa-check"></i><b>10.5</b> Exercices du chapitre 5</a></li>
<li class="chapter" data-level="10.6" data-path="sect1006.html"><a href="sect1006.html"><i class="fa fa-check"></i><b>10.6</b> Exercices du chapitre 6</a></li>
<li class="chapter" data-level="10.7" data-path="sect1007.html"><a href="sect1007.html"><i class="fa fa-check"></i><b>10.7</b> Exercices du chapitre 7</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="sect1007.html"><a href="sect1007.html#sect10071"><i class="fa fa-check"></i><b>10.7.1</b> Exercice 1</a></li>
<li class="chapter" data-level="10.7.2" data-path="sect1007.html"><a href="sect1007.html#sect10072"><i class="fa fa-check"></i><b>10.7.2</b> Exercice 2</a></li>
<li class="chapter" data-level="10.7.3" data-path="sect1007.html"><a href="sect1007.html#sect10073"><i class="fa fa-check"></i><b>10.7.3</b> Exercice 3</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="sect1008.html"><a href="sect1008.html"><i class="fa fa-check"></i><b>10.8</b> Exercices du chapitre 8</a>
<ul>
<li class="chapter" data-level="10.8.1" data-path="sect1008.html"><a href="sect1008.html#sect10081"><i class="fa fa-check"></i><b>10.8.1</b> Exercice 1</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="sect1009.html"><a href="sect1009.html"><i class="fa fa-check"></i><b>10.9</b> Exercices du chapitre 9</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notes de cours GMQ405 :
Modélisation et analyse spatiale</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sect073" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Régression géographiquement pondérée<a href="sect073.html#sect073" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La régression géographiquement pondérée (<em>geographically weighted regression</em> - GWR, en anglais) a été proposée par Fotheringham <em>et al.</em> <span class="citation">(<a href="#ref-fotheringham2003geographically">2003</a>)</span> pour modéliser une variable continue. Depuis, plusieurs extensions ont été proposées, notamment des GWR mixtes, des GWR logistiques ou Poisson. Dans le cadre de cette section, nous abordons uniquement sa forme classique.</p>
<div id="sect0731" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Principe de base<a href="sect073.html#sect0731" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Pourquoi recourir à la GWR?</strong></p>
<p>Dans la section <a href="sect061.html#sect061">6.1</a>, nous avons vu que les modèles autorégressifs visent à contrôler la <strong>dépendance spatiale</strong> d’un modèle de régression classique (MCO), afin d’améliorer l’estimation des coefficients de régression. L’objectif des modèles de régression géographiquement pondérée est différent : ils visent à analyser les variations spatiales de la relation entre la variable dépendante et les variables indépendantes.</p>
<p>Autrement dit, les modèles GWR visent à explorer <strong>l’instabilité spatiale du modèle MCO</strong> afin d’analyser localement la relation entre la variable dépendante et les variables indépendantes. Pour une description détaillée en français de la GWR, consultez Apparicio <em>et al.</em> <span class="citation">(<a href="#ref-apparicio2007modelisation">2007</a>)</span>.</p>
<p><strong>Formulation de la GWR</strong></p>
<p>Contrairement à la régression linéaire classique et aux modèles spatiaux autorégressifs qui produisent une équation pour l’ensemble du tableau de données, la GWR produit une équation pour chaque unité spatiale <em>i</em> et ainsi, des valeurs locales de R<sup>2</sup>, <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_k\)</span>, <em>t</em> de Student, etc. La résolution de cette équation de régression locale est aussi basée sur la méthode des moindres carrés et sur une matrice de pondération W(i) dont les valeurs décroissent en fonction de la distance séparant les unités <em>i</em> et <em>j</em>. Autrement dit, plus <em>j</em> est proche de <em>i</em>, plus sa pondération est élevée et donc plus son « rôle » dans la détermination de l’équation de régression locale de <em>i</em> est important.</p>
<p>De la sorte, la GWR est une extension de la régression linéaire multiple classique où <span class="math inline">\((u_i, v_i)\)</span> représente les coordonnées géographiques du centroïde de l’unité spatiale et où les paramètres <span class="math inline">\(\beta_0\)</span> et <span class="math inline">\(\beta_k\)</span> peuvent
varier dans l’espace (équation <a href="sect073.html#eq:GWR">(7.9)</a>).</p>
<p><span class="math display" id="eq:GWR">\[\begin{equation}
y_i = \beta_0(u_i, v_i)+ \sum_{j=1}^k \beta_j(u_i, v_i)x_{ij}+ \epsilon_i
\tag{7.9}
\end{equation}\]</span>
</p>
<p>avec :</p>
<ul>
<li><span class="math inline">\((u_i, v_i)\)</span>, les coordonnées géographiques de l’unité spatiale <em>i</em>.</li>
<li><span class="math inline">\(y_i\)</span>, la variable dépendante pour l’unité spatiale <em>i</em>.</li>
<li><span class="math inline">\(\beta_0(u_i, v_i)\)</span>, la constante pour l’unité spatiale <em>i</em> aux coordonnées géographiques <span class="math inline">\((u_i, v_i)\)</span>.</li>
<li><span class="math inline">\(\beta_j(u_i, v_i)\)</span>, le coefficient de régression pour la variable <span class="math inline">\(x_j\)</span> (avec <em>k</em> variables indépendantes) pour l’unité spatiale <em>i</em> aux coordonnées géographiques <span class="math inline">\((u_i, v_i)\)</span>.</li>
<li><span class="math inline">\(x_{ij}\)</span>, la valeur de la variable indépendante <span class="math inline">\(x_j\)</span> pour l’unité spatiale <em>i</em>.</li>
<li><span class="math inline">\(\epsilon_i\)</span>, le terme d’erreur pour l’unité spatiale <em>i</em>.</li>
</ul>
<p>Fotheringham <em>et al.</em> <span class="citation">(<a href="#ref-fotheringham2003geographically">2003</a>)</span> proposent deux fonctions <em>kernel</em> pour définir la pondération W(i) dans le modèle GWR : une fonction gaussienne (équation <a href="sect073.html#eq:kernelgaussien">(7.10)</a>) et une fonction bicarrée (équation <a href="sect073.html#eq:kernelbicarree">(7.11)</a>) où <span class="math inline">\(d_{ij}\)</span> représente la distance euclidienne entre les points <em>i</em> et <em>j</em> et <em>b</em>, le rayon de zone d’influence autour du point <em>i</em> (<em>bandwidth</em>). Il existe une différence fondamentale entre les deux : la fonction gaussienne accorde un poids non nul à tous les points de l’espace d’étude aussi loin soient-ils, tandis que la fonction bicarrée ne tient pas compte des points distants à plus de <em>b</em> mètres de <em>i</em>, tel qu’illustré à la figure <a href="sect073.html#fig:GWRKernels">7.8</a> avec une valeur fixée à 5000 mètres en guise d’exemple.</p>
<p><span class="math display" id="eq:kernelgaussien">\[\begin{equation}
w_{ij} = exp[-.5(d_{ij}/b)^2]
\tag{7.10}
\end{equation}\]</span>
</p>
<p><span class="math display" id="eq:kernelbicarree">\[\begin{equation}
w_{ij} = [1-(d_{ij}/b)^2]^2 \text{ si } d_{ij}&lt; b \text{, sinon } w_{ij}=0
\tag{7.11}
\end{equation}\]</span>
</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:GWRKernels"></span>
<img src="GMQ405_files/figure-html/GWRKernels-1.png" alt="Fonctions kernel pour définir la matrice de pondération W(i)" width="75%" />
<p class="caption">
Figure 7.8: Fonctions kernel pour définir la matrice de pondération W(i)
</p>
</div>
<p>Dans le modèle GWR, la valeur de <em>b</em> est soit fixée par la personne utilisatrice, soit optimisée avec la valeur de CV (<em>cross-validation</em>) ou celle de l’AIC. Notez qu’il est possible d’optimiser la taille de la zone d’influence à partir de la distance euclidienne ou du nombre de plus proches voisins.</p>
</div>
<div id="sect0732" class="section level3 hasAnchor" number="7.3.2">
<h3><span class="header-section-number">7.3.2</span> Construction et analyse du modèle GWR dans R<a href="sect073.html#sect0732" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Pour construire un modèle GWR dans R, nous utilisons le <em>package</em> <code>spgwr</code> <span class="citation">(<a href="#ref-packagesGWR">Bivand et Yu 2023</a>)</span>. La construction d’un modèle GWR comprend les étapes suivantes :</p>
<ol style="list-style-type: decimal">
<li>Sélection de la taille de la zone d’influence (<em>bandwith</em>) optimale.</li>
<li>Réalisation de la GWR avec la taille de la zone d’influence optimale.</li>
<li>Comparaison des modèles MCO et GWR.</li>
<li>Cartographie des résultats du modèle GWR (R<sup>2</sup>, coefficients, valeurs de <em>t</em>, etc.)</li>
</ol>
<div id="sect07321" class="section level4 hasAnchor" number="7.3.2.1">
<h4><span class="header-section-number">7.3.2.1</span> Définition de la taille de la zone d’influence<a href="sect073.html#sect07321" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>La sélection de la taille de la zone d’influence optimale est réalisée avec la fonction <code>gwr.sel</code> pour laquelle :</p>
<ul>
<li>le paramètre <code>gweight</code> permet de spécifier une fonction <em>kernel</em> gaussienne (<code>gwr.gauss</code>) ou bicarrée (<code>gwr.gauss</code>).</li>
<li>le paramètre <code>adapt</code> permet de spécifier si vous optimisez le nombre de plus proches voisins (<code>adapt=TRUE</code>) ou la distance (<code>adapt=FALSE</code>).</li>
</ul>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb526-1"><a href="sect073.html#cb526-1" tabindex="-1"></a><span class="fu">library</span>(spgwr)</span>
<span id="cb526-2"><a href="sect073.html#cb526-2" tabindex="-1"></a><span class="do">## Optimisation du nombre de voisins avec le CV</span></span>
<span id="cb526-3"><a href="sect073.html#cb526-3" tabindex="-1"></a>bwaCV.voisins  <span class="ot">&lt;-</span> <span class="fu">gwr.sel</span>(NO2 <span class="sc">~</span>  Pct0_14<span class="sc">+</span>Pct_65<span class="sc">+</span>Pct_Img<span class="sc">+</span>Pct_brevet<span class="sc">+</span>NivVieMed,</span>
<span id="cb526-4"><a href="sect073.html#cb526-4" tabindex="-1"></a>                          <span class="at">data =</span> LyonIris,</span>
<span id="cb526-5"><a href="sect073.html#cb526-5" tabindex="-1"></a>                          <span class="at">method =</span> <span class="st">&quot;cv&quot;</span>,          <span class="co"># Méthode cv ou AIC</span></span>
<span id="cb526-6"><a href="sect073.html#cb526-6" tabindex="-1"></a>                          <span class="at">gweight=</span>gwr.bisquare,   <span class="co"># gwr.gauss ou gwr.bisquare</span></span>
<span id="cb526-7"><a href="sect073.html#cb526-7" tabindex="-1"></a>                          <span class="at">adapt=</span><span class="cn">TRUE</span>,</span>
<span id="cb526-8"><a href="sect073.html#cb526-8" tabindex="-1"></a>                          <span class="at">verbose =</span> <span class="cn">FALSE</span>,</span>
<span id="cb526-9"><a href="sect073.html#cb526-9" tabindex="-1"></a>                          <span class="at">RMSE =</span> <span class="cn">TRUE</span>,</span>
<span id="cb526-10"><a href="sect073.html#cb526-10" tabindex="-1"></a>                          <span class="at">longlat =</span> <span class="cn">FALSE</span>,</span>
<span id="cb526-11"><a href="sect073.html#cb526-11" tabindex="-1"></a>                          <span class="at">coords=</span><span class="fu">cbind</span>(LyonIris<span class="sc">$</span>X,LyonIris<span class="sc">$</span>Y))</span>
<span id="cb526-12"><a href="sect073.html#cb526-12" tabindex="-1"></a><span class="do">## Optimisation du nombre de voisins avec l&#39;AIC</span></span>
<span id="cb526-13"><a href="sect073.html#cb526-13" tabindex="-1"></a>bwaAIC.voisins <span class="ot">&lt;-</span> <span class="fu">gwr.sel</span>(NO2 <span class="sc">~</span>  Pct0_14<span class="sc">+</span>Pct_65<span class="sc">+</span>Pct_Img<span class="sc">+</span>Pct_brevet<span class="sc">+</span>NivVieMed,</span>
<span id="cb526-14"><a href="sect073.html#cb526-14" tabindex="-1"></a>                          <span class="at">data =</span> LyonIris,</span>
<span id="cb526-15"><a href="sect073.html#cb526-15" tabindex="-1"></a>                          <span class="at">method =</span> <span class="st">&quot;AIC&quot;</span>,          <span class="co"># Méthode cv ou AIC</span></span>
<span id="cb526-16"><a href="sect073.html#cb526-16" tabindex="-1"></a>                          <span class="at">gweight=</span>gwr.bisquare,    <span class="co"># gwr.gauss ou gwr.bisquare</span></span>
<span id="cb526-17"><a href="sect073.html#cb526-17" tabindex="-1"></a>                          <span class="at">adapt=</span><span class="cn">TRUE</span>,              <span class="co"># adaptatif</span></span>
<span id="cb526-18"><a href="sect073.html#cb526-18" tabindex="-1"></a>                          <span class="at">verbose =</span> <span class="cn">FALSE</span>,</span>
<span id="cb526-19"><a href="sect073.html#cb526-19" tabindex="-1"></a>                          <span class="at">RMSE =</span> <span class="cn">TRUE</span>,</span>
<span id="cb526-20"><a href="sect073.html#cb526-20" tabindex="-1"></a>                          <span class="at">longlat =</span> <span class="cn">FALSE</span>,</span>
<span id="cb526-21"><a href="sect073.html#cb526-21" tabindex="-1"></a>                          <span class="at">coords=</span><span class="fu">cbind</span>(LyonIris<span class="sc">$</span>X,LyonIris<span class="sc">$</span>Y))</span>
<span id="cb526-22"><a href="sect073.html#cb526-22" tabindex="-1"></a><span class="do">## Optimisation de la distance avec le CV</span></span>
<span id="cb526-23"><a href="sect073.html#cb526-23" tabindex="-1"></a>bwnaCV.dist <span class="ot">&lt;-</span> <span class="fu">gwr.sel</span>(NO2 <span class="sc">~</span>  Pct0_14<span class="sc">+</span>Pct_65<span class="sc">+</span>Pct_Img<span class="sc">+</span>Pct_brevet<span class="sc">+</span>NivVieMed,</span>
<span id="cb526-24"><a href="sect073.html#cb526-24" tabindex="-1"></a>                           <span class="at">data =</span> LyonIris,</span>
<span id="cb526-25"><a href="sect073.html#cb526-25" tabindex="-1"></a>                           <span class="at">method =</span> <span class="st">&quot;cv&quot;</span>,     <span class="co"># méthode cv ou AIC</span></span>
<span id="cb526-26"><a href="sect073.html#cb526-26" tabindex="-1"></a>                           <span class="at">gweight=</span>gwr.Gauss, <span class="co"># gwr.gauss ou gwr.bisquare</span></span>
<span id="cb526-27"><a href="sect073.html#cb526-27" tabindex="-1"></a>                           <span class="at">adapt=</span><span class="cn">FALSE</span>,       <span class="co"># non adaptatif</span></span>
<span id="cb526-28"><a href="sect073.html#cb526-28" tabindex="-1"></a>                           <span class="at">verbose =</span> <span class="cn">FALSE</span>,</span>
<span id="cb526-29"><a href="sect073.html#cb526-29" tabindex="-1"></a>                           <span class="at">RMSE =</span> <span class="cn">TRUE</span>,</span>
<span id="cb526-30"><a href="sect073.html#cb526-30" tabindex="-1"></a>                           <span class="at">longlat =</span> <span class="cn">FALSE</span>,</span>
<span id="cb526-31"><a href="sect073.html#cb526-31" tabindex="-1"></a>                           <span class="at">coords=</span><span class="fu">cbind</span>(LyonIris<span class="sc">$</span>X,LyonIris<span class="sc">$</span>Y))</span>
<span id="cb526-32"><a href="sect073.html#cb526-32" tabindex="-1"></a><span class="do">## Optimisation de la distance avec l&#39;AIC</span></span>
<span id="cb526-33"><a href="sect073.html#cb526-33" tabindex="-1"></a>bwnaAIC.dist <span class="ot">&lt;-</span> <span class="fu">gwr.sel</span>(NO2 <span class="sc">~</span>  Pct0_14<span class="sc">+</span>Pct_65<span class="sc">+</span>Pct_Img<span class="sc">+</span>Pct_brevet<span class="sc">+</span>NivVieMed,</span>
<span id="cb526-34"><a href="sect073.html#cb526-34" tabindex="-1"></a>                          <span class="at">data =</span> LyonIris,</span>
<span id="cb526-35"><a href="sect073.html#cb526-35" tabindex="-1"></a>                          <span class="at">method =</span> <span class="st">&quot;AIC&quot;</span>,      <span class="co"># méthode cv ou AIC</span></span>
<span id="cb526-36"><a href="sect073.html#cb526-36" tabindex="-1"></a>                          <span class="at">gweight=</span>gwr.Gauss,   <span class="co"># gwr.gauss ou gwr.bisquare</span></span>
<span id="cb526-37"><a href="sect073.html#cb526-37" tabindex="-1"></a>                          <span class="at">adapt=</span><span class="cn">FALSE</span>,         <span class="co"># non adaptatif</span></span>
<span id="cb526-38"><a href="sect073.html#cb526-38" tabindex="-1"></a>                          <span class="at">RMSE =</span> <span class="cn">TRUE</span>,</span>
<span id="cb526-39"><a href="sect073.html#cb526-39" tabindex="-1"></a>                          <span class="at">verbose =</span> <span class="cn">FALSE</span>,</span>
<span id="cb526-40"><a href="sect073.html#cb526-40" tabindex="-1"></a>                          <span class="at">longlat =</span> <span class="cn">FALSE</span>,</span>
<span id="cb526-41"><a href="sect073.html#cb526-41" tabindex="-1"></a>                          <span class="at">coords=</span><span class="fu">cbind</span>(LyonIris<span class="sc">$</span>X,LyonIris<span class="sc">$</span>Y))</span>
<span id="cb526-42"><a href="sect073.html#cb526-42" tabindex="-1"></a><span class="do">## Affichage des résultats d&#39;optimisation </span></span>
<span id="cb526-43"><a href="sect073.html#cb526-43" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Sélection de la taille de la zone optimale (bandwith)&quot;</span>,</span>
<span id="cb526-44"><a href="sect073.html#cb526-44" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> avec le nombre de plus proches voisins :&quot;</span>,</span>
<span id="cb526-45"><a href="sect073.html#cb526-45" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">  CV =&quot;</span>, <span class="fu">round</span>(bwaCV.voisins,<span class="dv">4</span>), <span class="st">&quot;nombre de voisins =&quot;</span>, </span>
<span id="cb526-46"><a href="sect073.html#cb526-46" tabindex="-1"></a>    <span class="fu">round</span>(bwaCV.voisins<span class="sc">*</span><span class="fu">nrow</span>(LyonIris)),</span>
<span id="cb526-47"><a href="sect073.html#cb526-47" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">  AIC =&quot;</span>, <span class="fu">round</span>(bwaAIC.voisins,<span class="dv">4</span>), <span class="st">&quot;nombre de voisins =&quot;</span>, </span>
<span id="cb526-48"><a href="sect073.html#cb526-48" tabindex="-1"></a>    <span class="fu">round</span>(bwaAIC.voisins<span class="sc">*</span><span class="fu">nrow</span>(LyonIris)),</span>
<span id="cb526-49"><a href="sect073.html#cb526-49" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">Sélection de la taille de la zone optimale (bandwith) avec la distance :&quot;</span>,</span>
<span id="cb526-50"><a href="sect073.html#cb526-50" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">  CV =&quot;</span>, <span class="fu">round</span>(bwnaCV.dist, <span class="dv">0</span>),  <span class="st">&quot;mètres&quot;</span>,</span>
<span id="cb526-51"><a href="sect073.html#cb526-51" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">  AIC =&quot;</span>, <span class="fu">round</span>(bwnaAIC.dist, <span class="dv">0</span>), <span class="st">&quot;mètres&quot;</span>)</span></code></pre></div>
<pre><code>## Sélection de la taille de la zone optimale (bandwith) 
##  avec le nombre de plus proches voisins : 
##   CV = 0.1818 nombre de voisins = 92 
##   AIC = 0.1067 nombre de voisins = 54 
## Sélection de la taille de la zone optimale (bandwith) avec la distance : 
##   CV = 1315 mètres 
##   AIC = 1662 mètres</code></pre>
<p>Les résultats ci-dessus montrent que le nombre de plus proche voisins pourrait être de 92 selon l’approche <em>cross-validation</em> et de 54 selon la méthode basée sur l’AIC. Si la valeur de <em>b</em> est basée sur la distance, elle serait alors optimale à 1315 et 1662 mètres selon les deux méthodes.</p>
</div>
<div id="sect07322" class="section level4 hasAnchor" number="7.3.2.2">
<h4><span class="header-section-number">7.3.2.2</span> Réalisation de la GWR<a href="sect073.html#sect07322" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Avec la fonction <code>gwr</code>, nous estimons un modèle GWR avec un kernel bicarré et un nombre de plus voisins optimisé selon la méthode CV, soit 92.</p>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb528-1"><a href="sect073.html#cb528-1" tabindex="-1"></a>Modele.GWR <span class="ot">&lt;-</span> <span class="fu">gwr</span>(NO2 <span class="sc">~</span> Pct0_14<span class="sc">+</span>Pct_65<span class="sc">+</span>Pct_Img<span class="sc">+</span>Pct_brevet<span class="sc">+</span>NivVieMed,</span>
<span id="cb528-2"><a href="sect073.html#cb528-2" tabindex="-1"></a>              <span class="at">data =</span> LyonIris,</span>
<span id="cb528-3"><a href="sect073.html#cb528-3" tabindex="-1"></a>              <span class="at">adapt=</span>bwaCV.voisins,</span>
<span id="cb528-4"><a href="sect073.html#cb528-4" tabindex="-1"></a>              <span class="at">gweight=</span>gwr.bisquare,</span>
<span id="cb528-5"><a href="sect073.html#cb528-5" tabindex="-1"></a>              <span class="at">hatmatrix=</span><span class="cn">TRUE</span>,</span>
<span id="cb528-6"><a href="sect073.html#cb528-6" tabindex="-1"></a>              <span class="at">se.fit=</span><span class="cn">TRUE</span>,</span>
<span id="cb528-7"><a href="sect073.html#cb528-7" tabindex="-1"></a>              <span class="at">coords=</span><span class="fu">cbind</span>(LyonIris<span class="sc">$</span>X,LyonIris<span class="sc">$</span>Y),</span>
<span id="cb528-8"><a href="sect073.html#cb528-8" tabindex="-1"></a>              <span class="at">longlat=</span>F)</span></code></pre></div>
<p>Le code ci-dessous permet de renvoyer les statistiques univariées des coefficients des 506 régressions locales, réalisées pour chacune des 506 entités spatiales (IRIS), et les statistiques d’ajustement du modèle (AIC, R<sup>2</sup> global, etc.)</p>
<div class="sourceCode" id="cb529"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb529-1"><a href="sect073.html#cb529-1" tabindex="-1"></a>Modele.GWR</span></code></pre></div>
<pre><code>## Call:
## gwr(formula = NO2 ~ Pct0_14 + Pct_65 + Pct_Img + Pct_brevet + 
##     NivVieMed, data = LyonIris, coords = cbind(LyonIris$X, LyonIris$Y), 
##     gweight = gwr.bisquare, adapt = bwaCV.voisins, hatmatrix = TRUE, 
##     longlat = F, se.fit = TRUE)
## Kernel function: gwr.bisquare 
## Adaptive quantile: 0.1818192 (about 92 of 506 data points)
## Summary of GWR coefficient estimates at data points:
##                   Min.   1st Qu.    Median   3rd Qu.      Max.  Global
## X.Intercept. 12.429518 30.249511 38.619342 48.038863 60.098584 49.4330
## Pct0_14      -1.094802 -0.360556 -0.215643 -0.047687  0.382801 -0.5335
## Pct_65       -0.715331 -0.158253 -0.031353  0.076086  0.464992 -0.1505
## Pct_Img      -0.331892 -0.049146  0.077177  0.240755  0.670433  0.2829
## Pct_brevet   -0.655221 -0.221655 -0.084954  0.047835  0.598456 -0.2400
## NivVieMed    -1.140895 -0.560649 -0.214717  0.193768  1.311228 -0.3162
## Number of data points: 506 
## Effective number of parameters (residual: 2traceS - traceS&#39;S): 107.1278 
## Effective degrees of freedom (residual: 2traceS - traceS&#39;S): 398.8722 
## Sigma (residual: 2traceS - traceS&#39;S): 4.118116 
## Effective number of parameters (model: traceS): 81.53263 
## Effective degrees of freedom (model: traceS): 424.4674 
## Sigma (model: traceS): 3.992025 
## Sigma (ML): 3.656286 
## AICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 2945.674 
## AIC (GWR p. 96, eq. 4.22): 2829.504 
## Residual sum of squares: 6764.424 
## Quasi-global R2: 0.783008</code></pre>
</div>
<div id="sect07323" class="section level4 hasAnchor" number="7.3.2.3">
<h4><span class="header-section-number">7.3.2.3</span> Comparaison des modèles MCO et GWR<a href="sect073.html#sect07323" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Le R<sup>2</sup> global du modèle GWR est bien supérieur au modèle classique MCO (0,783 contre 0,283). Fotheringham <em>et al.</em> <span class="citation">(<a href="#ref-fotheringham2003geographically">2003</a>)</span> proposent plusieurs tests pour comparer les modèles GWR et classique qui sont implémentés dans le <em>package</em> <code>spgwr</code> (fonctions <code>anova(Modele.GWR)</code>, <code>anova(Modele.GWR, approx=TRUE)</code>, <code>LMZ.F1GWR.test(Modele.GWR)</code>, <code>LMZ.F2GWR.test(Modele.GWR)</code>.</p>
<p>Si les valeurs de <em>p</em> de ces tests sont inférieures à 0,05 alors le modèle GWR améliore de façon significative la capacité prédictive du modèle de régression globale, ce que confirment les résultats ci-dessous.</p>
<div class="sourceCode" id="cb531"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb531-1"><a href="sect073.html#cb531-1" tabindex="-1"></a><span class="fu">anova</span>(Modele.GWR)</span></code></pre></div>
<pre><code>## Analysis of Variance Table 
##                     Df  Sum Sq Mean Sq F value
## OLS Residuals     6.00 22346.0                
## GWR Improvement 101.13 15581.6 154.078        
## GWR Residuals   398.87  6764.4  16.959  9.0854</code></pre>
<div class="sourceCode" id="cb533"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb533-1"><a href="sect073.html#cb533-1" tabindex="-1"></a><span class="fu">anova</span>(Modele.GWR, <span class="at">approx=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Analysis of Variance Table 
## approximate degrees of freedom (only tr(S))
##                      Df  Sum Sq Mean Sq F value
## OLS Residuals     6.000 22346.0                
## GWR Improvement  75.533 15581.6 206.290        
## GWR Residuals   424.467  6764.4  15.936  12.945</code></pre>
<div class="sourceCode" id="cb535"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb535-1"><a href="sect073.html#cb535-1" tabindex="-1"></a><span class="fu">LMZ.F1GWR.test</span>(Modele.GWR)</span></code></pre></div>
<pre><code>## 
##  Leung et al. (2000) F(1) test
## 
## data:  Modele.GWR
## F = 0.37946, df1 = 430.81, df2 = 500.00, p-value &lt; 2.2e-16
## alternative hypothesis: less
## sample estimates:
## SS OLS residuals SS GWR residuals 
##        22346.021         6764.424</code></pre>
<div class="sourceCode" id="cb537"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb537-1"><a href="sect073.html#cb537-1" tabindex="-1"></a><span class="fu">LMZ.F2GWR.test</span>(Modele.GWR)</span></code></pre></div>
<pre><code>## 
##  Leung et al. (2000) F(2) test
## 
## data:  Modele.GWR
## F = 3.4476, df1 = 142.92, df2 = 500.00, p-value &lt; 2.2e-16
## alternative hypothesis: greater
## sample estimates:
##   SS OLS residuals SS GWR improvement 
##           22346.02           15581.60</code></pre>
<p>Un autres test (<code>LMZ.F3GWR.test</code>) permet de répondre à la question suivante : est-ce que les coefficients de régression du modèle GWR varient spatialement de façon significative? Les résultats ci-dessous démontrent que c’est le cas pour toutes les variables indépendantes et la constante (<em>p</em> &lt; 0,001).</p>
<div class="sourceCode" id="cb539"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb539-1"><a href="sect073.html#cb539-1" tabindex="-1"></a><span class="fu">LMZ.F3GWR.test</span>(Modele.GWR)</span></code></pre></div>
<pre><code>## 
## Leung et al. (2000) F(3) test
## 
##             F statistic Numerator d.f. Denominator d.f.     Pr(&gt;)    
## (Intercept)      2.2771       134.3880           430.81 1.629e-10 ***
## Pct0_14          2.7767       141.7244           430.81 5.636e-16 ***
## Pct_65           2.0918       169.0472           430.81 8.399e-10 ***
## Pct_Img          1.9486       106.4400           430.81 1.550e-06 ***
## Pct_brevet       2.4445       121.2830           430.81 1.629e-11 ***
## NivVieMed        3.6926       138.8118           430.81 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="sect07324" class="section level4 hasAnchor" number="7.3.2.4">
<h4><span class="header-section-number">7.3.2.4</span> Cartographie des résultats du modèle GWR<a href="sect073.html#sect07324" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Dans un premier temps, nous ajoutons les valeurs locales des R<sup>2</sup>, des coefficients de régression et des valeurs de <em>t</em> dans la couche <code>sf</code>. Notez que les résultats locaux de la GWR sont stockés dans l’objet <code>Modele.GWR$SDF</code>.</p>
<div class="sourceCode" id="cb541"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb541-1"><a href="sect073.html#cb541-1" tabindex="-1"></a><span class="do">## Récupération du R carré local</span></span>
<span id="cb541-2"><a href="sect073.html#cb541-2" tabindex="-1"></a>LyonIris<span class="sc">$</span>GWR.R2 <span class="ot">&lt;-</span> Modele.GWR<span class="sc">$</span>SDF<span class="sc">$</span>localR2</span>
<span id="cb541-3"><a href="sect073.html#cb541-3" tabindex="-1"></a><span class="do">## Récupération des coefficients de régression et calcul des valeurs de t locales</span></span>
<span id="cb541-4"><a href="sect073.html#cb541-4" tabindex="-1"></a><span class="fu">names</span>(Modele.GWR<span class="sc">$</span>SDF)</span></code></pre></div>
<pre><code>##  [1] &quot;sum.w&quot;              &quot;(Intercept)&quot;        &quot;Pct0_14&quot;           
##  [4] &quot;Pct_65&quot;             &quot;Pct_Img&quot;            &quot;Pct_brevet&quot;        
##  [7] &quot;NivVieMed&quot;          &quot;(Intercept)_se&quot;     &quot;Pct0_14_se&quot;        
## [10] &quot;Pct_65_se&quot;          &quot;Pct_Img_se&quot;         &quot;Pct_brevet_se&quot;     
## [13] &quot;NivVieMed_se&quot;       &quot;gwr.e&quot;              &quot;pred&quot;              
## [16] &quot;pred.se&quot;            &quot;localR2&quot;            &quot;(Intercept)_se_EDF&quot;
## [19] &quot;Pct0_14_se_EDF&quot;     &quot;Pct_65_se_EDF&quot;      &quot;Pct_Img_se_EDF&quot;    
## [22] &quot;Pct_brevet_se_EDF&quot;  &quot;NivVieMed_se_EDF&quot;   &quot;pred.se&quot;</code></pre>
<div class="sourceCode" id="cb543"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb543-1"><a href="sect073.html#cb543-1" tabindex="-1"></a>VarsIndep <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Pct0_14&quot;</span>, <span class="st">&quot;Pct_65&quot;</span>, <span class="st">&quot;Pct_Img&quot;</span>, <span class="st">&quot;Pct_brevet&quot;</span>, <span class="st">&quot;NivVieMed&quot;</span>)</span>
<span id="cb543-2"><a href="sect073.html#cb543-2" tabindex="-1"></a><span class="cf">for</span>(e <span class="cf">in</span> VarsIndep){</span>
<span id="cb543-3"><a href="sect073.html#cb543-3" tabindex="-1"></a>  <span class="co"># Nom des nouvelles variables</span></span>
<span id="cb543-4"><a href="sect073.html#cb543-4" tabindex="-1"></a>  var.coef <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;GWR.&quot;</span>, <span class="st">&quot;B_&quot;</span>, e)</span>
<span id="cb543-5"><a href="sect073.html#cb543-5" tabindex="-1"></a>  var.t    <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;GWR.&quot;</span>, <span class="st">&quot;T_&quot;</span>, e)</span>
<span id="cb543-6"><a href="sect073.html#cb543-6" tabindex="-1"></a>  <span class="co"># Récupération des coefficients pour les variables indépendantes</span></span>
<span id="cb543-7"><a href="sect073.html#cb543-7" tabindex="-1"></a>  LyonIris[[var.coef]] <span class="ot">&lt;-</span> Modele.GWR<span class="sc">$</span>SDF[[e]]</span>
<span id="cb543-8"><a href="sect073.html#cb543-8" tabindex="-1"></a>  <span class="co"># Calcul des valeurs de t pour les variables indépendantes</span></span>
<span id="cb543-9"><a href="sect073.html#cb543-9" tabindex="-1"></a>  LyonIris[[var.t]]    <span class="ot">&lt;-</span> Modele.GWR<span class="sc">$</span>SDF[[e]] <span class="sc">/</span> Modele.GWR<span class="sc">$</span>SDF[[<span class="fu">paste0</span>(e, <span class="st">&quot;_se&quot;</span>)]]</span>
<span id="cb543-10"><a href="sect073.html#cb543-10" tabindex="-1"></a>}</span></code></pre></div>
<p><strong>Cartographie des R<sup>2</sup> locaux</strong></p>
<p>Le code ci-dessous permet ensuite de cartographier les R<sup>2</sup> locaux de la GWR (figure <a href="sect073.html#fig:GWRR2">7.9</a>).</p>
<div class="sourceCode" id="cb544"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb544-1"><a href="sect073.html#cb544-1" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb544-2"><a href="sect073.html#cb544-2" tabindex="-1"></a><span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span></span>
<span id="cb544-3"><a href="sect073.html#cb544-3" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb544-4"><a href="sect073.html#cb544-4" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;GWR.R2&quot;</span>, <span class="at">palette=</span><span class="st">&quot;YlOrBr&quot;</span>, <span class="at">n=</span><span class="dv">5</span>, <span class="at">style=</span><span class="st">&quot;quantile&quot;</span>, <span class="at">title =</span> <span class="st">&quot;R2 locaux&quot;</span>)<span class="sc">+</span></span>
<span id="cb544-5"><a href="sect073.html#cb544-5" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb544-6"><a href="sect073.html#cb544-6" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:GWRR2"></span>
<img src="GMQ405_files/figure-html/GWRR2-1.png" alt="Cartographie des R2 locaux de la GWR" width="75%" />
<p class="caption">
Figure 7.9: Cartographie des R2 locaux de la GWR
</p>
</div>
<p><strong>Cartographie des coefficients de régression </strong></p>
<p>Le code ci-dessous permet ensuite de cartographier les coefficients locaux de la GWR (figure <a href="sect073.html#fig:GWRCoeffReg">7.10</a>).</p>
<div class="sourceCode" id="cb545"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb545-1"><a href="sect073.html#cb545-1" tabindex="-1"></a>Carte1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb545-2"><a href="sect073.html#cb545-2" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;GWR.B_Pct0_14&quot;</span>, <span class="at">palette=</span><span class="st">&quot;YlOrBr&quot;</span>, <span class="at">n=</span><span class="dv">4</span>, <span class="at">style=</span><span class="st">&quot;pretty&quot;</span>, </span>
<span id="cb545-3"><a href="sect073.html#cb545-3" tabindex="-1"></a>                  <span class="at">title =</span> <span class="st">&quot;Moins de 15 ans (%)&quot;</span>)<span class="sc">+</span></span>
<span id="cb545-4"><a href="sect073.html#cb545-4" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)<span class="sc">+</span><span class="fu">tm_scale_bar</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span>
<span id="cb545-5"><a href="sect073.html#cb545-5" tabindex="-1"></a>Carte2 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb545-6"><a href="sect073.html#cb545-6" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;GWR.B_Pct_65&quot;</span>, <span class="at">palette=</span><span class="st">&quot;YlOrBr&quot;</span>, <span class="at">n=</span><span class="dv">4</span>, <span class="at">style=</span><span class="st">&quot;pretty&quot;</span>, </span>
<span id="cb545-7"><a href="sect073.html#cb545-7" tabindex="-1"></a>                  <span class="at">title =</span> <span class="st">&quot;65 ans et plus (%)&quot;</span>)<span class="sc">+</span></span>
<span id="cb545-8"><a href="sect073.html#cb545-8" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)<span class="sc">+</span><span class="fu">tm_scale_bar</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span>
<span id="cb545-9"><a href="sect073.html#cb545-9" tabindex="-1"></a>Carte3 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb545-10"><a href="sect073.html#cb545-10" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;GWR.B_Pct_Img&quot;</span>, <span class="at">palette=</span><span class="st">&quot;YlOrBr&quot;</span>, <span class="at">n=</span><span class="dv">4</span>, <span class="at">style=</span><span class="st">&quot;pretty&quot;</span>, </span>
<span id="cb545-11"><a href="sect073.html#cb545-11" tabindex="-1"></a>                  <span class="at">title =</span> <span class="st">&quot;Immigrants (%)&quot;</span>)<span class="sc">+</span></span>
<span id="cb545-12"><a href="sect073.html#cb545-12" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)<span class="sc">+</span><span class="fu">tm_scale_bar</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span>
<span id="cb545-13"><a href="sect073.html#cb545-13" tabindex="-1"></a>Carte4 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb545-14"><a href="sect073.html#cb545-14" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;GWR.B_Pct_brevet&quot;</span>, <span class="at">palette=</span><span class="st">&quot;YlOrBr&quot;</span>, <span class="at">n=</span><span class="dv">4</span>, <span class="at">style=</span><span class="st">&quot;pretty&quot;</span>, </span>
<span id="cb545-15"><a href="sect073.html#cb545-15" tabindex="-1"></a>                  <span class="at">title =</span> <span class="st">&quot;Faible scolarité (%)&quot;</span>)<span class="sc">+</span></span>
<span id="cb545-16"><a href="sect073.html#cb545-16" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)<span class="sc">+</span><span class="fu">tm_scale_bar</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span>
<span id="cb545-17"><a href="sect073.html#cb545-17" tabindex="-1"></a>Carte5 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb545-18"><a href="sect073.html#cb545-18" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;GWR.B_NivVieMed&quot;</span>, <span class="at">palette=</span><span class="st">&quot;YlOrBr&quot;</span>, <span class="at">n=</span><span class="dv">4</span>, <span class="at">style=</span><span class="st">&quot;pretty&quot;</span>, </span>
<span id="cb545-19"><a href="sect073.html#cb545-19" tabindex="-1"></a>                  <span class="at">title =</span> <span class="st">&quot;Niveau de vie (€1000)&quot;</span>)<span class="sc">+</span></span>
<span id="cb545-20"><a href="sect073.html#cb545-20" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)<span class="sc">+</span><span class="fu">tm_scale_bar</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span>
<span id="cb545-21"><a href="sect073.html#cb545-21" tabindex="-1"></a><span class="fu">tmap_arrange</span>(Carte1, Carte2, Carte3, Carte4, Carte5, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:GWRCoeffReg"></span>
<img src="GMQ405_files/figure-html/GWRCoeffReg-1.png" alt="Cartographie des coefficients de régression de la GWR" width="100%" />
<p class="caption">
Figure 7.10: Cartographie des coefficients de régression de la GWR
</p>
</div>
<p><strong>Cartographie des valeurs de <em>t</em></strong></p>
<p>Pour cartographier les valeurs de <em>t</em>, nous utilisons les seuils de ± 1,96, 2,58 et 3,29, indiquant des seuils de signification à 5%, 1% et 0,1% (figure <a href="sect073.html#fig:GWRValT">7.11</a>).</p>
<div class="sourceCode" id="cb546"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb546-1"><a href="sect073.html#cb546-1" tabindex="-1"></a>classes.intervalles <span class="ot">=</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="sc">-</span><span class="fl">3.29</span>, <span class="sc">-</span><span class="fl">2.58</span>, <span class="sc">-</span><span class="fl">1.96</span>, <span class="fl">1.96</span>, <span class="fl">2.58</span>, <span class="fl">3.29</span>, <span class="cn">Inf</span>)</span>
<span id="cb546-2"><a href="sect073.html#cb546-2" tabindex="-1"></a>Carte1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb546-3"><a href="sect073.html#cb546-3" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;GWR.T_Pct0_14&quot;</span>, <span class="at">palette=</span><span class="st">&quot;-RdBu&quot;</span>, </span>
<span id="cb546-4"><a href="sect073.html#cb546-4" tabindex="-1"></a>                  <span class="at">breaks =</span> classes.intervalles,</span>
<span id="cb546-5"><a href="sect073.html#cb546-5" tabindex="-1"></a>                  <span class="at">title =</span> <span class="st">&quot;Moins de 15 ans (%)&quot;</span>)<span class="sc">+</span></span>
<span id="cb546-6"><a href="sect073.html#cb546-6" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span>
<span id="cb546-7"><a href="sect073.html#cb546-7" tabindex="-1"></a>Carte2 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb546-8"><a href="sect073.html#cb546-8" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;GWR.T_Pct_65&quot;</span>, <span class="at">palette=</span><span class="st">&quot;-RdBu&quot;</span>,</span>
<span id="cb546-9"><a href="sect073.html#cb546-9" tabindex="-1"></a>                  <span class="at">breaks =</span> classes.intervalles,</span>
<span id="cb546-10"><a href="sect073.html#cb546-10" tabindex="-1"></a>                  <span class="at">title =</span> <span class="st">&quot;65 ans et plus (%)&quot;</span>)<span class="sc">+</span></span>
<span id="cb546-11"><a href="sect073.html#cb546-11" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span>
<span id="cb546-12"><a href="sect073.html#cb546-12" tabindex="-1"></a>Carte3 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb546-13"><a href="sect073.html#cb546-13" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;GWR.T_Pct_Img&quot;</span>, <span class="at">palette=</span><span class="st">&quot;-RdBu&quot;</span>, </span>
<span id="cb546-14"><a href="sect073.html#cb546-14" tabindex="-1"></a>                  <span class="at">breaks =</span> classes.intervalles,</span>
<span id="cb546-15"><a href="sect073.html#cb546-15" tabindex="-1"></a>                  <span class="at">title =</span> <span class="st">&quot;Immigrants (%)&quot;</span>)<span class="sc">+</span></span>
<span id="cb546-16"><a href="sect073.html#cb546-16" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span>
<span id="cb546-17"><a href="sect073.html#cb546-17" tabindex="-1"></a>Carte4 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb546-18"><a href="sect073.html#cb546-18" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;GWR.B_Pct_brevet&quot;</span>, <span class="at">palette=</span><span class="st">&quot;-RdBu&quot;</span>, </span>
<span id="cb546-19"><a href="sect073.html#cb546-19" tabindex="-1"></a>                  <span class="at">breaks =</span> classes.intervalles,</span>
<span id="cb546-20"><a href="sect073.html#cb546-20" tabindex="-1"></a>                  <span class="at">title =</span> <span class="st">&quot;Faible scolarité (%)&quot;</span>)<span class="sc">+</span></span>
<span id="cb546-21"><a href="sect073.html#cb546-21" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span>
<span id="cb546-22"><a href="sect073.html#cb546-22" tabindex="-1"></a>Carte5 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb546-23"><a href="sect073.html#cb546-23" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;GWR.T_NivVieMed&quot;</span>, <span class="at">palette=</span><span class="st">&quot;-RdBu&quot;</span>, </span>
<span id="cb546-24"><a href="sect073.html#cb546-24" tabindex="-1"></a>                 <span class="at">breaks =</span> classes.intervalles,</span>
<span id="cb546-25"><a href="sect073.html#cb546-25" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">&quot;Niveau de vie (€1000)&quot;</span>)<span class="sc">+</span></span>
<span id="cb546-26"><a href="sect073.html#cb546-26" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)<span class="sc">+</span></span>
<span id="cb546-27"><a href="sect073.html#cb546-27" tabindex="-1"></a>          <span class="fu">tm_scale_bar</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span>
<span id="cb546-28"><a href="sect073.html#cb546-28" tabindex="-1"></a><span class="fu">tmap_arrange</span>(Carte1, Carte2, Carte3, Carte4, Carte5, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:GWRValT"></span>
<img src="GMQ405_files/figure-html/GWRValT-1.png" alt="Cartographie des valeurs de *t* de la GWR" width="85%" />
<p class="caption">
Figure 7.11: Cartographie des valeurs de <em>t</em> de la GWR
</p>
</div>
<p><strong>Cartographie du nombre de variables significatives</strong></p>
<p>Nous pouvons aussi cartographier le nombre de variables localement significatives aux seuils de 5% et 1%.</p>
<div class="sourceCode" id="cb547"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb547-1"><a href="sect073.html#cb547-1" tabindex="-1"></a><span class="do">## Identifier la variable plus significative avec les valeurs de t</span></span>
<span id="cb547-2"><a href="sect073.html#cb547-2" tabindex="-1"></a>VarsT <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;GWR.T_&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;Pct0_14&quot;</span>, <span class="st">&quot;Pct_65&quot;</span>, <span class="st">&quot;Pct_Img&quot;</span>, <span class="st">&quot;Pct_brevet&quot;</span>, <span class="st">&quot;NivVieMed&quot;</span>))</span>
<span id="cb547-3"><a href="sect073.html#cb547-3" tabindex="-1"></a>Lyon.df  <span class="ot">&lt;-</span> <span class="fu">st_drop_geometry</span>(LyonIris)</span>
<span id="cb547-4"><a href="sect073.html#cb547-4" tabindex="-1"></a>Lyon.df <span class="ot">&lt;-</span> <span class="fu">abs</span>(Lyon.df[,VarsT])</span>
<span id="cb547-5"><a href="sect073.html#cb547-5" tabindex="-1"></a>PlusSign <span class="ot">&lt;-</span> VarsT[<span class="fu">apply</span>(Lyon.df[VarsT],<span class="dv">1</span>,which.max)]</span>
<span id="cb547-6"><a href="sect073.html#cb547-6" tabindex="-1"></a>PlusSign <span class="ot">&lt;-</span> <span class="fu">substr</span>(PlusSign, <span class="dv">7</span>, <span class="fu">nchar</span>(PlusSign))</span>
<span id="cb547-7"><a href="sect073.html#cb547-7" tabindex="-1"></a>MaxAbsTvalue <span class="ot">&lt;-</span> <span class="fu">apply</span>(Lyon.df[VarsT], <span class="dv">1</span>, max)</span>
<span id="cb547-8"><a href="sect073.html#cb547-8" tabindex="-1"></a>PlusSign <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(MaxAbsTvalue<span class="sc">&lt;</span><span class="fl">1.96</span>, <span class="st">&quot;Aucune&quot;</span>, PlusSign)</span>
<span id="cb547-9"><a href="sect073.html#cb547-9" tabindex="-1"></a><span class="do">## Nombre de variables significatives au seuil de 5%, soit abs(t)= 1,96)</span></span>
<span id="cb547-10"><a href="sect073.html#cb547-10" tabindex="-1"></a>LyonIris<span class="sc">$</span>NbSignif_1<span class="fl">.96</span> <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">rowSums</span>(Lyon.df <span class="sc">&gt;</span> <span class="fl">1.96</span>))</span>
<span id="cb547-11"><a href="sect073.html#cb547-11" tabindex="-1"></a>LyonIris<span class="sc">$</span>NbSignif_2<span class="fl">.58</span> <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">rowSums</span>(Lyon.df <span class="sc">&gt;</span> <span class="fl">2.58</span>))</span>
<span id="cb547-12"><a href="sect073.html#cb547-12" tabindex="-1"></a>LyonIris<span class="sc">$</span>PlusSign      <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(PlusSign)</span>
<span id="cb547-13"><a href="sect073.html#cb547-13" tabindex="-1"></a><span class="do">## Cartographie</span></span>
<span id="cb547-14"><a href="sect073.html#cb547-14" tabindex="-1"></a>Carte1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb547-15"><a href="sect073.html#cb547-15" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;NbSignif_1.96&quot;</span>, <span class="at">palette=</span><span class="st">&quot;Reds&quot;</span>,</span>
<span id="cb547-16"><a href="sect073.html#cb547-16" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">&quot;Sign. au seuil de 5%&quot;</span>)<span class="sc">+</span></span>
<span id="cb547-17"><a href="sect073.html#cb547-17" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>)<span class="sc">+</span> <span class="fu">tm_scale_bar</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span>
<span id="cb547-18"><a href="sect073.html#cb547-18" tabindex="-1"></a>Carte2 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb547-19"><a href="sect073.html#cb547-19" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;NbSignif_2.58&quot;</span>, <span class="at">palette=</span><span class="st">&quot;Reds&quot;</span>, </span>
<span id="cb547-20"><a href="sect073.html#cb547-20" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">&quot;Sign. au seuil de 1%&quot;</span>)<span class="sc">+</span></span>
<span id="cb547-21"><a href="sect073.html#cb547-21" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>)</span>
<span id="cb547-22"><a href="sect073.html#cb547-22" tabindex="-1"></a><span class="fu">tmap_arrange</span>(Carte1, Carte2, <span class="at">ncol=</span><span class="dv">2</span>, <span class="at">nrow=</span><span class="dv">1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:GWRNNsign"></span>
<img src="GMQ405_files/figure-html/GWRNNsign-1.png" alt="Nombre de variables significatives aux seuils de 5% et 1%" width="85%" />
<p class="caption">
Figure 7.12: Nombre de variables significatives aux seuils de 5% et 1%
</p>
</div>
<p><strong>Cartographie de la variable la plus significative avec la valeur de <em>t</em></strong></p>
<p>Finalement, le code ci-dessous permet de repérer la variable la plus significative au seuil de 5%, c’est-à-dire avec la plus forte valeur absolue pour la valeur de <em>t</em>.</p>
<div class="sourceCode" id="cb548"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb548-1"><a href="sect073.html#cb548-1" tabindex="-1"></a><span class="fu">tm_shape</span>(LyonIris)<span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col=</span><span class="st">&quot;gray25&quot;</span>, <span class="at">lwd=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb548-2"><a href="sect073.html#cb548-2" tabindex="-1"></a>          <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">&quot;PlusSign&quot;</span>, <span class="at">palette=</span><span class="st">&quot;Set1&quot;</span>, </span>
<span id="cb548-3"><a href="sect073.html#cb548-3" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">&quot;Variable la plus significative&quot;</span>)<span class="sc">+</span></span>
<span id="cb548-4"><a href="sect073.html#cb548-4" tabindex="-1"></a>          <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>)<span class="sc">+</span> <span class="fu">tm_scale_bar</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:GWRPlussign"></span>
<img src="GMQ405_files/figure-html/GWRPlussign-1.png" alt="Variable indépendante la plus significative au seuil de 5 %" width="85%" />
<p class="caption">
Figure 7.13: Variable indépendante la plus significative au seuil de 5 %
</p>
</div>
</div>
</div>
</div>
<h3>Références</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-apparicio2007modelisation" class="csl-entry">
Apparicio, Philippe, Anne-Marie Séguin et Xavier Leloup. 2007. <span>« Modélisation spatiale de la pauvreté à Montréal: apport méthodologique de la régression géographiquement pondérée. »</span> <em>The Canadian Geographer/Le Géographe canadien</em> 51 (4): 412‑427. <a href="https://doi.org/10.1111/j.1541-0064.2007.00189.x">https://doi.org/10.1111/j.1541-0064.2007.00189.x</a>.
</div>
<div id="ref-packagesGWR" class="csl-entry">
Bivand, Roger et Danlin Yu. 2023. <em>spgwr: Geographically Weighted Regression</em>. s.n. <a href="https://CRAN.R-project.org/package=spgwr">https://CRAN.R-project.org/package=spgwr</a>.
</div>
<div id="ref-fotheringham2003geographically" class="csl-entry">
Fotheringham, A Stewart, Chris Brunsdon et Martin Charlton. 2003. <em>Geographically weighted regression: the analysis of spatially varying relationships</em>. John Wiley &amp; Sons.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sect072.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sect074.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["GMQ405.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
